### ISSUE TITLE
No method to reset step count

### ISSUE THREAD

**Issue by mossek2** [cph-cachet/flutter-plugins#1]
There appears to be no way to reset the step count was initiated.

**Comment by thomasnilsson** [comment]
This should be fixed now: By initializing a new Pedometer object, the step count is automatically reset.

**Comment by mychaelgo** [comment]
hi, i can't reset the step count, event if i init a new object of Pedometer. Any idea?

**Comment by Aashish-Dahal** [comment]
> This should be fixed now: By initializing a new Pedometer object, the step count is automatically reset.

Still issue , any updates on this 🙇
