### ISSUE TITLE
StreamSubsubription was never canceled

### ISSUE THREAD

**Issue by stefanschaller** [cph-cachet/flutter-plugins#10]
// old code
_lightStream.listen(onData,
          onError: onError, onDone: onDone, cancelOnError: true);

// new code 

_lightStreamSubScription = _lightStream.listen(onData,
          onError: onError, onDone: onDone, cancelOnError: true);

// You need to assign the StreamSubscription!! Thank you :)

**Comment by thomasnilsson** [comment]
It has been done, thank you for the feedback :)

**Comment by stefanschaller** [comment]
Top :D Thank you!
