### ISSUE TITLE
[health, 10.2.0 (latest)] Can the heart rate be read from a watch in real time?

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [cph-cachet/flutter-plugins#1005]
Can health (10.2.0, latest version at the time of writing) be used to read the heart rate from an Android or Apple watch in real time? Is this a supported feature?

**Comment by SlimShadyIAm** [comment]
Hi,

`health` is meant to interact with Apple Health only, so it can only whatever records are stored once the Apple Watch submits it to Apple Health (and similar for Android). There is no way to watch whatever the watches are reading in real-time.

**Comment by FluffyBunniesTasteTheBest** [comment]
Thank you very much for the clarification.
