### ISSUE TITLE
Add wind gust

### ISSUE THREAD

**Issue by RyanRamchandar** [cph-cachet/flutter-plugins#101]
**Plugin name & version**
weather: ^1.1.1

**Describe the bug**
Add wind gust parameter. This param is sometimes available as described in the API docs:

`wind`
- `wind.speed` Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour.
- `wind.deg` Wind direction, degrees (meteorological)
- `wind.gust` Wind gust. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour

see https://openweathermap.org/current#parameter

**Comment by MadsVSChristensen** [comment]
Wind gust has been added as of 1.2.2.

**Comment by RyanRamchandar** [comment]
Thanks!
