### ISSUE TITLE
[health 10.2.0] HealthDataType.SLEEP_IN_BED said to be available on Android but is not

### ISSUE THREAD

**Issue by Cyrille-Dakhlia** [cph-cachet/flutter-plugins#1010]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Pixel 3a
 - OS: Android 14.0

### Describe the bug
The `HealthDataType.SLEEP_IN_BED` is described to be [available on Android](https://github.com/cph-cachet/flutter-plugins/blob/e3a4530496351c9ba960e503e58ad28d7f2d32c3/packages/health/lib/src/heath_data_types.dart#L233), but the [documentation](https://pub.dev/packages/health#data-types) says it's not.
When running it on an Android simulator, the value returned for `HealthDataType.SLEEP_IN_BED` is indeed `null`, which makes me think that it is indeed not supported as the documentation says.

### To Reproduce
On an Android emulator, try to fetch the `HealthDataType.SLEEP_IN_BED` data type (it doesn't matter which start and end dates of collection are chosen)

### Expected behavior
If `HealthDataType.SLEEP_IN_BED` is supported on Android, then I expect to have a list of `HealthDataPoint`, or an empty list if no data are available.

If not, I expect to have the `HealthDataType.SLEEP_IN_BED` removed from the [constant](https://github.com/cph-cachet/flutter-plugins/blob/e3a4530496351c9ba960e503e58ad28d7f2d32c3/packages/health/lib/src/heath_data_types.dart#L233) `const List<HealthDataType> dataTypeKeysAndroid` defined in the library.

### Actual behavior
A null value is returned for that data type

**Comment by SlimShadyIAm** [comment]
@Cyrille-Dakhlia could you test if you experience this with my PR in #1026?

**Comment by Cyrille-Dakhlia** [comment]
Thank you very much @SlimShadyIAm

**Comment by SlimShadyIAm** [comment]
On a side note, as you have some sleep data on your device I'd really appreciate if you could test out my PR to see if you are able to pull all the data. I've expanded support for all the sleep stages Apple and Google support and I could use some help on the Android side of things :)

**Comment by Cyrille-Dakhlia** [comment]
Hi @SlimShadyIAm , it would be a pleasure to help, unfortunately I don't have sleep data on Android, I was actually testing it on an emulator :o 
I have an iOS device with sleep data though. Would you need help with that?
