### ISSUE TITLE
[Health] Add UUID to HealthDataPoint

### ISSUE THREAD

**Issue by DusanMicuda** [cph-cachet/flutter-plugins#1013]
Could you please add `uuid` property to `HealthDataPoint` ? The Health Connect provides [unique id](https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/metadata/Metadata#id()) of the data. It could be useful for saving this data to database on remote server.

**Comment by SlimShadyIAm** [comment]
Thanks for your suggestion, I will look into this and open a PR for it soon.

**Comment by SlimShadyIAm** [comment]
@DusanMicuda I'd appreciate if you could help test the PR I made above!

**Comment by DusanMicuda** [comment]
I appreciate your work, but I think that it would make sense, if you could implement the ios side as well. There you can use `HKObject.uuid`

**Comment by SlimShadyIAm** [comment]
Actually, it seems like the the iOS side was already implemented (e.g https://github.com/cph-cachet/flutter-plugins/blob/12a069b07d7659846acc525daae28827c16e7c86/packages/health/ios/Classes/SwiftHealthPlugin.swift#L823), it just wasn't read by our parsing code in Flutter.

**Comment by DusanMicuda** [comment]
Sorry, I didn't notice that. I'll check it.

**Comment by DusanMicuda** [comment]
Alright, I tested it. Looks like it works well for me 😁 Thank you so much 😊

**Comment by SlimShadyIAm** [comment]
Wonderful. It will be included in the next major release which I hope is in the next couple of weeks.
