### ISSUE TITLE
[health: 10.2.0] no default HealthWorkoutActivityType when no match is found

### ISSUE THREAD

**Issue by PawelBijok** [cph-cachet/flutter-plugins#1015]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Multiple Android devices
 - OS: Multiple Android versions (11,12,13,14)

### Describe the bug
`dataPoint['workoutActivityType']` does not always has matching `HealthWorkoutActivityType`

### Expected behavior
`HealthWorkoutActivityType.other` should be applied when no match is found to prevent throwing error 

### Actual behavior
Package throws error when no match from `HealthWorkoutActivityType` is found

**Comment by SlimShadyIAm** [comment]
Hi @PawelBijok, which activity type are you experiencing this issue with?

**Comment by nektar95** [comment]
this would be helpful for my app, i've got some recorded errors related to this issue, which is breaking fetching workouts for users 
<img width="686" alt="image" src="https://github.com/user-attachments/assets/93b468ae-12cf-4c84-ae33-790b21399b1d">

**Comment by PawelBijok** [comment]
Hi @SlimShadyIAm it is actually hard to tell, because I only have crashlytics stack trace with `Bad state: No element` just like @nektar95

**Comment by klubxxl** [comment]
I've encountered this issue in the past but couldn't find a matching issue report. The Bad state: No element error occurs when dataPoint['workoutActivityType'] doesn't match any HealthWorkoutActivityType, making the library unusable in some cases.

It would be great if HealthWorkoutActivityType.other could be applied by default when no match is found.
This fix would prevent crashes and improve usability.

**Comment by SlimShadyIAm** [comment]
Thanks all. I've just merged the fix for this (thanks to @PawelBijok for that!) and it will be included in 11.0.0 in the coming days.
