### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by georgeraveen** [cph-cachet/flutter-plugins#102]
How can I run activity recognition all the time in the background?

**Comment by thomasnilsson** [comment]
Thanks for the issue!

It seems to work on iOS in the background out of the box.

On Android, it seems a foreground service is needed to keep getting updates. We are working on it!

**Comment by thomasnilsson** [comment]
To consolidate the thread I will close this issue and refer to this instead: https://github.com/cph-cachet/flutter-plugins/issues/96
