### ISSUE TITLE
[Health 11.0.0] RecordingMethod.unknown returned for automatically added steps in Google Fit

### ISSUE THREAD

**Issue by tejasbadone** [cph-cachet/flutter-plugins#1036]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Realme 7 Pro [RMX2170]
 - OS: Realme UI 3.0 [Android 12]

### Describe the bug
When retrieving step data from Google Fit using the health package version 11.0.0, the RecordingMethod is returned as unknown even for steps that are automatically added by Google Fit. This issue occurs consistently, preventing accurate identification of the recording method.

### To Reproduce
1. Run the example app provided in the repository.
2. Grant Health Connect permissions.
3. Click the "Fetch Data" button.
4. Check the steps data in the list.

### Expected behavior
Recording method should be returned as RecordingMethod.automatic for automatically added steps.

### Actual behavior
Recording method returned as RecordingMethod.unknown for automatically and manually added steps too.

### Screenshots
![health](https://github.com/user-attachments/assets/686329fa-28e3-4f8a-acb6-dab98cf4ba8a)
![health1](https://github.com/user-attachments/assets/40a490b6-2ec9-4a4d-b990-e147f7c7a213)
![health2](https://github.com/user-attachments/assets/69250ce5-7f43-4aeb-a068-8f8a8a73e91a)

### Flutter doctor 
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4780], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2023.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.93.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by SlimShadyIAm** [comment]
Unfortunately, this is a limitation of how Google Fit adds the steps to Health Connect. The records added don't contain the recording method in the metadata and "unknown" is the default.
