### ISSUE TITLE
3.0.1

### ISSUE THREAD

**Issue by hariomloharapps** [cph-cachet/flutter-plugins#1068]
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app_usage'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 919ms
Error: Gradle task assembleDebug failed with exit code 1

**Comment by iarata** [comment]
@hariomloharapps Please specify which plugin this is

**Comment by iarata** [comment]
The `app_usage` plugin has all the proper namespaces for Android in both `build.gradle` and the example application runs fine in an emulator and a real device. Could you share more details on how you are trying to build the app_usage and your environment?
