### ISSUE TITLE
Failed to Build Release

### ISSUE THREAD

**Issue by addtek** [cph-cachet/flutter-plugins#107]
**Plugin name & version**
Which of the CACHET Flutter plugins is this issue related to and what is the version number.
screen_state version 0.1.1
**Describe the bug**
When i run my flutter app in debug it works fine but when i try to run release build it fails with the following error: 

```
Execution failed for task ':screen_state:verifyReleaseResources'.       
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\username\.gradle\caches\transforms-2\files-2.1\a528b13ac93e64cafa3d0480e2c93207\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
```
After removing the screen_state package from the project it then was able to build the release app

**Expected behavior**

**Actual behavior**
A clear and concise description of what did happen. Include stack traces and exception print-outs.

**Screenshots**

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for    
      detailed instructions.
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
**Smartphone(s) / Emulator**
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
Device: Android (Galaxy S8+)

**Comment by thomasnilsson** [comment]
The package has been updated to work with the newest Android API and should be working properly now :)

https://pub.dev/packages/screen_state
