### ISSUE TITLE
Hiring Request - Flutter Developer working on Health+AI APP (based in Shanghai)

### ISSUE THREAD

**Issue by celineycn** [cph-cachet/flutter-plugins#1075]
Hey Cachet Community,

We are a passionate team of medical professionals and AI specialists, committed to revolutionizing the way people manage their health. Our mission is to empower everyone around the globe to live longer, healthier lives through cutting-edge technology.
We’re currently looking for a Flutter Developer to join us in building our AI-driven health management app. If you're excited about leveraging the latest in AI to make a positive impact on people’s health, we’d love to hear from you.
If you’re interested, feel free to reach out to me!

Below is the job description

【重要的事情写在前面，这是一支想要为父母做一款用心的产品的年轻团队，希望招有类似Passion的同学一起撸产品快速迭代】

岗位职责
1.	负责iOS应用的架构设计及核心代码编写，优化应用性能，提升用户体验。
2.	根据产品需求，实现iOS端的高性能应用功能，支持产品的持续迭代。
3.	与多部门合作完成产品迭代，为iOS团队提供技术指导和支持，提升开发效率。
4.	编写高质量代码，进行代码审查，维护应用稳定性。
5.	研究新技术，探索前沿技术的应用，保持技术领先。
6.	管理应用的发布生命周期，包括测试、部署、更新和维护。

任职要求
1.	计算机科学或相关专业本科（211大学）及以上学历。
2.	精通Objective-C或Swift，熟悉iOS SDK和Xcode，具备良好的UI实现和网络编程能力。
3.	5年以上iOS开发经验，具有良好的应用架构设计和问题解决能力。
4.	熟悉Git等版本控制工具，了解一种非iOS编程语言优先。
5. 有flutter或Andriod开发经验优先，有医疗健康行业经验优先
6.	优秀的团队合作和沟通协调能力，能在团队中发挥技术领导作用。
7.	对技术有持续的热情，能快速学习新技术，有责任心，能适应快节奏工作环境。

Job Responsibilities:
- Responsible for architecture design and core code writing of iOS applications, optimizing performance and enhancing user experience.
- Implement high-performance application features on iOS based on product requirements, supporting continuous product iterations.
- Collaborate with multiple departments to complete product iterations, provide technical guidance and support to the iOS team, and improve development efficiency.
- Write high-quality code, conduct code reviews, and maintain the stability of the application.
- Research new technologies and explore the application of cutting-edge technologies to maintain technical leadership.
- Manage the application release lifecycle, including testing, deployment, updates, and maintenance.

Job Requirements:
- Bachelor's degree or above in Computer Science or relevant fields (preferably from a 211 university).
- Proficient in Objective-C or Swift, familiar with iOS SDK and Xcode, and skilled in UI implementation and network programming.
- 5+ years of iOS development experience, with strong ability in application architecture design and problem-solving.
- Familiar with version control tools like Git, with knowledge of at least one non-iOS programming language being a plus.
- Preferred: Experience with Flutter or Android development, and experience in the healthcare industry.
- Strong team collaboration and communication skills, with the ability to take a technical leadership role within the team.
- A passion for technology, with the ability to quickly learn new technologies, a strong sense of responsibility, and an ability to adapt to a fast-paced work environment.

**Comment by bardram** [comment]
Once you hire a developer, please make him/her contribute here with nice PRs.
