### ISSUE TITLE
Probleme With Pedometer Plugin 1.2.0

### ISSUE THREAD

**Issue by HamzaAyada** [cph-cachet/flutter-plugins#108]
I tried to build an application to count the steps (via plugin "Pedometer 1.2.0"),
but I find a big problem during the generation of the application. when i use an smartphone (android 10, 9) it does not work but with smartphone (android 8, 7, 6) it works correctly. I have consult that the sensor is null. is there a solution to fix the sensor error in version 9,10 of android?

E/SensorManager( 1460): sensor is null

![image](https://user-images.githubusercontent.com/49845208/86550642-d7ef1600-bf3a-11ea-9b26-5cd06d6e6287.png)

**Comment by thomasnilsson** [comment]
Thanks for the issue, this has been fixed in version 1.2.5 :) 

For Android 10 and above add the following permission to the Android manifest:

```dart
<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
```
