### ISSUE TITLE
Make the Stream<int> public

### ISSUE THREAD

**Issue by stefanschaller** [cph-cachet/flutter-plugins#11]
Please make the Stream<int> public! So i can use the rx operators and do some custom stuff

// Old code 
Stream<int> _lightStream;
_lightStream = _eventChannel.receiveBroadcastStream().map((lux) => lux);

// New code  - Assign the _eventChannel in the constructor
Stream<int> lightStream;

@override
Light() {
      lightStream = _eventChannel.receiveBroadcastStream().map((lux) => lux);
}

**Comment by thomasnilsson** [comment]
Done. :)
