### ISSUE TITLE
app_usage plugins giving wrong times

### ISSUE THREAD

**Issue by Volnetiks** [cph-cachet/flutter-plugins#111]
**Plugin name & version**
Using app_usage in last version.

**Describe the bug**
I create a double to get the total time spent on apps and get a huge number (47643 -> value given by last print, cf code used).

**To Reproduce**
Code Used:
Future<int> getTotalTime() async {
  double totalTime = 0;
  AppUsage appUsage = new AppUsage();
  try {
    DateTime endDate = new DateTime.now();
    DateTime startDate = DateTime(
        endDate.year, endDate.month, endDate.day, 0, 0, 0);

    Map<String, double> usage = await appUsage.fetchUsage(startDate, endDate);

    usage.removeWhere((key, value) => value == 0);
    usage.forEach((key, value) {
      print(key);
      print(value);
      totalTime += value;
    });
  }
  on AppUsageException catch (exception) {
    print(exception);
  }

  print(totalTime);
  return totalTime.round();
}

**Expected behavior**
The complete phone usage (addition of all times given)

**Actual behavior**
The print(total_time) gives a way to huge number in minutes. (47643)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [version 10.0.19041.329], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

**Smartphone(s) / Emulator**
 - Device: Huawei Mate 20
 - OS: Android 10 with EMUI 10.1

**Comment by Volnetiks** [comment]
I got a bit further into the problem, and it seems like my device gets the usage data for 3 days instead of one, and also gets android process which, I think, multiples the time by 2. Also if someone can check the 3 days things on a Samsung phone or any other phone. I will check it out as well.

**Comment by Volnetiks** [comment]
The problem isn't occuring on a oneplus 7, the problem probably comes from my EMUI 10.1.

**Comment by PriyaSindkar** [comment]
I am facing the same issue with motorola device. Getting wrong timings. I am using the same code as in your example.

**Comment by Volnetiks** [comment]
May I know which android version you are using?
And also could you check if it's the time for around past 3 days instead of one?

**Comment by PriyaSindkar** [comment]
Android Pie (9).. how do I check if data that is fetched is of how many days?

**Comment by Volnetiks** [comment]
There is something called Digital Balance, it should be in.
If it's not, I will try to check on others phone

**Comment by PriyaSindkar** [comment]
My device do not have Digital Balance but I have installed one app which gives usage history, according to it, the data I am getting from this plugin is 1-2 hours less than the combined 3-days usage timing

**Comment by PriyaSindkar** [comment]
I think we need to filter out apps with some categories like uninstaller, installer, deskclock, etc from the app list that we are getting from this plugin.. ?

**Comment by Volnetiks** [comment]
So it's kinda the same issue as I have, we should try at first to find where the timestamp to get usage is changed

**Comment by JRParreno** [comment]
> Android Pie (9).. how do I check if data that is fetched is of how many days?

me too I only get one specific day in one week, I always get the startDate when the first load of app still get that date it does not change the startDate. anyone solve this issue?
