### ISSUE TITLE
SensorLib integration as PR

### ISSUE THREAD

**Issue by nightscape** [cph-cachet/flutter-plugins#12]
I am considering using CARP as backend for a bio-feedback app. In order to support multiple devices, I was looking into [SensorLib](https://github.com/mad-lab-fau/SensorLib) and would contribute a corresponding PR if desired.
Is this the right repository for such a PR, or should I create a separate repository?

**Comment by bardram** [comment]
Thansk @nightscape for pointing us to SensorLib - this looks very interesting and seems to fit what we're trying to do with CARP mobile sensing. I will try to look further into SensorLib later. However, the way CARP mobile sensing is intended to be extended with additional sensing capabilities is described on our [wiki](https://github.com/cph-cachet/carp.sensing-flutter/wiki) -- especially in the section on [extending the framework](https://github.com/cph-cachet/carp.sensing-flutter/wiki/4.-Extending-CARP-Mobile-Sensing).
