### ISSUE TITLE
I am using pedometer plugin 1.2.0 , but am not able to access Pedometer class.

### ISSUE THREAD

**Issue by sandeepsoni25** [cph-cachet/flutter-plugins#121]
**Plugin name & version**
Which of the CACHET Flutter plugins is this issue related to and what is the version number.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what did happen. Include stack traces and exception print-outs.

**Screenshots**

**Flutter doctor**
Please run `flutter doctor` and add the output here.

**Smartphone(s) / Emulator**
Please complete the following information for each phone and/or emulator you're experiencing this bug on:

**Additional context**

**Comment by thomasnilsson** [comment]
I dont understand the issue.

You should also not be using an old version of the plugin, a newer version, 1.2.5 is available.
