### ISSUE TITLE
trouble installing 'pedometer' plugin

### ISSUE THREAD

**Issue by robes** [cph-cachet/flutter-plugins#13]
I'm having trouble getting the 'pedometer' v0.0.5 installed.

I added:
```
    pedometer: ^0.0.5
```
to the dependencies section of my flutter project's `pubspec.yaml`.

Then I ran `flutter packages get`.

I'm usually working out of Android Studio so I chose my emulator and hit the Run button.

The first error I get is:

```
...
   -> Installing pedometer (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `pedometer` does not specify a Swift version and none of the targets (`Runner`)
    integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```
(I also notice it reports "`podometer (0.0.1)`" above, which doesn't match the dependency version.)

I'm new to cocoapods (flutter and dart!) so took a guess that I could resolve this by adding
```
ENV['SWIFT_VERSION'] = '4.2'
```
to the `ios/Podfile`.

With that change, the build (`flutter run`) fails like so.
```
Xcode's output:
↳
    === BUILD TARGET pedometer OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/xxxxx/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/pedometer-0.0.5/ios/Classes/PedometerPlugin.m:2:9: fatal error:
    'pedometer/pedometer-Swift.h' file not found
    #import <pedometer/pedometer-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I assume that's probably a generated header file.

The installation instructions are really simple so I can't see that I missed any step.

**Comment by robes** [comment]
Never mind. I got it building/running in a new project that didn't have anything else going on in it. So it might just have been an issue with my local environment. I'll close this.

**Comment by mychaelgo** [comment]
@robes can you share your solution here? i have same problem too

**Comment by robes** [comment]
My problem was that I had not selected the support for Kotlin and Swift when setting up the project. These 2 checkboxes (in the screenshot) had to be selected in order for my project to build.

<img width="912" alt="Screen Shot 2019-07-25 at 8 33 43 PM" src="https://user-images.githubusercontent.com/4202842/61924241-caa06d80-af1b-11e9-89a6-ef4c1268f55a.png">

**Comment by mychaelgo** [comment]
@robes  thank you, anw, do you have any idea to reset pedometer counter steps? i've init a new object for pedometer, but it now works.

**Comment by robes** [comment]
You are just subscribing to a stream of pedometer readings. You cannot reset anything to my knowledge.

**Comment by mychaelgo** [comment]
@robes have you test if app is killed, is stream still get the data? because i test it when app in background, it does not counted anymore

**Comment by robes** [comment]
That's right. Its only going to call your app when it is in the foreground. If you want to check on the total steps recorded by the phone there is an API for that and a flutter plug in called 'simple_step_history' that I found useful.
