### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by vvatsaraj09** [cph-cachet/flutter-plugins#132]
I am using pedometer 1.2.5 and my build fails.
Here is the exception..
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pedometer:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\jayme\.gradle\caches\transforms-2\files-2.1\a0fcb6d94610446cbfe3fa7cb06e8419\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
     C:\Users\jayme\.gradle\caches\transforms-2\files-2.1\a0fcb6d94610446cbfe3fa7cb06e8419\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 10s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     251.4s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...
Please help me

**Comment by thomasnilsson** [comment]
An update to the pedometer plugin will be coming out today or tomorrow which hopefully solves these recurring Android problems

**Comment by thomasnilsson** [comment]
A new version of the plugin is out (2.0.1+1) which should solve the issue.

If the problem persists, feel free to create a new issue. This makes it easier to keep track of what version creates which problems :)
