### ISSUE TITLE
[Health][Android] Rejected authorization request never returns

### ISSUE THREAD

**Issue by TylerStein** [cph-cachet/flutter-plugins#133]
**Plugin name & version**
Health 1.1.4

**Describe the bug**
The invoked `requestAuthorization` plugin method on Android never returns the Future if the user does not complete authorization with their Google account.

**To Reproduce**
1. Run an app that calls `Health.requestAuthorization()` on Android
2. Tap off of the Google account dialog to cancel the authorization process
3. See that the `_channel.invokeMethod('requestAuthorization')` Future is never returned

**Expected behavior**
Invoking `requestAuthorization` should at least return false when the user cancels the authorization request by closing the Google account dialog.

**Actual behavior**
Invoking `requestAuthorization` and closing the Google account dialog without authorizing never returns the Future created in the `Health.requestAuthorization()` method.

**Screenshots**

**Flutter doctor**
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.959], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)
• No issues found!

**Smartphone(s) / Emulator**
 - Device: Samsung Galaxy S8 (SM-G950W)
 - OS: Android 9 (Kernel 4.4.153-17901174)

**Additional context**
I managed to solve the issue in a local copy of the plugin code by updating the `onActivityResult` method of `HealthPlugin.kt`
The change is in this pull request #134 

```kt
class HealthPlugin(val activity: Activity, val channel: MethodChannel) : MethodCallHandler, ActivityResultListener, Result {
...
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean {
        if (requestCode == GOOGLE_FIT_PERMISSIONS_REQUEST_CODE) {
            if (resultCode == Activity.RESULT_OK) {
                Log.d("FLUTTER_HEALTH", "Access Granted!")
                mResult?.success(true)
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.d("FLUTTER_HEALTH", "Access Denied!")
                mResult?.success(false);
            }
        }
        return false
    }
...
}
```

**Comment by thomasnilsson** [comment]
Merged the pull request and the changes are not live in version 1.1.5, thank you!
