### ISSUE TITLE
Pedometer not counting and showing '?' on the screen.

### ISSUE THREAD

**Issue by IndDevOrg** [cph-cachet/flutter-plugins#135]
Every mobile in which its tested is showing the same issue, most of the mobiles are of Samsung and with Android 8.1(Oreo) and below versions also if the problem is with my devices then how can I solve it and make it working?

Here is what I am getting in the Console section of Android Studio:
> E/SensorManager(  759): sensor or listener is null
D/ViewRootImpl@37d1545[MainActivity](  759): MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport(  759): Input channel destroyed: fd=87
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme pointer 0
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme pointer 1
D/ViewRootImpl@37d1545[MainActivity](  759): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager(  759): Starting input: tba=android.view.inputmethod.EditorInfo@ae6d9b5 nm : com.example.example ic=null
D/InputMethodManager(  759): startInputInner - Id : 0
I/InputMethodManager(  759): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(  759): Input channel constructed: fd=90
D/ViewRootImpl@37d1545[MainActivity](  759): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 3296503808} changed=false
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme pointer 0
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme pointer 1
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme key 0
D/ViewRootImpl@37d1545[MainActivity](  759): ViewPostIme key 1
D/ViewRootImpl@37d1545[MainActivity](  759): MSG_WINDOW_FOCUS_CHANGED 0
D/InputTransport(  759): Input channel destroyed: fd=90
D/SurfaceView(  759): onWindowVisibilityChanged(8) false 4dec0c1 of ViewRootImpl@37d1545[MainActivity]
D/SurfaceView(  759): BG show() Surface(name=Background for - SurfaceView - com.example.example/com.example.example.MainActivity@4dec0c1@0) io.flutter.view.FlutterView{4dec0c1 VFE...... .F...... 0,0-1080,1920}
D/SurfaceView(  759): surfaceDestroyed 1 #2 io.flutter.view.FlutterView{4dec0c1 VFE...... .F...... 0,0-1080,1920}
D/SurfaceView(  759): BG destroy() Surface(name=Background for - SurfaceView - com.example.example/com.example.example.MainActivity@4dec0c1@0) io.flutter.view.FlutterView{4dec0c1 VFE...... .F...... 0,0-1080,1920}
D/OpenGLRenderer(  759): eglDestroySurface = 0xdd88ac98, 0xc47ca800
D/ViewRootImpl@37d1545[MainActivity](  759): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x5 surface={valid=false 0} changed=true
D/SurfaceView(  759): windowStopped(true) false 4dec0c1 of ViewRootImpl@37d1545[MainActivity]
D/ViewRootImpl@37d1545[MainActivity](  759): dispatchDetachedFromWindow
D/InputEventReceiver(  759): channel '2b419c com.example.example/com.example.example.MainActivity (client)' ~ Disposing input event receiver.
D/InputEventReceiver(  759): channel '2b419c com.example.example/com.example.example.MainActivity (client)' ~NativeInputEventReceiver.

**Comment by thomasnilsson** [comment]
Version 2.0.0 of pedometer has been released. Please make a new issue if this issue persists :)
