### ISSUE TITLE
[HEALTH]aux.dart isn't downloaded on windows

### ISSUE THREAD

**Issue by takinok** [cph-cachet/flutter-plugins#137]
**Plugin name & version**
health 1.1.5

**Describe the bug**
Check below. Unfortunately aux is reserved name on Windows, so it's download as _aux.dart.
https://www.howtogeek.com/fyi/windows-10-still-wont-let-you-use-these-file-names-reserved-in-1974/

Now, i avoid this problem by changing import statement of 'health.dart'.
 part 'package:health/src/**_aux.dart**';

**To Reproduce**
1. just do 'pub get'

**Comment by thomasnilsson** [comment]
I will rename the file, thanks for letting us know 👍

**Comment by thomasnilsson** [comment]
Should be fixed in version 1.1.5+1 👍

Let me know if it works!

**Comment by takinok** [comment]
It works. Thank you for your prompt response.
