### ISSUE TITLE
Weather plugin - compatible with Android X

### ISSUE THREAD

**Issue by DARdk** [cph-cachet/flutter-plugins#14]
Weather plugin: 
Not compatible with Android X because it depends on locations 1.4.1 
(There is locations 2.0 which is compatible with androidX)
Would you be able to update it? 

Thanks!

**Comment by gedw99** [comment]
same issue for me too.

**Comment by thomasnilsson** [comment]
I am unable to get it working with location 2.0.0, due to the gradle changes introduced in the 2.0.0 version.

**Comment by bardram** [comment]
`location: ^2.3.5` seems to work fine. I've also migrated to AndroidX and location: ^2.3.5, so would appreciate an update to weather also.

**Comment by bardram** [comment]
Can we close this issue now @thomasnilsson ?
