### ISSUE TITLE
[pedometer]: Pedometer doesn't support sdk below 26

### ISSUE THREAD

**Issue by arnavvaryani** [cph-cachet/flutter-plugins#140]
Hi, I upgraded the dependency to 2.0.0 but it doesn't support sdk's below 26. Just wanted to confirm if this is a bug or not because I won't be able to use this dependency otherwise, the minSdk is too high! Please do something about it!

**Comment by thomasnilsson** [comment]
Using a lower SDK introduces complexity on our side. Why do you need such a low SDK?

**Comment by arnavvaryani** [comment]
The lowest SDK possible for the dependency to work would be best, as a lot of my audience have older devices hence low sdk versions!

**Comment by thomasnilsson** [comment]
In version 2.0.1+2 the minSdkVersion has been downgraded to 18, does this work for you?

**Comment by arnavvaryani** [comment]
Thanks! That works, also one more thing do the steps reset after the day changes?

**Comment by thomasnilsson** [comment]
You have to do this manually, unfortunately. The native API for Android does not allow you to reset the step counter, unless you reboot the phone.
