### ISSUE TITLE
[health] Improvement : Be more granular on what data access

### ISSUE THREAD

**Issue by younss** [cph-cachet/flutter-plugins#143]
**Plugin name & version**
health
**Describe the Request**
Instead of getting access to all measures. specify which measure the app access for. 
example:
Health.requestAuthorization(HealthDataType.WEIGHT, HealthDataType.STEPS,...)

**Comment by thomasnilsson** [comment]
This a good idea 👍

**Comment by thomasnilsson** [comment]
This is now implemented in version 2.0.1 https://pub.dev/packages/health

**Comment by LokiRathod** [comment]
But, If user want all the at once then, What will the solution ? @thomasnilsson

**Comment by thomasnilsson** [comment]
Make an issue, and use the template to state exactly what you want :)

**Comment by LokiRathod** [comment]
Ok I am creating one.

**Comment by younss** [comment]
It's better to be me more granular, if you need it all you pass all the datatypes you need in the autorization process.
