### ISSUE TITLE
PedometerPlugin  uninstall for ios

### ISSUE THREAD

**Issue by Pbosss** [cph-cachet/flutter-plugins#15]
In file included from
    /huahuacode/flutter/.pub-cache/hosted/pub.flutter-io.cn/pedometer-0.0.5/ios/Classes/PedometerPlugin.m:1:
    /huahuacode/flutter/.pub-cache/hosted/pub.flutter-io.cn/pedometer-0.0.5/ios/Classes/PedometerPlugin.h:3:12: note:
    'PedometerPlugin' declared here
    @interface PedometerPlugin : NSObject<FlutterPlugin>
               ^

![Uploading image.png…]()

**Comment by thomasnilsson** [comment]
I am having a hard time understanding the issue. Could you clarify? 
The image link is not working either.
