### ISSUE TITLE
[Pedometer] adb error launching application 

### ISSUE THREAD

**Issue by hho114** [cph-cachet/flutter-plugins#157]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: One Plus 5
 - OS: Android

### Describe the bug
I can not run an application with "flutter run", it shows the error "Failure [INSTALL_FAILED_DUPLICATE_PERMISSION:
Package ... attempting to redeclare permission android.permission.ACTIVITY_RECOGNITION already owned by
com.example.pedometer_example]"

### To Reproduce
I removed the "permission android:name="android.permission.ACTIVITY_RECOGNITION" in AndroidManifest.xml, and it work again.

I just want to know if I remove the permission from AndroidManifest.xml, will I have an issue in production in the future such as release application?

**Comment by thomasnilsson** [comment]
I am not sure what you mean:

- Are you having trouble running your own app, or the example app?
- What did you remove from the Android Manifest? (Just paste the new manifest)

**Comment by hho114** [comment]
it on my own app. Sorry for the confusion, I edited my post. I remove permission android:name="android.permission.ACTIVITY_RECOGNITION" in AndroidManifest.xml

**Comment by thomasnilsson** [comment]
What targetSDK and minimumSDK version are you using? 

I have no problems if I make a new Flutter app where I set targetSDK to 28, and minimumSDK to 18

**Comment by hho114** [comment]
My target SDK to 29, and minimum SDK to 18. By the way, it works on my android simulator. I think this problem appears because I installed an example app using a pedometer package on my device.

**Comment by thomasnilsson** [comment]
Was the issue resolved?

**Comment by hho114** [comment]
Yes, it is resolved. I found out I use wrong permission syntax, I forget to add "user-permission". You can close this issue.
