### ISSUE TITLE
In version 1.1.5 user is able to select/ give the permission all in one shot, But in version 2.0.0, its asking one-by-one.

### ISSUE THREAD

**Issue by LokiRathod** [cph-cachet/flutter-plugins#159]
As of now, we can pull the data from health app around 25 DataType's 
And in my app i need all  permissions at one shot, if would have wanted one or two, i would have asked only these permissions, But in my case, i need all at one time.

The version 1.1.5 was correct, Please can you guys revert back for that permission OR Any suggestions to get the all permissions in one shot.

**Comment by thomasnilsson** [comment]
Fixed in version 2.0.2 :)

Data is now fetched specifying multiple types:

```dart
List<HealthDataType> types = [
  HealthDataType.BODY_MASS_INDEX,
  HealthDataType.STEPS,
  HealthDataType.WEIGHT,
  HealthDataType.ACTIVE_ENERGY_BURNED
];

DateTime startDate = DateTime.utc(2001, 01, 01);
DateTime endDate = DateTime.now();

List<HealthDataPoint> healthData =
            await health.getHealthDataFromType(startDate, endDate, types);
```
