### ISSUE TITLE
[health] headless option

### ISSUE THREAD

**Issue by edcmex** [cph-cachet/flutter-plugins#178]
### Description
Could you make this headless compatible? I realize an activity may be need for health data authorization., but once that is granted could it run headless for background tasks.

**Comment by thomasnilsson** [comment]
I don't think I understand what you need; how is it not headless in its current state?

Is this an android or iOS specific thing? Google isn't giving me any useful results.

**Comment by edcmex** [comment]
Android only.

https://pub.dev/packages/background_fetch/ 

That plug-in allows tasks to run in the background even with the app completely closed within an isolate. 

Here is a related comment on the issue: https://github.com/transistorsoft/flutter_background_fetch/issues/25#issuecomment-492627846

**Comment by thomasnilsson** [comment]
If it is android only then I doubt we will use it. We aim to make the behaviour on both platforms as close to each other as possible. 

What do you say, @bardram ?

**Comment by ThangNguyen91** [comment]
Is there any solution to this problem?

**Comment by thomasnilsson** [comment]
Feel free to make a pull request that implements this functionality.

**Comment by alpapado** [comment]
I am facing a similar problem. 

I use the Flutter workmanager plugin (https://github.com/fluttercommunity/flutter_workmanager) which can be used to schedule tasks to execute periodically in the background both in Android and iOS. 

While I can successfully fetch data upon pressing a button in the Flutter UI, I get an "Authorization not granted" when running the same operation via the workmanager. The necessary permissions have been granted prior to the workmanager executing the task. 

Do you have any ideas or pointers as to what might be the issue with the permission not being granted when executing in the background?

**Comment by JapneetSingh-28** [comment]
Hi all, Any update on how to handle the heath package with the workmanager when the flutter app is in the background?

**Comment by chukovskid** [comment]
We are having the same problem, are there some updates? Also, we opened a new issue regarding [this](https://github.com/cph-cachet/flutter-plugins/issues/465)

**Comment by robisaks** [comment]
For anyone coming to this thread, someone has done the work for this in a fork. 
https://github.com/indolex/flutter-plugins/commit/63af2f5c7d6cc39228017b14f8f77fa695830b36

**Comment by harryandroiddev** [comment]
But according to the docs of the health connect you cannot use health connect in the background .
https://developer.android.com/health-and-fitness/guides/health-connect/plan/developer-functionality
