### ISSUE TITLE
in PedometerPlugin.m,  pedometer/pedometer-Swift.h file cannot be found

### ISSUE THREAD

**Issue by yuzhihang** [cph-cachet/flutter-plugins#18]
#import "PedometerPlugin.h"
#import <pedometer/pedometer-Swift.h>

@implementation PedometerPlugin
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar>*)registrar {
  [SwiftPedometerPlugin registerWithRegistrar:registrar];
}
@end

**Comment by thomasnilsson** [comment]
I can't replicate the issue. Please use the issue template and provide us with more details, thanks!
