### ISSUE TITLE
[carp_background_location] background processing, when not running the app

### ISSUE THREAD

**Issue by fre391** [cph-cachet/flutter-plugins#183]
Hi,

what a great plugin -  I love it. Thx for sharing. However, I would have an improvment, propably worth thinking about it:

- The package is designed to run the location service, even if the app itself is no more running. Thats a great option, but it would be even better, if we could configure, the service to stop in case the app is closed / or crashes. The users today are very sensible to accept that an app will expect location access all day long, even if the app itself is not running. Also there a lot of scenarios, where it is not really necessary. I know, the user can choose at startup to allow temporarilly, but then the background service is no more delivering data, even if the app is in front.

Would be great, if you could add a feature like this, because the app is running really stable in background on android. Thank you so much again.

Best regards

**Comment by fre391** [comment]
Found a solution, but this will cause a little bug as follows:
in android_manifest I have done the following changes:

        <receiver
                android:name="rekab.app.background_locator.LocatorBroadcastReceiver"
                android:enabled="true"
                android:exported="true"
                android:stopWithTask="true"
        />
        <service
                android:name="rekab.app.background_locator.LocatorService"
                android:permission="android.permission.BIND_JOB_SERVICE"
                android:exported="true"
                android:stopWithTask="true"
        />
        <service
                android:name="rekab.app.background_locator.IsolateHolderService"
                android:permission="android.permission.FOREGROUND_SERVICE"
                android:exported="true"
                android:stopWithTask="true"
        />

Also, I have deleted the following part, because no more needed:

        <receiver android:name="rekab.app.background_locator.BootBroadcastReceiver"
                  android:enabled="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>

It works well as now the service is stopped when the app exits. The following issues occure:

1. When the app will be started again, the receiver will find the service running and locations are delivered. I asssume, that the service was NOT stopped completely.

2. The user still needs to allow that the service needs unlimited access. I think, that could be solved, if _checkLocationPermission() in location_manager.dart would be changed accordingly.

3. Of course, this change will not work for IOS. What would be the approach here?

Would be great to get any feedback on this....Thanks again

**Comment by thomasnilsson** [comment]
It is not an issue for iOS as far as I am aware. 

I don't think it is possible to achieve the behaviour you want, which all comes back to the way that Google changed their location API earlier this year, making a background service which runs constantly the only way to get location.
