### ISSUE TITLE
[carp_background_location] background process for IOS 

### ISSUE THREAD

**Issue by fre391** [cph-cachet/flutter-plugins#184]
I have tested the package on an old iPad (IOS 9.3.5) and it seems that the location will be delivered every 5 minutes, regardless the setting of the locationManager.interval. No error message occures.

Not sure, if this might be a restriction of the operation system or just some performance issue. Just, let me know, if I can help by testing a specific setting or new version.

Thanks

Markus

**Comment by thomasnilsson** [comment]
Thanks for pointing this out: 
The interval only has an effect on Android. This has been updated in the documentation now.
