### ISSUE TITLE
[movisens] Sensor is not connecting 

### ISSUE THREAD

**Issue by attex** [cph-cachet/flutter-plugins#186]
Hi there, 
i am having trouble with a movisens sensor, as it seems to not connect with the app.

I used the example project provided in the plugin. 

My log: 
`
D/BleUtils(16423): Read DATA_AVAILABLE
I/MovisensService(16423): BLE: Gatt services discovered
I/BLEConnectionHandler(16423): onServicesDiscovered received: 0
I/MovisensService(16423): Received data from characteristic Measurement: f89edec7-f7e0-94f2-747d-ee7acaa6d412, data: 00
I/BLEConnectionHandler(16423): onServicesDiscovered received: 0
D/BluetoothGatt(16423): onConnectionUpdated() - Device=00:07:80:78:63:A5 interval=36 latency=0 timeout=500 status=0
D/BluetoothGatt(16423): onClientConnectionState() - status=8 clientIf=9 device=00:07:80:78:63:A5
D/BluetoothGatt(16423): close()
D/BluetoothGatt(16423): unregisterApp() - mClientIf=9
I/BLEConnectionHandler(16423): onServicesDiscovered received: 133
I/BLEConnectionHandler(16423): Gatt server error, status: 8, newState: 0
D/BLEConnectionHandler(16423): Reconnect in 21434 ms
D/S: CONNECTION_STATUS(16423): sensor_disconnected
I/MovisensService(16423): BLE: Gatt services error
D/CONNECTION_STATUS(16423): {connection_status=sensor_disconnected, timestamp=2020-09-14 07:20:17}
D/ANDROID_DATA(16423): {connection_status={connection_status=sensor_disconnected, timestamp=2020-09-14 07:20:17}}
D/BluetoothGatt(16423): connect() - device: 00:07:80:78:63:A5, auto: false
D/BluetoothGatt(16423): registerApp()
D/BluetoothGatt(16423): registerApp() - UUID=6efd2db6-521f-4425-b4fb-ee9874688407
D/BluetoothGatt(16423): onClientRegistered() - status=0 clientIf=9
D/BluetoothGatt(16423): refresh() - device: 00:07:80:78:63:A5
I/BLEConnectionHandler(16423): Trying to reconnect
I/BLEConnectionHandler(16423): Initiate connect device
I/BLEConnectionHandler(16423): Bluetoth Device refreshing successful: true
I/BLEConnectionHandler(16423): Trying to create a new connection.
D/BluetoothGatt(16423): onClientConnectionState() - status=0 clientIf=9 device=00:07:80:78:63:A5
D/BluetoothGatt(16423): discoverServices() - device: 00:07:80:78:63:A5
D/S: CONNECTION_STATUS(16423): sensor_connected
I/MovisensService(16423): BLE: GATT Connected
I/BLEConnectionHandler(16423): Connected to GATT server.
I/BLEConnectionHandler(16423): Attempting to start service discovery:true
D/CONNECTION_STATUS(16423): {connection_status=sensor_connected, timestamp=2020-09-14 07:20:44}
D/ANDROID_DATA(16423): {connection_status={connection_status=sensor_connected, timestamp=2020-09-14 07:20:44}}
D/BluetoothGatt(16423): onConnectionUpdated() - Device=00:07:80:78:63:A5 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(16423): onSearchComplete() = Device=00:07:80:78:63:A5 Status=0
D/uuid_   (16423): UUID is f89edeb6-e4e8-928b-4cfa-ebc07fce1768gattService.getUuid() isf89edeb6-e4e8-928b-4cfa-ebc07fce1768
D/gattCharacteristicId (16423): f1cc0780-95e8-4a93-a1d1-6cfac6641b24
D/gattCharacteristicId (16423): f89edec4-d590-764d-530f-8fff5c181606
D/gattCharacteristicId (16423): 8f717cee-030c-4628-9d76-4e3fd9d74fb6
D/gattCharacteristicId (16423): 0086b101-7f7d-4249-bfae-1999065a68c2
D/gattCharacteristicId (16423): 10847e7a-d43f-4b9e-b2f2-3e8546215c3c
D/gattCharacteristicId (16423): f89edec2-9fc2-c29e-ff29-da323b327e44
D/gattCharacteristicId (16423): f89edec7-f7e0-94f2-747d-ee7acaa6d412

`

As you can see the app constantly connects and disconnects to the sensor.

Hope someone can help!

**Comment by thomasnilsson** [comment]
This plugin was very complicated to develop and debug, do not expect this to be fixed fast.

**Comment by thomasnilsson** [comment]
@devhci

**Comment by attex** [comment]
I found the solution to this issue.
After contacting the movisens team i've been told that there might been an issue with newer phones in the movisens firmware. 

So i switched to another device (Google Pixel 4) which works fine!

They are still working on this issue and will soon release a new firmware.
