### ISSUE TITLE
Add history request to API.

### ISSUE THREAD

**Issue by MichalMisiaszek** [cph-cachet/flutter-plugins#19]
The free API key provides access to free historical data as well. Can it be exposed in the plugin? I am interested in the last 24 hours of rainfall and this can be calculated from historical data every hour.

**Comment by thomasnilsson** [comment]
Noted, will have a look!

**Comment by thomasnilsson** [comment]
It seems this was removed as a free feature unfortunately. https://openweathermap.org/price#history
