### ISSUE TITLE
Weather version 1.2.2 - insecure HTTP is not allowed by platform

### ISSUE THREAD

**Issue by kevin6shah** [cph-cachet/flutter-plugins#192]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: iPhone 11 Pro Max (Device & Simulator)
 - OS: iOS 14

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
When attempting to use the plugin in flutter, I get an error that says "insecure HTTP is not allowed by platform" along with the insecure (http) link to the openweather api. 

So I tried to change the following line in the _buildURL function and my app worked as it should:

```dart
String url = 'http://api.openweathermap.org/data/2.5/' + '$tag?';   // Change this
String url = 'https://api.openweathermap.org/data/2.5/' + '$tag?';  // To this
```

### To Reproduce
Just run the following code in the init method of any stateful widget:

```dart
WeatherFactory wf = new WeatherFactory(API_KEY_HERE);
Future<List<Weather>> getWeatherInfo() async {
     return await wf.fiveDayForecastByLocation(40.500615, -74.447496);
}
getWeatherInfo()
```

### Expected behavior
Expected to not get an exception here

### Actual behavior
Threw an exception as stated above

### Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.338, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (not installed)
[✓] VS Code (version 1.49.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.

**Comment by thomasnilsson** [comment]
Thanks, corrected this in version 1.2.3 👍
