### ISSUE TITLE
Plugin crashed.

### ISSUE THREAD

**Issue by MichalMisiaszek** [cph-cachet/flutter-plugins#20]
Hi,
PLugin crashed on emulator due to location plugin crashing. I have seen it before.
Is there a way to provide location to Weather plugin instead of plugin using current location? I am using diffrent location plugin(paid) which is much more stable.
Thanks
Michal

**Comment by MichalMisiaszek** [comment]
It crashed couple of times again. Can you provide API where location is provided by app not requested in background ? It is conflicting with my other location plugin causing wrong locations and crashes.

**Comment by thomasnilsson** [comment]
The latest version supports custom latitude and longitude https://pub.dev/packages/weather

We are working on removing the dependency on location entirely. Stay tuned.
