### ISSUE TITLE
[health]`callToHealthTypes` in HelathPlugin.kt calls `keyToHealthDataType` with wrong key always.

### ISSUE THREAD

**Issue by bakatsuyuki** [cph-cachet/flutter-plugins#201]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Pixel 3a
 - Android 10

### Describe the bug
`callToHealthTypes` method calls `keyToHealthDataType` with wrong key that is `ArrayList.toString()`. `ArrayList.toString()` returns `[WEIGHT]` for example.

### Expected behavior
- DataPoints return always empty.

### Additional information
There is PR.
https://github.com/cph-cachet/flutter-plugins/pull/200

**Comment by TylerStein** [comment]
+1 applying this fixed an issue where permissions were not being granted on my end, resulting in Google auth errors when retrieving data. Thanks for the fix! 

Tested on a Galaxy S8 and a Pixel 3a for the permissions: BODY_FAT_PERCENTAGE, STEPS, HEART_RATE, BODY_TEMPERATURE, BLOOD_GLUCOSE

**Comment by thomasnilsson** [comment]
Thank you, I will review and merge this.

**Comment by thomasnilsson** [comment]
Merged in version 2.0.7 :)
