### ISSUE TITLE
[health]GoogleSignIn.getAccountForExtension in `HelathPlugin.kt#getData` uses permissions that is not requested.

### ISSUE THREAD

**Issue by bakatsuyuki** [cph-cachet/flutter-plugins#203]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Pixel 3a
 - Android 10

### Describe the bug
`GoogleSignIn.getAccountForExtension` in `HelathPlugin.kt#getData` uses permissions that is not requested. Then, `GoogleSignIn.getAccountForExtension`  returns no account. So `Fitness.getHistoryClient` returns always empty data points.

### Additional information
There is PR.
https://github.com/cph-cachet/flutter-plugins/pull/202

**Comment by thomasnilsson** [comment]
Thank you, I will have a look at it.

**Comment by thomasnilsson** [comment]
Merged in version 2.0.7 :)
