### ISSUE TITLE
[health] MINDFULNESS has wrong unit 

### ISSUE THREAD

**Issue by Mishanya840** [cph-cachet/flutter-plugins#208]
**Remember to specify the plugin name in the title!**

### Device 
 - Device: iPhone 6 plus
 - OS: iOS 12.4.8

### Describe the bug

<img width="687" alt="Снимок экрана 2020-10-13 в 18 18 26" src="https://user-images.githubusercontent.com/6845754/95881144-f312c280-0d80-11eb-8b33-76bfb6ff2ce6.png">

**Comment by thomasnilsson** [comment]
A merge issue had deleted some of these data types. Version 2.0.8 should be up to speed. Can you let me know if the problem is solved now?
