### ISSUE TITLE
[activity_recognition_flutter] Does not work on Android 10 / SDK level 29

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#215]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Samsung Galaxy 
 - OS: OS level 10.0, API 29

### Describe the bug
When trying to run the example app with OS level 10, SDK target to 29, I get 

`requestActivityUpdates: Failed to enable Activity updates: 10: SecurityException: Activity detection usage requires the ACTIVITY_RECOGNITION permission`

### To Reproduce

In the `build.graddle` file I change to:

`compileSdkVersion 29`

I also update the `manifest.xml` file with

`<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION permission" />`

as said in the README file.

### Expected behavior

That activity recognition also works on Android 10.

**Comment by bardram** [comment]
This is the root cause of this CAMS issue >> https://github.com/cph-cachet/carp.sensing-flutter/issues/104

**Comment by thomasnilsson** [comment]
Check the documentation of version 1.2.4. The permission handler plugin should be for android API >= 29:

```dart
import 'package:activity_recognition_flutter/activity_recognition_flutter.dart';
import 'package:permission_handler/permission_handler.dart';

Stream<Activity> activityStream;

@override
void initState() {
    super.initState();
    _init();
}

void _init() async {
    /// Ask for permission
    if (await Permission.activityRecognition.request().isGranted) {
      activityStream = ActivityRecognition.activityUpdates();
      activityStream.listen(onData);
    }
}

void onData(Activity activity) {
    /// Do something with the received activity
    ActivityType type = activity.type;
    int confidence = activity.confidence;
}
```

**Comment by bardram** [comment]
The `build.graddle` file was still on SDK 28. So in order to check, I've updated it to SDK 29 and updated the README file -- there were some errors in the xml. Have published a small updated.
