### ISSUE TITLE
carp_background_location 1.0.2+1

### ISSUE THREAD

**Issue by joranmulderij** [cph-cachet/flutter-plugins#220]
**App crashes when killed due to carp_background_location**

### Device / Emulator and OS
 - Device: Samsung A300F
 - OS: Android 5.1

### Problem
App crashes when killed (displays a crash dialog).

### To Reproduce
Create a flutter project and follow the instructions in the pub README file.
Run the app on a device, wait for the device to get a location.
Kill the app

### Expected behavior
I would expect the background process to recognize that the main app has been killed, and kill itself.

**Comment by thomasnilsson** [comment]
It works fine on the Samsung Galaxy A21S and the Android emulator for me, i.e. I can kill the app without it crashing.

Perhaps I am misunderstanding the issue? The background service is not supposed to get terminated, since it is necessary for the application to get location updates.

**Comment by joranmulderij** [comment]
Does the location callback function have to be a top-level function? It doesn't say so on pub.dev, nor in the example, but how would the program be able to receive updates otherwise, when the program itself is terminated?

**Comment by thomasnilsson** [comment]
The app does not receive updates while it is terminated, of course, but it uses the foreground service as a hook. When the app is started it checks whether the hook is exists or should be created.
