### ISSUE TITLE
[app_usage] usage doesn't return the correct value in the interval

### ISSUE THREAD

**Issue by apoleo88** [cph-cachet/flutter-plugins#226]
### Emulator and OS
 - Device: Pixel 2 XL Android

### Describe the bug
usage property doesn't return the correct value.

### Expected behavior
According to the documentation usage should return only the usage in that interval:
```
  /// The amount of time the application has been used
  /// in the specified interval
  Duration get usage;
```

However the interval is not respected in the usage result.
**1 minute** interval:
```
app: youtube (google)
usage: :0:14:47.000000
interval: 2020-11-15T15:07:31.944562 -- 2020-11-15T15:08:31.944562
```

**10 minute** interval:

```
app:youtube (google) 
usage: :0:14:53.000000
interval: 2020-11-15T15:07:07.320441 -- 2020-11-15T15:17:07.320441
```

### Expected behavior
The returned value should be the use in the interval and anyway less or equal the duration of the interval.

### Actual behavior
It seems to return the total usage from reboot.

### Flutter doctor 
[√] Flutter (Channel beta, 1.22.1, on Microsoft Windows [Versione 10.0.19041.610], locale it-IT)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\_Apoleo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
    • All Android licenses accepted.

[√] Connected device
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by thomasnilsson** [comment]
This error has something to do with how the app usage statistics from Google are made. 
From the documentation it seems that it is not accurate down to the minute, but is rather course grained (i.e. probably hourly, or even daily) https://developer.android.com/reference/android/app/usage/UsageStatsManager

We are trying to see if we can make the plugin a little more accurate since it seems that the precision can be tweaked natively.

Stay tuned 👍

**Comment by thomasnilsson** [comment]
It does not seem there is a solution to this, problem; Google's API is simply not precise enough. 

In version 1.1.1 the documentation has been updated to reflect this issue.
