### ISSUE TITLE
Health: No entitlement

### ISSUE THREAD

**Issue by garlicgit** [cph-cachet/flutter-plugins#227]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: 10xs
 - OS: IOS 14

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
Info.plist updated per documentation, but still receiving entitlement error

flutter: HealthDataType.STEPS, false
[default] fetchContainerAppExtensionEntitlementsWithCompletion: failed with error: Error Domain=com.apple.healthkit Code=4 "Missing com.apple.developer.healthkit entitlement." UserInfo={NSLocalizedDescription=Missing com.apple.developer.healthkit entitlement.}
[default] fetchContainerAppExtensionEntitlementsWithCompletion: failed with error: Error Domain=com.apple.healthkit Code=4 "Missing com.apple.developer.healthkit entitlement." UserInfo={NSLocalizedDescription=Missing com.apple.developer.healthkit entitlement.}

### To Reproduce

_getHealth() async {

    /// Get everything from midnight until now
    DateTime endDate = DateTime.now();
    DateTime startDate = DateTime(2020, 11, 14);

    HealthFactory health = HealthFactory();

    /// Define the types to get.
    List<HealthDataType> types = [
      HealthDataType.BODY_MASS_INDEX,
      HealthDataType.WEIGHT,
      HealthDataType.ACTIVE_ENERGY_BURNED,
      HealthDataType.WATER,
      HealthDataType.SLEEP_ASLEEP,
      HealthDataType.SLEEP_AWAKE,
      HealthDataType.SLEEP_IN_BED,
      HealthDataType.MINDFULNESS,
      HealthDataType.DISTANCE_WALKING_RUNNING,
      HealthDataType.FLIGHTS_CLIMBED,
      HealthDataType.MOVE_MINUTES,
      HealthDataType.HEART_RATE,
      HealthDataType.STEPS
    ];

    /// Fetch new data
    List<HealthDataPoint> healthData =
    await health.getHealthDataFromTypes(startDate, endDate, types);

    /// Save all the new data points
    _healthDataList.addAll(healthData);

    /// Filter out duplicates
    _healthDataList = HealthFactory.removeDuplicates(_healthDataList);

    /// Print the results
    _healthDataList.forEach(
            (x) => print("Data point: $x")
    );
  }

### Expected behavior
Print data

### Actual behavior
Entitlement exception

### Screenshots
See above

### Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.251, on macOS 11.0 20A5384c
    darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)

### Additional information
None

**Comment by thomasnilsson** [comment]
When I copy paste all the code and the permissions from the description on pub.dev it works fine.

Have you made sure to add the HealthKit capability in the xcode project?
