### ISSUE TITLE
GoogleSignIn Pop-Up still appears, after successful permission request

### ISSUE THREAD

**Issue by LoadJulz** [cph-cachet/flutter-plugins#229]
[###](url) Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Emulator, Huawei Nova
 - OS: Android 11

### Describe the bug
GoogleSignIn Pop-Up still appears after requesting the Permission for the GoogleFit Data, when requesting GoogleFit Data.

### To Reproduce
First requestAuthorization for GoogleFitData (e.g. steps). Accept the dialog to give permission for the healthData. When calling getHealthDataFromTypes the googleSignIn Pop-Up shortly appears and then disappears. This happens everytime getHealthDataFromTypes is called. It looks like a short a black Frame appears for a second.

Link to video that shows the bug: https://drive.google.com/file/d/1061W3nk3yPEE_rFQtEA4yhJp5IgoyBFZ/view?usp=sharing

### Flutter doctor 
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.5 19F101, locale de-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by cadaniel** [comment]
The same thing is happening with Pedometer 2.0.2

**Comment by thomasnilsson** [comment]
> The same thing is happening with Pedometer 2.0.2

I cannot reproduce this. Please make an issue.

**Comment by thomasnilsson** [comment]
I have made good progress in this issue, but an update is not ready just yet.

**Comment by connlaoi** [comment]
> I have made good progress in this issue, but an update is not ready just yet.

@thomasnilsson Do you have an ETA for when a fix will be available, or suggestions for an interim solution?

**Comment by tonileppanen** [comment]
I fixed the flickering by commenting out all unnecessary rows from fitnessOptions.builder()

**Comment by connlaoi** [comment]
> I fixed the flickering by commenting out all unnecessary rows from fitnessOptions.builder()

I was indeed able to fix the bug by keeping only the Fitness API values authorized by our OAuth Service Token.

For those interested in using this as an interim solution, see here (guide for using a customized existing package):  
https://medium.com/flutter-community/how-to-modify-an-existing-pub-package-to-use-in-your-flutter-project-4e909452ee66

In order to access the nested packages you will need to use the path option shown below in your pubspec.yaml.
```
  health:
    git:
      url: https://github.com/[username or collection]/flutter-plugins.git
        path: packages/health
```

Hope this helps someone in the meantime. @tonileppanen thanks for pointing me in the right direction. :)

**Comment by t-animal** [comment]
We can confirm that the bug is gone with version 3.0.0 of the health plugin.

**Comment by thomasnilsson** [comment]
Awesome.
