### ISSUE TITLE
Pedometer 2.0.2 complileSdkVersion 29

### ISSUE THREAD

**Issue by mjarpitanand** [cph-cachet/flutter-plugins#235]
Pedometer 2.0.2 complileSdkVersion 29

### Device / Emulator and OS

 - Android compile sdk version 29
 - ios 

### Describe the bug
Pedometer plugin is not working when complile sdk version is 29 in app/build.grade file , how ever for 28 is working 

### To Reproduce
Just put  complile sdk version is 29 in app/build.grade file

### Expected behavior
Error - registerListener fail (1) :: 16, SAMSUNG Step Detector Sensor, 0, 0,  

### Actual behavior
What did happen? Include stack traces and exception print-outs.

**Comment by thomasnilsson** [comment]
You should put the SDK version 29 in both gradle files, it works fine for me :)

**Comment by MarcelHH** [comment]
how exactly at which point? the android / build gradle is completely different
