### ISSUE TITLE
app_usage: ^1.0.2

### ISSUE THREAD

**Issue by rmaatouk** [cph-cachet/flutter-plugins#241]
Hello , when i add this package to my pubsbec.yaml and when i run my app  , it takes me to settibgs 

--> usage data access : and then i need allow usage tracking

The problem is that its directing the user directtly to this page even before opening the app .

**Comment by thomasnilsson** [comment]
Thanks for the issue. It is now fixed in version 1.1.0

**Comment by sendi404** [comment]
help please app usage not with icon. how to replace icon for my app_usage
