### ISSUE TITLE
health 2.0.9 write samples?

### ISSUE THREAD

**Issue by brightmind-loredo** [cph-cachet/flutter-plugins#245]
### Description
Do you have any plans to enhance the Health plug-in to write health data?

### Additional information
I am developing a Flutter app that needs to write data to Droid and iOS health. (Google Fit and Apple Health Kit)

**Comment by thomasnilsson** [comment]
Currently we do not allocate resources to implement functionality outside of what we need ourselves.

Feel free to make a pull request that implements this functionality.
