### ISSUE TITLE
[health 3.0.0] Steps are fetched with incorrect value

### ISSUE THREAD

**Issue by AmandaOlearczuk** [cph-cachet/flutter-plugins#252]
### Device / Emulator and OS
Samsung with Android 10

### Describe the bug
The step value is fetched incorrectly sometimes. For example, today my steps are 953, but the plugin gives me the step points that sum to be 1679.
![Screenshot_20201216-151723_Fit](https://user-images.githubusercontent.com/35851317/102413510-46d49e80-3fb2-11eb-9aae-480ab1f97e45.jpg)

### To Reproduce
Run this method to get steps for a few past days from google fit and some values will not match.
```
  Future<int> getStepsForDay(DateTime day) async {
    var startDate = DateTime(day.year, day.month, day.day, 0, 0);
    var endDate = DateTime(day.year, day.month, day.day, 23, 59, 59, 59, 59);
    try {
      var stepsDataPoints = await _factory
          .getHealthDataFromTypes(startDate, endDate, [HealthDataType.STEPS]);

      stepsDataPoints = HealthFactory.removeDuplicates(stepsDataPoints);

      var totalSteps = 0;
      for (HealthDataPoint dataPoint in stepsDataPoints) {
        print(dataPoint.value.toString());
        totalSteps += dataPoint.value.toInt();
      }

    print("Total steps from this day are: " + totalSteps.toString());
      return totalSteps;

    } on Exception catch (_) {
      return 0;
    }
  }
```

### Expected behavior
Expect to receive the same total number of steps as in the google fit app.

### Actual behavior
The number of steps in google fit from a day is different then the sum of step points received from plugin

### Flutter doctor 
```
[√] Flutter (Channel master, 1.26.0-2.0.pre.56, on Microsoft Windows [Version 10.0.19041.685], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.0)
[√] Connected device (3 available)

• No issues found!
```

**Comment by thomasnilsson** [comment]
I get the correct values for the few days of data that I have on my android developer phone. Have you tried doing this sum of steps over a month? Maybe it has something to do with timezones, that is the only thing I can think of!

**Comment by oakmad** [comment]
I'm seeing something similar with iOS. I suspect that is timezone related as well but I'm a little unsure what the best course is. I see you pass the date as millisecondsSinceEpoch through to HealthKit and then convert it back again with milliseconds from epoch using the default of Utc false. So to me everything should be "local time" but when I test (US Eastern) get my steps for today its consistently adding a few hundred (from last night). I think this is just probably a documentation issue. Is there a best practice for the start and end dates and how we treat the result?

**Comment by ppakorn** [comment]
@oakmad we're seeing that as well. Could you provide a solution to fix that problem?

**Comment by lovaicv** [comment]
iOS Health app will combine steps count from multiple sources and calculate steps using their own algorithm. 
https://stackoverflow.com/questions/33746497/how-do-you-calculate-steps-per-day-from-the-ios-health-app-export-xml

the simple way to get the exact same number of steps as in iOS Health app is to use iOS method called HKStatisticsCollectionQuery, sample over here
https://stackoverflow.com/questions/36559581/healthkit-swift-getting-todays-steps

you then can build a iOS plugin for flutter based on it.

**Comment by chrisvidal** [comment]
any solutions for this duplicate data coming from multiple data sources? having the same issue here

**Comment by Ol-Wood** [comment]
@oakmad 

Do we have a solution for handling data from multiple sources, how do we appropriately aggregate them?

**Comment by chrisvidal** [comment]
@Ol-Wood 
i did it using the device ID available in the HealthDate if my memory is correct
