### ISSUE TITLE
how to clear steps after complete a certain level

### ISSUE THREAD

**Issue by shivamviswas** [cph-cachet/flutter-plugins#253]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. iPhone 6s]
 - OS: [e.g. iOS 13.1]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### To Reproduce
Steps to reproduce the behavior.

### Expected behavior
What did you expect to happen?

### Actual behavior
What did happen? Include stack traces and exception print-outs.

### Flutter doctor 
Please run `flutter doctor` and add the output here.

### Additional information
Add any other info about the problem here.

**Comment by thomasnilsson** [comment]
You should do this yourself. The plugin does not keep track of the number of steps internally.
