### ISSUE TITLE
[activity_recognition_flutter 2.0.2] build failed android

### ISSUE THREAD

**Issue by georgeraveen** [cph-cachet/flutter-plugins#254]
**activity_recognition_flutter 2.0.2**

### Device / Emulator and OS

 - Device: [Galaxy J7 Nxt]
 - OS: [Android 9]

### Describe the bug
I updated the activity recognition package to 2.0.2.
when I run the application "FAILURE: Build failed with an exception."

### To Reproduce
Steps to reproduce the behavior.

### Expected behavior
Build app

### Actual behavior

`Launching lib\main.dart on SM J701F in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
 A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    Android resource linking failed
     ..............\build\flutter_foreground_service\intermediates\library_manifest\debug\AndroidManifest.xml:11:9-14:121: AAPT: error: attribute android:foregroundServiceType not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin activity_recognition_flutter...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'activity_recognition_flutter'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin activity_recognition_flutter could not be built due to the issue above.`

### Flutter doctor 
`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
`

### Additional information
Add any other info about the problem here.

**Comment by thomasnilsson** [comment]
You likely need to set the SDK version correctly. If I were you I would look at the example app that ships with the plugin, this app builds with no issues and works for Android 10/SDK 29
