### ISSUE TITLE
[Specify the plugin name and version here]

### ISSUE THREAD

**Issue by deveshgarg-max** [cph-cachet/flutter-plugins#255]
Device Information: 
Samsung A21S 
Android 10 
Ram 4 GB

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(1, StepDetection not available, StepDetection is not available on this device, null)
E/flutter (15319):
I/flutter (15319): ERROR: StepCount not available

I am using an example provided in the repository. And Other apps "Samsung health" is working properly

**Comment by thomasnilsson** [comment]
I have also had the same issue with certain samsung galaxy models. Unfortunately there is not much to do, the API is not exposed by samsung.

**Comment by deveshgarg-max** [comment]
There is a lack of response here it's really unfair if you are creating something public you need to be active.
Anybody else found this solution?

**Comment by thomasnilsson** [comment]
Go somewhere else with that attitude, good bye.
