### ISSUE TITLE
[health] plugin requires old device_info ^0.4.2+8 when device_info 1.0.0 installed

### ISSUE THREAD

**Issue by denkoul** [cph-cachet/flutter-plugins#264]
**PUB GET error message:** 
`Because health 3.0.1+1 depends on device_info ^0.4.2+8 and no versions of health match >3.0.1+1 <4.0.0, health ^3.0.1+1 requires device_info ^0.4.2+8.
So, because app depends on both device_info ^1.0.0 and health ^3.0.1+1, version solving failed.
pub get failed (1; So, because app depends on both device_info ^1.0.0 and health ^3.0.1+1, version solving failed.)`

I can not run pub get due to the conflict above. I need the device_info 1.0.0 and can not downgrade to 0.4. Thanks in advance.

**Comment by thomasnilsson** [comment]
Fixed in version 3.0.2
