### ISSUE TITLE
[audio_streamer]: handleInterruptions crashes app on iOS

### ISSUE THREAD

**Issue by halldorlogi** [cph-cachet/flutter-plugins#266]
**Plugin name & version**
noise_meter 2.0.0 which depends on audio_streamer 1.2.0

**Describe the bug**
Audio interruptions crash app.

**To Reproduce**

1. Play audio with [https://pub.dev/packages/just_audio](url) using [https://pub.dev/packages/audio_session](url) for interruption handling.
2. Put app into background and start playing audio with another app, for example Spotify, to trigger an interruption.

**Expected behavior**
Audio interruptions should be handled, or at least the interruption code should not crash app.

**Actual behavior**
App crashes on interruption.

![image](https://user-images.githubusercontent.com/31821199/105050389-a3215700-5a65-11eb-836a-ffc3fbdefd5e.png)
![image](https://user-images.githubusercontent.com/31821199/105050409-a87ea180-5a65-11eb-9c6e-98b943309f40.png)

**Note:**
Commenting out the function body solves the issue.
  @objc func handleInterruption(notification: Notification) {
      // To be implemented.
    //eventSink!(FlutterError(code: "100", message: "Recording was interrupted", details: "Another process interrupted recording."))
  }

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale en-IS)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

**Smartphone**
- Device: iPhone Xs
- OS: iOS 14.3

**Comment by Felixduelmer** [comment]
any updates on this issue?

**Comment by devibrahimkarahan** [comment]
Any update ???
