### ISSUE TITLE
Pedometer in background

### ISSUE THREAD

**Issue by mychaelgo** [cph-cachet/flutter-plugins#27]
how to get pedometer still count the stepsData when app is on background?

**Comment by thomasnilsson** [comment]
It should still count while the app is in the background - if you could provide more details (consult the issue template) we can look into it.

**Comment by mychaelgo** [comment]
**Plugin name & version**
```
pedometer: ^0.0.5
```

**Describe the bug**
```
Pedometer not counting steps after app is closed
```

**To Reproduce**
1. Code
```dart
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:pedometer/pedometer.dart';
void main() => runApp(new MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _stepCountValue = 'Unknown';
  StreamSubscription<int> _subscription;

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    setUpPedometer();
    if (!mounted) return;
  }

  void setUpPedometer() {
    Pedometer pedometer = new Pedometer();
    _subscription = pedometer.stepCountStream.listen(_onData,
        onError: _onError, onDone: _onDone, cancelOnError: true);
  }

  void _onData(int stepCountValue) async {
    setState(() => _stepCountValue = "$stepCountValue");
  }

  void _onDone() => print("Finished pedometer tracking");

  void _onError(error) => print("Flutter Pedometer Error: $error");

  void _onCancel() => _subscription.cancel();

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: new Center(
          child: new Text('Steps taken: $_stepCountValue\n'),
        ),
      ),
    );
  }
}
```

2. Walking
3. Close app with home button (app in backgroun now)
4. Walking
5. Open App, step count not counting

**Expected behavior**
```
_onData tiggered if we are walking & app is in background
```

**Actual behavior**
```
_onData not triggered when app in background
```

**Screenshots**
-

**Flutter doctor**
```
mychaelgo@Mychaels-MacBook-Pro:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.5 18F132, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
```

**Smartphone**
Please complete the following information for each phone and/or emulator you're experiencing this bug on:

 - Device: iPhoneX
 - OS: iOS 13

**Additional context**
-

**Comment by VolodymyrBiryuk** [comment]
Will this still work on Android Pie? There are some changes coming (see https://developer.android.com/about/versions/pie/android-9.0-changes-all).

**Comment by omarsherifs** [comment]
this plugin can count when the app is launched on in ram ... so when you remove it from ram it will stop counting

**Comment by thedrhax14** [comment]
@omarsherifs is right. Only when it is left on the background, it actually counts steps, but once removed, i.e. closed completely, it resets. So, it never remembers it on iOS. However, on Android it remembers properly. The potential fix is to enable background processing in the app's capabilities and maybe implement such logic in the dart code, which remembers steps on iOS.

I plan to try this option and share results later.

**Comment by omarsherifs** [comment]
@thedrhax14 waiting for your results

**Comment by thomasnilsson** [comment]
I will take a proper look at this old issue in the coming days.

**Comment by thomasnilsson** [comment]
[Pedometer 1.1.0 is now live](https://pub.dev/packages/pedometer) and we have addressed the issue. Thanks for letting us know.

**Comment by FirdousNath** [comment]
Does it even work when app removed from RAM or recents apps ?

**Comment by darshansatra1** [comment]
@FirdousNath  I don't think so, I'm using the **Background_Fetch** plugin to get steps in the background but the stream is not emitting any data. If there is an alternative approach, please let us know.

**Comment by FirdousNath** [comment]
> **Background_Fetch**

can you share your config, for me background fetch isn't working automatically every 15 mins. When I manually hit add command as per their redeem file, it run the headless block.

**Comment by darshansatra1** [comment]
You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.

**Comment by FirdousNath** [comment]
can you please help me, how did you achieve it ? I am stuck for so long. As you suggested foreground service will only work on android, what about iOS ?

**Comment by RangasamyEswaran** [comment]
curently the pedometer is working but it is not showing the step count value. If there is an error means it will show the Pedometer Error. But it is available means it will not show the step value. In that time it will initial value unkown. How can i solve this kaind error. any one curently developed the step count means reply this commend

**Comment by thekavak** [comment]
Hi, @FirdousNath @darshansatra1 
Is there any way to continue step counting even if app is killed by user.
I'm using a xiaomi device and the example on github doesn't work for it.
How logical it is to follow a Work manager or similar path, I would be very happy if you could show me a way.

**Comment by Bagheer4** [comment]
> You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.

Hi @darshansatra1 ,
could you please state an example of the foreground service with the pedometer?

**Comment by junaidlodhi22** [comment]
> You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.

Hi, Can you tell us which package are you using for the foreground service? We are not finding anything that will keep the app in foreground when app is push in recent apps.

**Comment by prossion** [comment]
Hi. Has anyone used flutter_foreground_task to read steps from a pedometer? Because I have a problem that when the program enters the foreground, the steps stop tracking. Thanks

**Comment by Cubel89** [comment]
I am getting it working fine when the app is open. The problem is that I am trying to configure the "background_fetch" package to run the task every 15 minutes on both Android and iOS, but it seems that "_stepCountStream.listen((StepCount event) {...}" never fires, for therefore I can't read the steps in the background.

**Comment by kaneki666** [comment]
> You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.

Hey i am stuck here..how can i keep running the pedometer when app is terminated.can you share your solve

**Comment by Cubel89** [comment]
> > You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.
> 
> Hey i am stuck here..how can i keep running the pedometer when app is terminated.can you share your solve

As far as I know, it will have to do it in Kotlin. The movito is because Pedometer's package uses the channels for communication with the sensor, and for what I have been seeing, (someone corrects me if I'm wrong) it seems that the channels are not available for background tasks

**Comment by prossion** [comment]
> > You won't be able to get the pedometer data in the background service cause the flutter engine is killed when the app is killed. So I used foreground service and I everything is working fine.
> 
> Hey i am stuck here..how can i keep running the pedometer when app is terminated.can you share your solve

Try to use flutter_foreground_task

**Comment by maeddin** [comment]
Would https://github.com/cph-cachet/flutter-plugins/issues/993 solve the problem with measuring steps on Android while the app ist closed?
