### ISSUE TITLE
[weather 1.2.4]

### ISSUE THREAD

**Issue by shobhitpuri** [cph-cachet/flutter-plugins#280]
**Remember to specify the plugin name in the title!**

### Description
Methods like `currentWeatherByCityName`, don't throw the errors back to the calling code. There is no way to know the reason for the error or the error message. Please instead of calling `print` on the catching the exception, `throw` it back to calling code to handle. Or provide a choice. Sample code with issue:
```
  /// Fetch current weather based on city name
  /// Result is JSON.
  /// For API documentation, see: https://openweathermap.org/current
  Future<Weather> currentWeatherByCityName(String cityName) async {
    try {
      Map<String, dynamic> currentWeather =
          await _sendRequest(CURRENT_WEATHER, cityName: cityName);
      return Weather(currentWeather);
    } catch (exception) {
      print(exception);
    }
    return null;
  }
``` 

### Additional information
`SocketException`, `HttpException` etc can be handled separately by an application. This gives a developer more information to make the right error messages.

**Comment by thomasnilsson** [comment]
See version 1.4.0

**Comment by shobhitpuri** [comment]
Thanks @thomasnilsson ! Thank you. Improvement issue can be closed then
