### ISSUE TITLE
[pedometer] Cannot check if step count stream is available

### ISSUE THREAD

**Issue by thevirtuoso1973** [cph-cachet/flutter-plugins#286]
### Device / Emulator and OS
Samsung A40 or any emulator.

### Describe the bug
Devs who use this library cannot check if step count stream is available since errors are caught in your code.
You could instead allow us to catch errors ourselves.

### To Reproduce
Run your example app on any device without a step counter. It will *not* inform you that it is unavailable.

**Comment by thomasnilsson** [comment]
Fixed in version 2.1.0
