### ISSUE TITLE
Nullsafety for all plugins

### ISSUE THREAD

**Issue by mjstel** [cph-cachet/flutter-plugins#295]
### Description
Since null-safety is now API stable, i just want to ask if you already have plans or a road map to publish null-safety versions of your awesome plugins.

**Comment by thomasnilsson** [comment]
We mostly handle the severe bugs due to resource constraints but feel free to contribute and we will review your PRs

**Comment by mjstel** [comment]
Im gonna close this issue, since there are already merged pr's for some plugins.
