### ISSUE TITLE
Health 3.0.3 - Migration to null-safety

### ISSUE THREAD

**Issue by deimantasa** [cph-cachet/flutter-plugins#311]
Hello devs,

Thank you for this great plugin! I was wondering, is there any plan for migrating this plugin to `null-safety`?
If no - I'd be happy to contribute. As one of our projects screamingly needs `null-safety`.

Cheers

**Comment by vmalyi** [comment]
https://github.com/cph-cachet/flutter-plugins/issues/295

**Comment by tiloc** [comment]
see my PR #297

**Comment by deimantasa** [comment]
That's fantastic! Thank you @tiloc .

It's been nearly a month - is there any estimations when this PR can get officially merged reviewed and merged into the package?

**Comment by allanwolski** [comment]
+1

**Comment by MadsVSChristensen** [comment]
As of 3.0.5 Health supports null safety. Apologies for the delay - we maintain a large number of packages ATM.
