### ISSUE TITLE
carp_background_location on app is killed

### ISSUE THREAD

**Issue by web75018** [cph-cachet/flutter-plugins#318]
Plugin: carp_background_location

Thank you so much for this great job. Awesome!

### Description
The background location keeps working even if the app is killed. for both Android and iOS. 
That is awesome. 

_**Flutter logs =>**_ 
D/plugin  (28459): sendLocationEvent {callback=5839465806, location={altitude=0.0, heading=235.86823, latitude=11.001122334455, accuracy=3.0847857, speed_accuracy=0.0, time=1.616879123709E12, is_mocked=true, speed=31.944445, longitude=-5.1234567890}}

**_Question_**
How to use this as i need to keep getting locations.

**Comment by bardram** [comment]
carp_background_location 4.0.0 has been published and I'm closing this old issue.

**Comment by ritesh305** [comment]
@web75018  did you find how to use that data?
