### ISSUE TITLE
[Pedometer 2.0.2] For Android, this plugin doesn't work, if compileSdkVersion > 28

### ISSUE THREAD

**Issue by hangzhi22** [cph-cachet/flutter-plugins#319]
no callback of stepCount and stepStatus if compileSdkVersion > 28. 

when I change the version to 28, it works again.

**Comment by jtmuller5** [comment]
Can confirm, the package wasn't working for me when compiledSdkVersion = 30. I changed back to 28 and the call backs are being triggered again.

**Comment by ZuSe** [comment]
Are you talking about this exception?

> E/MethodChannel#flutter_health( 2535): Failed to handle method call
> E/MethodChannel#flutter_health( 2535): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.HashMap<*, *> /* = java.util.HashMap<*, *> */
> E/MethodChannel#flutter_health( 2535): 	at cachet.plugins.health.HealthPlugin.callToHealthTypes(HealthPlugin.kt:204)
> E/MethodChannel#flutter_health( 2535): 	at cachet.plugins.health.HealthPlugin.requestAuthorization(HealthPlugin.kt:215)
> E/MethodChannel#flutter_health( 2535): 	at cachet.plugins.health.HealthPlugin.onMethodCall(HealthPlugin.kt:237)
> E/MethodChannel#flutter_health( 2535): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/MethodChannel#flutter_health( 2535): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/MethodChannel#flutter_health( 2535): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> E/MethodChannel#flutter_health( 2535): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#flutter_health( 2535): 	at android.os.MessageQueue.next(MessageQueue.java:335)
> E/MethodChannel#flutter_health( 2535): 	at android.os.Looper.loop(Looper.java:206)
> E/MethodChannel#flutter_health( 2535): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
> E/MethodChannel#flutter_health( 2535): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#flutter_health( 2535): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
> E/MethodChannel#flutter_health( 2535): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

**Comment by nikosportolos** [comment]
Any updates on this? I also don't get any events from streams with targetSdkVersion > 28.
This is a blocker issue for publishing apps in PlayStore, since the minimum target SDK version is currently 29 and starting from August it will change to 30. https://developer.android.com/distribute/best-practices/develop/target-sdk.html

**Comment by MarcelHH** [comment]
can you show how where exactly do you have to install the code?

**Comment by nikosportolos** [comment]
You can take a look on the following code snippet.
I modified the method initPlatformState() of the example project to request for the necessary permissions.

**main.dart**

```
  Future<Permission> getMotionPermission() async {
    if (Platform.isAndroid && await getAndroidSdk() >= 29)
      return Permission.activityRecognition;
    else
      return Permission.sensors;
  }

  Future<int> getAndroidSdk() async {
    if (Platform.isAndroid) {
      var androidInfo = await DeviceInfoPlugin().androidInfo;
      var sdkInt = androidInfo.version.sdkInt;
      return sdkInt;
    }
    return 0;
  }

  Future<void> initPlatformState() async {
    Permission motionPermission = await getMotionPermission();
    if (!await motionPermission.isGranted) {
      var newStatus = await motionPermission.request();
      if (!newStatus.isGranted) return Future.error('Permission not granted');
    }

    _pedestrianStatusStream = Pedometer.pedestrianStatusStream;
    _pedestrianStatusStream.listen(onPedestrianStatusChanged).onError(onPedestrianStatusError);

    _stepCountStream = Pedometer.stepCountStream;
    _stepCountStream.listen(onStepCount).onError(onStepCountError);

    if (!mounted) return;
  }
```

You can also check the full source code on my forked repo https://github.com/nikosportolos/flutter-plugins/tree/master/packages/pedometer

**Comment by MarcelHH** [comment]
I understand correctly that is only possible with the package permission_handler?

**Comment by nikosportolos** [comment]
> THX its work now 😊

Great! Glad I could help :)

**Comment by seungduk-yanolja** [comment]
It looks like this is a must-do. Why isn't it included in the package already?

**Comment by saurabhkumar8112** [comment]
I don't see this issue happening now. Can others confirm? If yes, I would request authors to close this issue
