### ISSUE TITLE
notifications bug

### ISSUE THREAD

**Issue by AnavrinApps** [cph-cachet/flutter-plugins#324]
/Users/abc/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/notifications-1.0.2+1/android/src/main/kotlin/dk/cachet/notifications/NotificationsPlugin.kt: (65, 76): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ComponentName?

I get this error during runtime using Flutter 2.0.4

**Comment by thomasnilsson** [comment]
Should be fixed in v 1.1.0
