### ISSUE TITLE
carp_background_location: ^1.0.2+1

### ISSUE THREAD

**Issue by nvngkr** [cph-cachet/flutter-plugins#331]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Anroid Device OS version 8.0.0

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
when we set locationManger.interval = 10 ( in seconds), the background fetch should happen every 10 seconds, but in anroid phone it is taking 20 seconds but in emulator it is working fine (same os)

**Comment by bardram** [comment]
carp_background_location 4.0.0 has been published and I'm closing this old issue.
