### ISSUE TITLE
[activity_recognition_flutter 4.0.1] extra } in ActivityRecognitionFlutterPlugin.java

### ISSUE THREAD

**Issue by cs-vladpaianu** [cph-cachet/flutter-plugins#349]
After upgrading from version 4.0.0 to 4.0.1, the application won't build on Android emulators or devices. 

The line that causes it is in ActivityRecognitionFlutterPlugin.java (line 169). I believe that due to the recent merge, an extra "}" remained in that file.

**Comment by bardram** [comment]
Closed with PR #351
