### ISSUE TITLE
carp_background_location: what does it offer beyond background_locater, on which it is based? (docs?)

### ISSUE THREAD

**Issue by willhaslett** [cph-cachet/flutter-plugins#360]
### Description
I'm sourcing a plugin for background location sensing. `background_location` works for 2 hours after a reboot but then fails for me on Android 11. I'm looking at `carp_background_location` vs `background_locater`. The former clearly relies on the latter under the hood, but adds more stuff (complexity?). Should the README include a rationale for this plugin? What is that rationale? Not an idle question, as I, and I'm sure others, are sourcing plugins for background location for production apps.

**Comment by bardram** [comment]
Hi @willhaslett - the main reason to create the CARP wrapper plugin was to make a more concise and simple API using a Dart stream which can be used like this:

```
StreamSubscription locationSubscription = LocationManager().locationStream.listen(onData);
```

We found the API rather cumbersome to work with for our purposes.

Good idea to update the README file with this info - will do it later.
