### ISSUE TITLE
[3.0.x] health  - Log out or disconnect account

### ISSUE THREAD

**Issue by edumolins** [cph-cachet/flutter-plugins#363]
Health Package
----------------
I have not found a way to log out a user's account once it has been authorized. 
It would be nice to have a logout method to be able to choose another user account to retrieving data.

**Comment by HangingClowns** [comment]
We actually already implemented this and can probably send it back.

**Comment by bardram** [comment]
Please make a PR if so?

**Comment by mikidimitrovski** [comment]
Hi, we really need the log out option, it's a must for data protection regulation...

**Comment by zlated** [comment]
Hi, any news on this topic?!

**Comment by chukovskid** [comment]
Any updates on the log-out option for Android and IOS?

**Comment by HangingClowns** [comment]
My PR has this function.

**Comment by igorstama** [comment]
Hello @HangingClowns, nice work with #436!

Would it be possible for you to go over the merge conflicts, in the coming weeks? 

Let me know how can I help. Thanx!

**Comment by dipinsankar1** [comment]
Any updates on logout or disconnect from googlefit ??

**Comment by sunilkumawatandroid** [comment]
Any updates on logout or disconnect from googlefit or health app ??

**Comment by chukovskid** [comment]
We solved it with google_sign_in plugin for flutter. This plugin allows to SignIn Silently even when the app is in background. 
So we used the REST flow to get the steps from googleFit.

This is the scopes we used:
  static String googleFirUrl =
      "https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate";

  static GoogleSignIn _googleSignIn = GoogleSignIn(
    scopes: <String>[
      'email',
      'https://www.googleapis.com/auth/fitness.activity.read',
    ],
  );

**Comment by MadsVSChristensen** [comment]
As of version 4.6.0 `revokePermissions` now disables Google Fit.
