### ISSUE TITLE
notifications How to get the content of the notice

### ISSUE THREAD

**Issue by a97077088** [cph-cachet/flutter-plugins#37]
notifications How to get the content of the notice

**Comment by sicay1** [comment]
Great plugin, seems to work well - I just wanted to know if it's possible to get steps for a given date, like yesterdays date.

**Comment by KingDarBoja** [comment]
@sicay1 @a97077088 Provide the package as github url.

Example code on my [Notification Listener](https://github.com/KingDarBoja/Notification-Listener/blob/master/pubspec.yaml) sample repo.

**Comment by ta1bbty** [comment]
Hi @KingDarBoja 
Your repo doesn't seem to work. I am running this on android 10 ( physical device ), trying to read whatsapp notifications.

Let me know, what I need to do to run this.

Thanks.

**Comment by KingDarBoja** [comment]
Hi @ta1bbty 

I will take a look and update dependencies if needed, been a while since last time I tested it.

**Comment by thomasnilsson** [comment]
Have a look at version 1.0.0 :)
