### ISSUE TITLE
[health 3.0.4]

### ISSUE THREAD

**Issue by hasan-abul** [cph-cachet/flutter-plugins#375]
**Remember to specify the plugin name in the title!**

### Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [Nexus 4 API 29 (andriod-x86 emulator)]
 - OS: [Andriod Version 10]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
After debugging v3.0.4, It's working for me with no errors the issue is I am not getting any data

List<HealthDataPoint> healthData = await health.getHealthDataFromTypes(startDate, endDate, types); list is always returning empty and step count is 0.

### To Reproduce
Use the same code as in Health example

### Expected behavior
To show user step count

### Actual behavior
Step count always 0

### Screenshots
![image](https://user-images.githubusercontent.com/33178971/124383148-747ffb80-dce8-11eb-833e-31c303467104.png)

### Flutter doctor 
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.57.1)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

### Additional information
Add any other info about the problem here.

**Comment by hasan-abul** [comment]
Please any help on the above issue.. please

**Comment by bajpaijalaj** [comment]
> Please any help on the above issue.. please

Request for this access, you should see data :
if(Platform.isAndroid) {
        var androidInfo = await DeviceInfoPlugin().androidInfo;
        int sdk = androidInfo.version.sdkInt;

        if (sdk > 28) {
          bool activityRecognitionStatus =
          await Permission.activityRecognition.status.isGranted;

          if (!activityRecognitionStatus) {
            if (await Permission.activityRecognition.request().isGranted) {}
          }
        }
      }

**Comment by bajpaijalaj** [comment]
> Please any help on the above issue.. please

Request for this access, you should see data :
```
if(Platform.isAndroid) {
var androidInfo = await DeviceInfoPlugin().androidInfo;
int sdk = androidInfo.version.sdkInt;

    if (sdk > 28) {
      bool activityRecognitionStatus =
      await Permission.activityRecognition.status.isGranted;

      if (!activityRecognitionStatus) {
        if (await Permission.activityRecognition.request().isGranted) {}
      }
    }
  }
```
