### ISSUE TITLE
[health 3.0.6] Android, Authorization not granted Error

### ISSUE THREAD

**Issue by EunyoungY** [cph-cachet/flutter-plugins#387]
[health 3.0.6] 
Hello, I'm running flutter health plugin
It gives an error "**Authorization not granted**".

 https://console.developers.google.com/flows/enableapi?apiid=fitness 
I followed this instruction for android, but It doesn't work.

**Comment by Crewlan** [comment]
Hi @EunyoungY ,  i'm opened this PR #394  to solution this problem.

**Comment by EunyoungY** [comment]
Thank you. The solution works for "Authorization not granted" error.
**However, it says "no data".**

Caught exception in getHealthDataFromTypes: An exception happened when requesting HealthDataType.DISTANCE_WALKING_RUNNING. Cause: Not available on platform PlatformType.ANDROID
I/flutter (21535): Steps: 0

**Comment by bardram** [comment]
Fixed with PR #394 and released as version 3.1.1
