### ISSUE TITLE
Flutter health

### ISSUE THREAD

**Issue by aashishvyas** [cph-cachet/flutter-plugins#391]
Step count value not correct in ios

**Comment by Crewlan** [comment]
Hi @aashishvyas, i'm opened this PR #394  to solution this problem.

**Comment by sanjayApanchal** [comment]
I tried to fetch fitness data using this library but _List<HealthDataPoint>_ returns nothing while I do have logged in with same account in Google fit and my app, Can you help me with **Sample App code**? and I also need to know that where to use **OAuth Client ID in my project**? please help..

**Comment by bardram** [comment]
The plugin has been updated several times now, and with an updated example. Please check if this solves this issue.
