### ISSUE TITLE
requestAuthorization returns true even though read data is disabled [3.1.0]

### ISSUE THREAD

**Issue by leanhro2812** [cph-cachet/flutter-plugins#397]
Even though the permission to read data has been denied or disabled, I still get the permission True

![Screen Shot 2021-08-06 at 22 45 11](https://user-images.githubusercontent.com/45846101/128537303-c46f6928-e5c5-484c-9bcc-49baafec582c.png)

**Comment by sanjayApanchal** [comment]
I tried to fetch fitness data using this library but _List<HealthDataPoint>_ returns nothing while I do have logged in with same account in Google fit and my app, Can you help me with **Sample App code**? and I also need to know that where to use **OAuth Client ID in my project**? please help..

**Comment by korolkir** [comment]
This is expected behaviour of iOS HealthKit (pls read the iOS docs) because of safety reasons
