### ISSUE TITLE
Health 3.1.1+1

### ISSUE THREAD

**Issue by sanjayApanchal** [cph-cachet/flutter-plugins#400]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: OnePlus nord 2
 - OS: Android 11

### Describe the bug
I tried to fetch fitness data using this library but _List<HealthDataPoint>_ returns nothing while I do have logged in with same account in Google fit and my app, Can you help me with **Sample App code**? and I also need to know that where to use **OAuth Client ID in my project**? please help..

### Flutter doctor 

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/sanjay_lohar/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /home/sanjay_lohar/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/sanjay_lohar/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (3 available)
    • AEFA45PVORW4S4QW (mobile) • AEFA45PVORW4S4QW • android-arm    • Android null (API null)
    • sdk gphone x86 (mobile)   • emulator-5554    • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by yukitaka13-1110** [comment]
iOS always return true.

`requestAuthorization`
