### ISSUE TITLE
[carp_background_location 2.0.0] LocationManager().notificationMsg only changes the folded message

### ISSUE THREAD

**Issue by koenniem** [cph-cachet/flutter-plugins#411]
### Device / Emulator and OS
Android only

### Describe the bug
Per [this SO question](https://stackoverflow.com/questions/68069748/change-the-text-background-location-is-on-on-the-keep-app-up-tp-date-in-carp), one can change the notification title and message of `carp_background_location` like this:
```java
LocationManager().notificationTitle = 'CARP Location Example';
LocationManager().notificationMsg = 'CARP is tracking your location';
```
However, as the SO question shows, this message is only change when the notification is folded, not when expanded. This behaviour is unexpected.

### To Reproduce
Run the example app and `LocationManager().notificationMsg = 'CARP is tracking your location';`. This will not be changed in the expanded message.

### Expected behavior
Either both folded and expanded message should be updated by `notificationMsg` or there needs to be a separate setter for the expanded message, like in PR #410.

### Actual behavior
Only the folded message was changed.

### Screenshots
See the SO link above.

**Comment by bardram** [comment]
carp_background_location 4.0.0 has been published and I'm closing this old issue.
