### ISSUE TITLE
Health: 3.1.1+1 Add revoke function

### ISSUE THREAD

**Issue by jzaccone** [cph-cachet/flutter-plugins#412]
### Description
Add revoke function to allow users to revoke permissions directly in the app

**Comment by thomasmol** [comment]
I'd like to see this functionality as well. My app can connect with several other health apps (like Fitbit and Strava), and uses this package for HealthKit, which works great. However, I'd like the user to be able to revoke access to their health data (both for google fit or apple health) as well.

**Comment by MadsVSChristensen** [comment]
This has been added in release 4.6.0
