### ISSUE TITLE
[weather]: Include precipitation information in Weather response

### ISSUE THREAD

**Issue by btrautmann** [cph-cachet/flutter-plugins#414]
**Remember to specify the plugin name in the title!**

### Description
Would love to see the addition of the `pop` (probability of precipitation) added to the deserialization of the [open weather API response](https://openweathermap.org/forecast5).

Opening an issue here first before opening a PR. Happy to help if that's something you are interested in!

**Comment by jigzstar** [comment]
I would love this as well. Actually need this for a project.
