### ISSUE TITLE
[NoiseMeter 3.0.1]

### ISSUE THREAD

**Issue by petrovicmobi** [cph-cachet/flutter-plugins#419]
**NoiseMeter**

### Description
I have problem with noise meter... on line
  
    previousMillis = DateTime.now().millisecondsSinceEpoch;
    try {
      _noiseSubscription = _noiseMeter.noiseStream.listen(onData);
    } catch (e) {
      print(e);
    }

I get error:

Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments.: Closure: (PlatformException) => void from Function 'onError':.

### Additional information

Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments.: Closure: (PlatformException) => void from Function 'onError':.
Any idea how to fix this?

**Comment by bardram** [comment]
Fixed with noise_meter version 4.0.1
