### ISSUE TITLE
Get the frequency, Hz, with noise_meter

### ISSUE THREAD

**Issue by DanielCardona** [cph-cachet/flutter-plugins#42]
**Plugin name & version**
Noise_meter.

**Enhancement request**
Is it possible to get the Hz, like we get the Db?
Will you support this option?

**Expected behavior**
Would like to get the frequency.

**Actual behavior**
Actually is only possible to get the decibels.

Thank you for your work.

**Comment by KingDarBoja** [comment]
From the source code at [Android Library](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/noise_meter/android/src/main/java/cachet/sensors/noisemeter/NoiseMeterPlugin.java), it looks like it has a fixed value of **44100**.

You can check by looking at the `private static int SAMPLE_RATE = 44100;` line.

**Comment by DanielCardona** [comment]
Thanks @KingDarBoja!! I'll chek it, anyway andoid native is not one of my strenghts, hope somebody port the get frecuency to both Android and IOS.

**Comment by thomasnilsson** [comment]
Thanks for the issue, this is now available in Noise Meter 1.1.5 https://pub.dev/packages/noise_meter
