### ISSUE TITLE
[health: ^3.2.0]  HealthFactory.revokePermissions() gives  MissingPluginException 

### ISSUE THREAD

**Issue by yadav-aniket** [cph-cachet/flutter-plugins#431]
### Device / Emulator and OS
 - Device:  Nokia 3.1
 - OS: Android 10

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method revokePermissions on channel flutter_health)

### Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1237], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (4 available)

**Comment by edvardmk** [comment]
Same thing for me on:

- Device: Samsung Galaxy S7
- OS: Android 8
- health version: ^4.1.1

### Flutter Doctor
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.4 21F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
