### ISSUE TITLE
[notifications]

### ISSUE THREAD

**Issue by serdariince** [cph-cachet/flutter-plugins#434]
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel notifications:
MissingPluginException(No implementation found for method listen on channel notifications)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:486:9)
<asynchronous suspension>

**Comment by UbaidBodla** [comment]
Are you find solution to this problem??
MissingPluginException(No implementation found for method listen on channel notifications)

please let me know
