### ISSUE TITLE
Incorrect permission handling on IOS [health: 3.3.1]

### ISSUE THREAD

**Issue by vovaklh20012** [cph-cachet/flutter-plugins#456]
### Device / Emulator and OS
 - Device: [Iphone X]
 - OS: [iOS 15.2]

### Describe the bug
The HealthFactory method requestAuthorization returns true if user denied permission to read and write steps
![image](https://user-images.githubusercontent.com/85889928/142395659-e2ba1638-b4c2-46ee-8c75-8d1e7d93de85.png)
![image](https://user-images.githubusercontent.com/85889928/142395718-5b0c3a70-f3c9-4da1-870e-6e6be1be0670.png)

**Comment by MadsVSChristensen** [comment]
Hey @vovaklh20012 

Though this is an inconvenience, it is intended behavior. The result of the `requestAuthorization` is true/false this is simply an indicator of the app showing the permission screen correctly. This is per Apple's design and API.

The reasoning behind this is that users must be protected by privacy, so the app cannot determine the READ status. WRITE status CAN be determined for the individual app, but READ and READ_WRITE should never be disclosed.

HealthKit has some documentation on this here:
https://developer.apple.com/documentation/healthkit/authorizing_access_to_health_data

This is the most relevant part to this question:

> To help protect the user’s privacy, your app doesn’t know whether the user granted or denied permission to read data from HealthKit. If the user denied permission, attempts to query data from HealthKit return only samples that your app successfully saved to the HealthKit store.

Best regards,
Mads
