### ISSUE TITLE
[Health 3.3.0] parameter in method requestAuthorization to specify access permission 

### ISSUE THREAD

**Issue by matsunanaro** [cph-cachet/flutter-plugins#464]
### Description
The requestAuthorization method in HealthFactory should include a parameter to specify what permission is requested, e.g. READ ONLY, WRITE ONLY, READ_WRITE

### Additional information
The current implementation is requesting implicitly  both read and write access. However, an application may require only READ ACCESS in some scenarios. Implicitly requesting for both the permissions is not appropriate.

**Comment by rsbthebest** [comment]
Yup google has raised a OAuth issue for us because we are requesting write access while we don't really need it.

**Comment by bardram** [comment]
This PR has been merged and published as version 3.4.0 of the plugin.
