### ISSUE TITLE
3.3.1

### ISSUE THREAD

**Issue by Pavi08** [cph-cachet/flutter-plugins#467]
how  to  get the specify what permission is requested, e.g. READ ONLY, WRITE ONLY, READ_WRITE

**Comment by matsunanaro** [comment]
Duplicate of #464

**Comment by Pavi08** [comment]
How to het specify read permission only for health kit

**Comment by matsunanaro** [comment]
I'm working on a fix that basically will, by default, request for read access only. Otherwise, the caller must explicitly request "write" or "read_write"

**Comment by bardram** [comment]
This PR has been merged and published as version 3.4.0 of the plugin.
