### ISSUE TITLE
[flutter Health plugin]

### ISSUE THREAD

**Issue by ninoid** [cph-cachet/flutter-plugins#469]
HealthFactory class in health_factory.dart file

removeDuplicates method is very slow. This cause problems with large data. Cause main thread to freezes.

Improvement:

Add break; statement. Please check attached image link:

https://ibb.co/sPxTpL4

**Comment by bardram** [comment]
Fixed (addressed) as part of PR #483 and released as version 3.4.1. 

Thanks to @matsunanaro for the PR.
