### ISSUE TITLE
activity_recognition_flutter android 12 intent flag fix

### ISSUE THREAD

**Issue by altanod0627** [cph-cachet/flutter-plugins#473]
hello  i need your this plugin. But same issue this plugin for android 12. Please fix that intent flag

error: 
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, null)

**Comment by altanod0627** [comment]
ActivityRecognitionFlutterPlugin.java file line 47, 48 replace to

        int flags = PendingIntent.FLAG_UPDATE_CURRENT;
        if (Build.VERSION.SDK_INT >= 23) {
            flags |= PendingIntent.FLAG_IMMUTABLE;
        }
        PendingIntent pendingIntent = PendingIntent.getBroadcast(androidActivity, 0, intent, flags);

**Comment by bardram** [comment]
Is released as v. 4.1.0 - thx for the fix.

(however, it is SDK >= 31 -- not 23)
