### ISSUE TITLE
[CARP_BACKGROUND_LOCATION 3.0.1] How can I get this data

### ISSUE THREAD

**Issue by lasd14** [cph-cachet/flutter-plugins#479]
### Description
 Hi, excellent plugin!
When I open the app and after this I kill it, in the logs of the console I receive sendLocationEvent and a lot parameters I want to know how can I get this data and send it to a database?,
### Additional information
![image](https://user-images.githubusercontent.com/51976094/147256499-cc183613-a623-4125-b982-bb796eefcabb.png)

**Comment by MehrulHassnain** [comment]
please also tell me how to get longitude and latitude ?

**Comment by lasd14** [comment]
Hi, you can get it using this:
`StreamSubscription<LocationDto> locationSubscription = LocationManager().locationStream.listen((LocationDto dto) {
    print(dto.latitude);
    print(dto.longitude);
}
`
