### ISSUE TITLE
Issue with light

### ISSUE THREAD

**Issue by cchazz** [cph-cachet/flutter-plugins#49]
**Plugin name & version**
light ^0.1.1

When I run Gradle on Android Studio I get the following exception:

* What went wrong:
Execution failed for task ':noise_meter:parseDebugLibraryResources'.
> Could not resolve all files for configuration ':noise_meter:androidApis'.
   > Failed to transform file 'android.jar' to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}

Would you have an idea how to fix this. Thanks.

**Comment by thomasnilsson** [comment]
Sorry for the late answer but we have not been able to replicate this issue and have therefore not responded yet. If you still have this problem feel free to create a new one :)

Closing it.
