### ISSUE TITLE
carp_background_location: 3.0.1 - Build fails

### ISSUE THREAD

**Issue by tierecke** [cph-cachet/flutter-plugins#491]
When I add the dependency:
carp_background_location: ^3.0.1 
to my yaml file.

It's enough to make the build fail:
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
e: /Users/me/code/flutter/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/provider/LocationParserUtil.kt: (31, 60): Expecting an argument

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_locator:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

Any idea why?
(I did try the example as is and added to the manifest. But anything seems to fail).

Thanks. Nir.

**Comment by bardram** [comment]
carp_background_location 4.0.0 has been published and I'm closing this old issue. Try the new version, which builds on both Android and iOS.
