### ISSUE TITLE
No dependency link for ios podspec file. version 0.0.6

### ISSUE THREAD

**Issue by coffee4u** [cph-cachet/flutter-plugins#5]
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET cloud_firestore OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/chenbin/development/flutter/.pub-cache/hosted/pub.dartlang.org/weather-0.0.6/ios/Classes/WeatherPlugin.m:2:9: fatal error: 'weather/weather-Swift.h' file not found
    #import <weather/weather-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by thomasnilsson** [comment]
Having trouble replicating the issue on iOS. Could you tell something more about how you used the plugin?

**Comment by mikenussbaumer** [comment]
Any solutions for that problem? Have the same problem 

=== BUILD TARGET flutter_pedometer OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/mikenussbaumer/Developement/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pedometer-0.9.2/ios/Classes/FlutterPedometerPlugin.m:2:9: fatal error: 'flutter_pedometer/flutter_pedometer-Swift.h' file not found
    #import <flutter_pedometer/flutter_pedometer-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/mikenussbaumer/Developement/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pedometer-0.9.2/ios/Classes/FlutterPedometerPlugin.m:2:9: fatal error: 'flutter_pedometer/flutter_pedometer-Swift.h' file not found
    #import <flutter_pedometer/flutter_pedometer-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by thomasnilsson** [comment]
These plugins have both had major overhauls since these comments were made. Feel free to make a new issue if it persists today. :)
