### ISSUE TITLE
[Health] Value *** is not compatible with type HKCategoryTypeIdentifierSleepAnalysis

### ISSUE THREAD

**Issue by deepsan98** [cph-cachet/flutter-plugins#502]
### Device 
 - Device: iPhone 13 mini
 - OS: iOS 15.3

### Description
I am trying to write sleep informations to HealthKit and I already asked for READ_WRITE permissions. 
While I am trying to write health data with `health.writeHealthData()` method, the app crashes and in the console I get this error:
```
*** Terminating app due to uncaught exception '_HKObjectValidationFailureException',
 reason: 'Value 601 is not compatible with type HKCategoryTypeIdentifierSleepAnalysis'
```
Checking the error, it seems that `HKCategoryTypeIdentifierSleepAnalysis` accepts an `HKCategoryValueSleepAnalysis` which is an `int` (see [documentation](https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis)), but `.writeHealthData()` accepts only a `double` as value parameter

### To Reproduce
```
bool success = await health.writeHealthData(
        totalTimeInBed,
        HealthDataType.SLEEP_IN_BED,
        bedtimeStart,
        bedtimeEnd,
);
```
with
```
totalTimeInBed: 601.0
bedtimeStart: DateTime (2022-02-10 23:56:00.000)
bedtimeEnd: DateTime (2022-02-11 09:57:00.000)
```

### Expected behavior
The data should be written to HealthKit (both SLEEP_IN_BED and SLEEP_ASLEEP type).

### Actual behavior
Getting the error mentioned above.

### Flutter doctor 
`flutter doctor` result:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by MadsVSChristensen** [comment]
Hey @deepsan98 

When writing to the SLEEP_*** types, the value is the TYPE of sleep-status (0 = inBed, 1 = asleep, 2 = awake). 

```
await health.writeHealthData(
      status, // 0 = inBed, 1 = asleep, 2 = awake
      HealthDataType.SLEEP_IN_BED,
      bedtimeStart,
      bedtimeEnd,
    );
```
The start and end times are the period of the status e.g. I've slept from 22 - 06 would be:
```
await health.writeHealthData(
      1, // 0 = inBed, 1 = asleep, 2 = awake
      HealthDataType.SLEEP_IN_BED,
      startTime // (2022-02-10 22:00:00.000),
      endTime // (2022-02-11 06:00:00.000),
    );
```

Hope this helps
