### ISSUE TITLE
steps problem when app is published for android

### ISSUE THREAD

**Issue by cndr** [cph-cachet/flutter-plugins#512]
Hello,

+ I do not have any problems with the ios version.
+ I have no problem when I debug in android version or build with apk.

but 
**- no step data when app is published!?**

+ I allowed fitness api.
+ I created a release certificate. (keytool -list -v -keystore key.jks -alias key)
+ I added the SHA-1 certificate as the OAuth client id.

Is there a problem? Or am I doing something wrong somewhere?

Thanks.

**Comment by ivictbor** [comment]
Did you try to run some service in parallel with your app like GoogleFit?
