### ISSUE TITLE
Pedometer _onData not being called on some phones (api level 5)

### ISSUE THREAD

**Issue by ketchup208** [cph-cachet/flutter-plugins#52]
**Pedometer 1.0.0**

**Describe the bug**
_onData function not being called on old android phones 
also onError is not called 
phone information: 
```
{
    "brand": "samsung",
    "device": "coreprimeve3g",
    "display": "LMY48B.G361HXXS0APE1",
    "hardware": "sc8830",
    "manufacturer": "samsung",
    "model": "SM-G361H",
    "version": {
        "codename": "REL",
        "incremental": "G361HXXS0APE1",
        "release": "5.1.1",
        "sdkInt": "22",
    }
}
```

**code sample**
```
  void initState() {
    super.initState();
    setUpPedometer();
}

  Future<void> setUpPedometer() async {
    startListening();
  }
  void startListening() {
    print('i am the pedometer');
    Pedometer pedometer = new Pedometer();
    pedometer.pedometerStream.listen(_onData,
        onError: _onError,
        onDone: _onDone,
        cancelOnError: true);
  }

  void _onData(int stepCountValue) async {
    print(stepCountValue);
  }

  void _onError(error) async {
    print(error);
  }

```

**Expected behavior**
stepCountValue should be printed 

**Actual behavior**
stepCountValue  is not being printed 
but this is getting executed ` print('i am the pedometer');`

**Flutter doctor**
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version
    10.0.18362.592], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
```

**Smartphone(s) / Emulator**
SM-G361H
Android
Core prime

### Update

i just installed the pedometer example app on the device and it did not work with no errors in console 
i checked if the phone have akcelerometr and it does... 

also i ran the project on android studio and checked the logcat and this error appeared
`01-18 14:44:11.937 17649-17649/com.example.pedometer_test E/SensorManager: sensor or listener is null`
i have no idea if this helps

**Comment by keitoro** [comment]
I have the same issue, however, I downloaded a pedometer app and it did work. So something else must be going on.

**Comment by thomasnilsson** [comment]
Thanks for making an issue, but if it is exclusively a problem on old phones (Android 5 is from 2014) then we will not fix it.
