### ISSUE TITLE
Pedometer still shows count when the app is reinstalled

### ISSUE THREAD

**Issue by dark-chocolate** [cph-cachet/flutter-plugins#53]
**Plugin name & version**
`pedometer: ^1.0.0`

**Describe the bug**
When you uninstall the app and install it again, the `onData` method still returns you the same number of steps it had when the app was installed. 

**To Reproduce**
Run the sample code, walk few steps, uninstall the app and install it again, you see those number of steps. 

**Expected behavior**
When app is installed again (after uninstalling), the `onData` should start with `0`

**Actual behavior**
When app is installed again (after uninstalling), the `onData` should starts with last value

**Flutter doctor**
```
[✓] Flutter (Channel dev, v1.14.1, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
```

**Smartphone(s) / Emulator**
Samsung Galaxy S8+ running Android 9.0

**Comment by adham-ashraf77** [comment]
get answer for your issue please share it if you get it

**Comment by Fr099y** [comment]
V1.2.0 Same issue on Google Pixel 3

**Comment by thomasnilsson** [comment]
Our plugins aim to mimic the original APIs as much as possible.

From the description of the plugin
> The step count returned is the number of steps since the phone was last booted.

I.e. if you want a different start time for counting steps, such as the first time opening the app, or when a new day starts at 00:00, you will have to save this in a file yourself.
