### ISSUE TITLE
[Health] removeDuplicates is unnecessarily very slow

### ISSUE THREAD

**Issue by noinskit** [cph-cachet/flutter-plugins#532]
removeDuplicates, which is used for every query, is O(n^2) in regards to the number of datapoints. Combined with the fact that it's normally executed in the main isolate, it can easily block the UI for multiple seconds for e.g. queries returning >10K datapoints.

It can be fixed (O(n^2) -> O(n log n)) as simply as:
```dart
   /// Given an array of [HealthDataPoint]s, this method will return the array
   /// without any duplicates.
   static List<HealthDataPoint> removeDuplicates(List<HealthDataPoint> points) {
-    final unique = <HealthDataPoint>[];
-
-    for (var p in points) {
-      var seenBefore = false;
-      for (var s in unique) {
-        if (s == p) {
-          seenBefore = true;
-        }
-      }
-      if (!seenBefore) {
-        unique.add(p);
-      }
-    }
-    return unique;
+    return LinkedHashSet.of(points).toList();
   }
```

...but this exposes a bug in HealthDataPoint: its implementation of `hashCode` produces unique hash codes every time, because it's based on toJson(), which uses a shallowly-compared collection, and this does not satisfy `Hash codes must be the same for objects that are equal to each other according to [operator ==].`
So for the above removeDuplicates implementation to work, HealthDataPoint.hashCode needs to be fixed e.g. like this:
```dart
   /// Override required due to overriding the '==' operator
   @override
-  int get hashCode => toJson().hashCode;
+  int get hashCode => Object.hash(
+      value,
+      unit,
+      dateFrom,
+      dateTo,
+      type,
+      platform,
+      deviceId,
+      sourceId,
+      sourceName,
+  );
 }
```

**Comment by cubuspl42** [comment]
This sounds like a possible cause of performance issues we had with Google Fit access via the Health plugin in my team! Are there any blockers from integrating these suggested improvements into the upstream?

**Comment by MadsVSChristensen** [comment]
Hey @noinskit 

Thank you for bringing this issue to our attention! I've added this fix to the upcoming version of Health! 

Best regards,
Mads
