### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ignaciomanchu1998** [cph-cachet/flutter-plugins#537]
I am using this package but I have problems with some phones:

In some samsumg phones they do not reset the values ​​of the steps at the end of the day.

Any method that allows me to do that?

**Comment by MadsVSChristensen** [comment]
Hey @Ignaciomanchu1998 
Could you provide more detailed information about the issue? We cant provice much help with the current description. 

Regards,
Mads

**Comment by MadsVSChristensen** [comment]
Closing this issue. Feel free to create a new issue with a more detailed description, if the problem persists.
