### ISSUE TITLE
[health 3.4.4] App crash when writing MINDFULNESS data with value ≠ 0

### ISSUE THREAD

**Issue by gdelataillade** [cph-cachet/flutter-plugins#542]
### Device
 - Device: iPhone SE 3rd Generation - Simulator
 - OS: iOS 15.4

### Flutter
 - Version: 2.10.4
 - Mode: debug

Note: It's an iOS only bug because the MINDFULNESS data type is not available for Android.

### Describe the bug
App crashes without catching any exceptions.

### To Reproduce
I cloned the example project and added the MINDFULNESS type to test reading and writing. Every time I use `writeHealthData` for `HealthDataType.MINDFULNESS` with a `value` parameter different than `0`, I get the crash. It is not the case if I set `value` to `0`. I don't see any documentation mentioning it.

### Expected behavior
MINDFULNESS data should be added to Apple Health and the app should not crash.

### Solution
Maybe you should process Mindfulness value just like Sleep and Headache are.

### Flutter doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by dreadjr** [comment]
@gdelataillade I believe that is by design. https://developer.apple.com/documentation/healthkit/hkcategorytypeidentifier/1648575-mindfulsession/

**Comment by MadsVSChristensen** [comment]
Hey @gdelataillade 

This is by design, BUT I have updated this method to ignore the user input and only use the correct value for the type - this will be coming out in the new release we are putting the finishing touches on.

Best regards,
Mads
