### ISSUE TITLE
[health 3.4.4] getHealthDataFromTypes(_startTime, _endTime, [HealthDataType.STEPS]) return data not in search interval

### ISSUE THREAD

**Issue by moxran** [cph-cachet/flutter-plugins#543]
### Device / Emulator and OS
 - Device: [iPhone 13]
 - OS: [iOS 15.4.1]

### Describe the bug
The function returns data beyond the search interval.

### To Reproduce
DateTime  startTime = DateTime(2022,5,5,12);
DateTime endTime = DateTime(2022,5,5,13);
try {
      /// fetch new data
      List<HealthDataPoint> healthData = await health
          .getHealthDataFromTypes(startTime, endTime, [HealthDataType.STEPS]);

      /// save all the new data points
      healthDataList.addAll(healthData);
    } catch (e) {
      debugPrint("Caught exception in fetchData: $e");
    }
healthDataList = HealthFactory.removeDuplicates(healthDataList);
debugPrint(healthDataList.toString()));

----------
output: 
HealthDataPoint - value: 206.0, unit: HealthDataUnit.COUNT, dateFrom: 2022-05-05 12:58:48.182, dateTo: 2022-05-05 13:04:24.758, dataType: HealthDataType.STEPS, platform: PlatformType.IOS, sourceId: com.apple.health 
......... more....

### Expected behavior
return only healthDataPoint within the search period, i.e., from 12:00:00 to 13:00:00

### Actual behavior
the last datapoint in the return:
dateFrom: 2022-05-05 12:58:48.182, dateTo: 2022-05-05 13:04:24.758,

### Flutter doctor 
ios$flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!

### Additional information
Add any other info about the problem here.

**Comment by MadsVSChristensen** [comment]
Hey @moxran 

This is intended behaviour as steps are saved in batches on iOS. Each batch might not be from the same source, so to allow this destinction and to allow a more finegrained look at the data, this is how `getHealthDataFromTypes` works with `STEPS`.

However, I suggest you try to use `getTotalStepsInInterval` as this will give you a single integer value of steps taken in the specified interval.

Regards,
Mads

**Comment by moxran** [comment]
Thank you for your reply!
