### ISSUE TITLE
health 3.4.4 - Deprecation of Google Fit APIs and introduction of Health Connect

### ISSUE THREAD

**Issue by indigothm** [cph-cachet/flutter-plugins#548]
### Description
At Google IO it was announced that Google Fit Android APIs will be deprecated and replaced by the new Health Connect hub. It will be necessary to replace the underlying native APIs on Android with the new ones by the end of the year. The new API provides significant benefits in terms of UX, privacy and more supported datatypes. 

### Additional information
[https://developer.android.com/guide/health-and-fitness/health-connect](
)

**Comment by MadsVSChristensen** [comment]
Thank you for bringing this to our attention! We will support Health Connect when it becomes relevant

Best regards,
Mads

**Comment by rshams-dius** [comment]
Any updates on whether the update has been put on the roadmap?

**Comment by tiloc** [comment]
Fwiw, they are not mentioning it in their release notes, but the Withings Healthmate app is now interoperable with Health Connect.

**Comment by frodefi** [comment]
@MadsVSChristensen Any estimates on when Health Connect will be supported?

**Comment by tiloc** [comment]
Google Fit and Samsung Health have recently enabled support for Health Connect.

**Comment by armanso** [comment]
@MadsVSChristensen I have started working on the Health Connect integration for our app. As long as your team does not have any internal road map, I can begin making a PR for adding support for all types.

Our team handles the heavy lifting such as permission management, SDK integration, and heartbeat, steps, and sleep stages integration with health connect.

**Comment by thomas4Bitcraft** [comment]
Any estimate for this?

**Comment by MadsVSChristensen** [comment]
I've just released 5.0.0 which has support for Health Connect, but the plugin is currently _limited_ as it focuses on Google Fit until Health Connect is out of beta.
