### ISSUE TITLE
Build failed when running flutter build apk

### ISSUE THREAD

**Issue by jaca420** [cph-cachet/flutter-plugins#549]
environment:
  sdk: ">=2.16.1 <3.0.0"

### Describe the bug
App runs without issues on the ios emulator but when running flutter build apk, it fails with the following messages: 

`../../../.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/lib/background_locator.dart:34:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addObserver(AutoStopHandler());
                     ^
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (25, 1): Class 'BackgroundLocatorPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in io.flutter.plugin.common.PluginRegistry.NewIntentListener
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (215, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (215, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (224, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (224, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (243, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (243, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (266, 5): 'onNewIntent' overrides nothing
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (275, 35): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/IsolateHolderExtension.kt: (42, 27): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/IsolateHolderService.kt: (269, 35): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/pluggables/DisposePluggable.kt: (17, 51): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/my-cpu/.pub-cache/hosted/pub.dartlang.org/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/pluggables/InitPluggable.kt: (22, 55): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_locator:compileReleaseKotlin'.
`

**Comment by MadsVSChristensen** [comment]
Hey @jaca420 

You need to provide more information to get a good answer - I will kindly ask you to resubmit the issue with a better description and I will close this for now as we cannot help you.

Regards,
Mads
