### ISSUE TITLE
[health 3.4.4] HealthDataUnit.MINUTES are actually seconds on iOS at HealthDataType.WORKOUT

### ISSUE THREAD

**Issue by filly82** [cph-cachet/flutter-plugins#552]
when comparing the data from this package with the Fitness/Health-App on iOS I've noticed that the value for HealthDataType.WORKOUT is actually in seconds and not in minutes

**Comment by MadsVSChristensen** [comment]
Hey @filly82 

We have just published Health 4.0.0 which has expanded the workouts for iOS and Android. This should fix the issue as the duration is now defined by the start and endtime.

Best regards,
Mads
