### ISSUE TITLE
[pedometer]android build faild,but debug run is ok

### ISSUE THREAD

**Issue by xuwankang** [cph-cachet/flutter-plugins#56]
** pedometer & 1.0.0**

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/iosappjingda/Documents/flutter
    • Framework revision 0b8abb4724 (13 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/iosappjingda/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G9500 • 9889db424651533259 • android-arm64 • Android 9 (API 28)

• No issues found!

**Describe the bug**
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     179.0s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...                           
[!] Flutter tried to create the file `android/settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:

    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:

            def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

            def plugins = new Properties()
            def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
            if (pluginsFile.exists()) {
                pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
            }

            plugins.each { name, path ->
                def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
                include ":$name"
                project(":$name").projectDir = pluginDirectory
            }

Please create the file and run this command again.

**Comment by MaskyS** [comment]
Migrate to androidX: https://github.com/cph-cachet/flutter-plugins/pull/40/files

**Comment by xuwankang** [comment]
I did already,and fix it,but I got a question,does the step is today’s or what

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kifah Meeran<mailto:notifications@github.com>
发送时间: 2020年2月26日 23:16
收件人: cph-cachet/flutter-plugins<mailto:flutter-plugins@noreply.github.com>
抄送: xuwankang<mailto:xuxiaobao1992@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [cph-cachet/flutter-plugins] [pedometer]android build faild,but debug run is ok (#56)


Migrate to androidX: https://github.com/cph-cachet/flutter-plugins/pull/40/files

―

**Comment by MaskyS** [comment]
I'm confused about that myself, I've seen past issues report that the steps
are cumulative and don't reset, but I have to test

**Comment by MaskyS** [comment]
@xuwankang steps are cumulative but reset whenever device is rebooted.

**Comment by xuwankang** [comment]
Thanks,but do you know how to get today’s steps?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kifah Meeran<mailto:notifications@github.com>
发送时间: 2020年3月4日 18:35
收件人: cph-cachet/flutter-plugins<mailto:flutter-plugins@noreply.github.com>
抄送: xuwankang<mailto:xuxiaobao1992@live.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [cph-cachet/flutter-plugins] [pedometer]android build faild,but debug run is ok (#56)


@xuwankang<https://github.com/xuwankang> steps are cumulative but reset whenever device is rebooted.

―

**Comment by MaskyS** [comment]
I'm planning to do a write-up about it on my [blog](blog.maskys.com) soon, but roughly, here's how I did it: 
You'll need the following vars: 
- `savedStepCount` to save previous days' step count (e.g using shared_preferences). If you already save *and display/use/show* previous days' step count, you cannot use that var for this purpose, as this savedStepCount will reset intermittently
- `lastDaySaved`, either an int or a DateTime to save the last time you "reset" your pedometer. this will become apparent shortly.
- `value` is the count received from the pedometer stream
- `todayStepCount`

```
    if (value < savedStepCount) {
      // Upon device reboot, pedometer resets. When this happens, the saved counter must be reset as well.
      savedStepCount = 0;
      // {persist this value using a package of your choice here}
    }

      var lastDaySaved;
      // {load the saved value using a package of your choice here}

      if (lastDaySaved < todayDayNo) { // whether you use int or DateTime, this should only return true once every 24 hours, otherwise your value will reset too frequently.
        
        lastDaySaved = todayDayNo
        // {save lastDaySaved here}
        savedStepCount = value;
        // {save savedStepCount here}
      }

      todayStepCount = value - savedStepCount;
      return todayStepCount; // this is your daily steps value.
```
 
then subtract that from the pedometer count.

**Comment by ruskimarcin** [comment]
To fix this, I had to 
```
git clone https://github.com/cph-cachet/flutter-pluginsthis 
mkdir my_flutter_project_dir/packages
cp flutter-plugins/packages/pedometer my_flutter_project_dir/packages
```
then in **`my_flutter_project_dir/packages/pedometer/android/build.gradle`** I changed
```gradle
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'  // <- bump
    }
    

android {
    compileSdkVersion 28 // <- bump

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" 
//                                 ^ bump to androidX
    }
    lintOptions {
        disable 'InvalidPackage'
    }

```
Finally in **`pubspac.yaml`**, I changed  
```yaml
dependencies:
  pedometer: ^1.0.0
```
to
```yaml
dependencies:
  pedometer:
    path: packages/pedometer
```
and built my project

**Comment by ruskimarcin** [comment]
to extend on @MaskyS wonderful post, here is my implementation of his idea, with a bonus of being able to preserve today steps count over reboot
`value` is the value passed directly from steps counter stream
```dart
Future<int> getTodaySteps(int value) async {
  SharedPreferences prefs = await SharedPreferences.getInstance();
  int todayDayNo = DateTime.now().day;
  int savedStepCount = prefs.getInt('savedStepCount') ?? 0;
  int lastDaySaved = prefs.getInt('lastDaySaved') ?? 0;
  int todaySteps = prefs.getInt('todaySteps') ?? 0;
  int lastValue = prefs.getInt('stepsLastValue') ?? 0;
  prefs.setInt('stepsLastValue', value);

  // device reboot
  if (savedStepCount > value) {
    prefs.setInt('savedStepCount', 0);
    savedStepCount = 0;
  }

  // next day
  if (todayDayNo > lastDaySaved) {
    prefs.setInt('lastDaySaved', todayDayNo);
    prefs.setInt('savedStepCount', value);
    prefs.setInt('todaySteps', 0);
    savedStepCount = value;
    todaySteps = 0;
  }

  if (savedStepCount == 0 && todaySteps > value) {
    if (value < 10) {
      prefs.setInt('todaySteps', value + todaySteps);
    } else {
      prefs.setInt('todaySteps', value - lastValue + todaySteps);
    }
  } else {
    prefs.setInt('todaySteps', value - savedStepCount);
  }

  todaySteps = prefs.getInt('todaySteps') ?? 0;

  if (todaySteps > 0) {
    return todaySteps; 
  } else {
    return 0;
  }
}
```

- `if (todaySteps > 0)` is an overkill to make sure I never run into some sticky situation where I display negative step count in UI
- `if (value < 10)` is to make sure there is ten step buffor for a sensor to catch up after reboot, otherwise, it would substract `lastValue` recorded before the reboot, from `value` which would be equal to 0 after reboot

**Comment by thomasnilsson** [comment]
Hi, the latest version of the Pedometer plugin (1.2.0) has the same behaviour on both platforms, i.e. reporting the step count since last reboot. 

The idea of keeping track of the step count between boots is great but our philosophy on the plugins is that they have to be quite simple and 'lean'. This means you will have to store these things yourselves, perhaps make a package (not a plugin) which uses the pedometer plugin?

**Comment by MaskyS** [comment]
I finally got around to writing down how a full-blown code sample for tracking daily steps. Here's the [blog post](https://blog.maskys.com/implementing-a-daily-step-count-pedometer-in-flutter/) and the [code](https://github.com/MaskyS/daily_steps).

**Comment by yogeshButani** [comment]
> to extend on @MaskyS wonderful post, here is my implementation of his idea, with a bonus of being able to preserve today steps count over reboot `value` is the value passed directly from steps counter stream
> 
> ```dart
> Future<int> getTodaySteps(int value) async {
>   SharedPreferences prefs = await SharedPreferences.getInstance();
>   int todayDayNo = DateTime.now().day;
>   int savedStepCount = prefs.getInt('savedStepCount') ?? 0;
>   int lastDaySaved = prefs.getInt('lastDaySaved') ?? 0;
>   int todaySteps = prefs.getInt('todaySteps') ?? 0;
>   int lastValue = prefs.getInt('stepsLastValue') ?? 0;
>   prefs.setInt('stepsLastValue', value);
> 
>   // device reboot
>   if (savedStepCount > value) {
>     prefs.setInt('savedStepCount', 0);
>     savedStepCount = 0;
>   }
> 
>   // next day
>   if (todayDayNo > lastDaySaved) {
>     prefs.setInt('lastDaySaved', todayDayNo);
>     prefs.setInt('savedStepCount', value);
>     prefs.setInt('todaySteps', 0);
>     savedStepCount = value;
>     todaySteps = 0;
>   }
> 
>   if (savedStepCount == 0 && todaySteps > value) {
>     if (value < 10) {
>       prefs.setInt('todaySteps', value + todaySteps);
>     } else {
>       prefs.setInt('todaySteps', value - lastValue + todaySteps);
>     }
>   } else {
>     prefs.setInt('todaySteps', value - savedStepCount);
>   }
> 
>   todaySteps = prefs.getInt('todaySteps') ?? 0;
> 
>   if (todaySteps > 0) {
>     return todaySteps; 
>   } else {
>     return 0;
>   }
> }
> ```
> 
> * `if (todaySteps > 0)` is an overkill to make sure I never run into some sticky situation where I display negative step count in UI
> * `if (value < 10)` is to make sure there is ten step buffor for a sensor to catch up after reboot, otherwise, it would substract `lastValue` recorded before the reboot, from `value` which would be equal to 0 after reboot

This code works fine, but want to know that ho to reset steps  to 0 daily? for example, when a new day starts, the steps count should be automatically set to 0 even if i don't open the app on that day

for example after 12am, new day have started and i have taken the steps, so when i open the app, i need to see updated step count for that day...it means we have to run above function in backgroud and it should be automatically hit without opening the app, whenver new day starts.
