### ISSUE TITLE
Sleep data is requested with GFit even when it is not requested by the client

### ISSUE THREAD

**Issue by yogendrapai17** [cph-cachet/flutter-plugins#569]
So, as per version 4.0.0, I wanted to request the workout data types and the distance delta data from the GFit. But somehow, the sleep data is also requested by the client when I refer to my google account's permission for the app. Works fine in debug, but causes an issue in production as the sleep permission for the app was not pre-approved by google and hence the build is not working in production

**Comment by anoop-dtrans** [comment]
On checking the Android implementation found that the sleep permission is indeed requested when the workout feature is used. 

https://github.com/cph-cachet/flutter-plugins/blob/d6bff0eb59b8ed08b22058c13876ef3737fb052b/packages/health/android/src/main/kotlin/cachet/plugins/health/HealthPlugin.kt#L792

**Comment by rshams-dius** [comment]
Any chance it's gonna be modified in a future release?
