### ISSUE TITLE
Kotlin version issue 

### ISSUE THREAD

**Issue by ghost** [cph-cachet/flutter-plugins#57]
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':health' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by softmarshmallow** [comment]
```Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':health' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71
```
same here

**Comment by KingDarBoja** [comment]
Pretty much explained by this [comment](https://stackoverflow.com/a/54606054/12405220) on StackOverflow.

But looking at the current [source](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/health/android/build.gradle) code, it seems it got fixed few commits ago.
