### ISSUE TITLE
[Health 4.1.1] Sleep data does not show!

### ISSUE THREAD

**Issue by alireza-dhp** [cph-cachet/flutter-plugins#586]
### Device / Emulator and OS
 - Device: [Android Emulator]
 - OS: [Android version 9]

### Describe the bug
I am trying to fetch sleep data, but it does not show any type of sleep data (SLEEP_ASLEEP  or SLEEP_IN_BED or SLEEP_AWAKE).
Any other types of data are available as well.

**Comment by fix92** [comment]
could this be relavant to this issue and therefore be closed? https://github.com/cph-cachet/flutter-plugins/issues/603
