### ISSUE TITLE
Pedometer:3.0.0 is counting steps inaccurate in iphone.

### ISSUE THREAD

**Issue by AhmedZahidProgrammar** [cph-cachet/flutter-plugins#587]
Pedometer:3.0.0

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - iPhone 7,iPhone 11
 - iOS 15.6.1

### Describe the bug
 It counts 927  steps in one minute. Which is logically not possible. I was walking normally

### To Reproduce
install the pedometer example app and tried on iPhone

### Expected behavior
It should count the accurate steps on ios

.

### Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

### Additional information
Add any other info about the problem here.

**Comment by kzawadi** [comment]
Hello, I think it is working as intended, as the package states that "_

> The step count represents the number of steps taken since the last system boot. On Android, any steps taken before installing the application will not be counted

or you can clarify more on your issue.

**Comment by AhmedZahidProgrammar** [comment]
The pedometer package is working fine on android phones but when we test on iPhones, the steps are inaccurate. I am attaching a link to screen recording of the iPhone 7 , in the video, the steps are 0, when I start walking the steps are increasing but my steps are lower than the pedometer steps, I was walking normally. I have compared the steps with the apple health app on iPhone.I am waiting for your reply
https://drive.google.com/file/d/1x6-vkRO5NKaMe2X2Qj_-GbnvM-EkHcIJ/view

**Comment by kzawadi** [comment]
Oh, unlucky as I don't have an iOS device currently to test and see what is happening.

**Comment by AhmedZahidProgrammar** [comment]
Can you tell me who write the code for ios in swift for pedometer plugin,Share his contact here

**Comment by kzawadi** [comment]
just go to the main page you will see more info about the author ..am not the author

**Comment by moxran** [comment]
This plugin reads the CMPedometer data. iOS Health will combine data from different sources that are using the same apple account, it might be possible it uses a different algorithm to calculate the steps. So you may see different data.  You can check the swift code for the plugin in iOS/.symlinks/plugins/pedometer/ios/Classes/SwiftPedometerPlugins.swift.

You might want to check the Health plugin from the same developer team.
