### ISSUE TITLE
[health 4.1.1] Writing non-trivial types such as blood pressure or oxygen saturation to Google Fit

### ISSUE THREAD

**Issue by mk-dev-1** [cph-cachet/flutter-plugins#588]
It appears that this plugin is not capable of setting more complex types for Google Fit. For example a blood pressure record requires at least a systolic and diastolic value to be set as fields for the same datapoint. For oxygen saturation you need the oxygen saturation level and any supplemental flow rate.

I have written two methods for that for my own use (happy to share), but I believe a method should be implemented that allows setting a list of values with a list of fields. I would gladly implement this, but unfortunately my know how about Android and Kotlin programming is very limited.

Would anyone be up to add this?

**Comment by rafaellop** [comment]
@mk-dev-1 Can you please share the methods you used to store blood pressure in Google Fit?

**Comment by MadsVSChristensen** [comment]
Added blood pressure in version 4.6.0
