### ISSUE TITLE
Pedometer sensor event listener "onSensorChanged" not trigger when app is killed

### ISSUE THREAD

**Issue by deepakrana0011** [cph-cachet/flutter-plugins#60]
The sensor listener method "onSensorChanged" inside pedometer plugin not called when app is in kill mode and pedometer plugin init though "Alarm Manager". Its working fine when app is not killed

**Comment by paltin** [comment]
Same issue when trying to run the plugin on background task using workmanager (0.2.2) plugin

**Comment by ruskimarcin** [comment]
https://www.reddit.com/r/Flutter/comments/focw0y/what_is_a_reliable_way_of_tracking_user_steps/
and for the brave: https://stackoverflow.com/questions/34472700/using-type-step-counter-in-a-background-service

**Comment by thomasnilsson** [comment]
You will need to wrap the plugin in a foreground service to achieve this. 

Currently it's not part of the plan for this plugin. The step value is however still incremented while app is killed, and the change in steps taken will be reflected when the app is started again.

This is the case for both android and iOS in the pedometer 1.2.0 version. https://pub.dev/packages/pedometer
