### ISSUE TITLE
[health: ^4.1.1] REM Sleep, Light Sleep, Deep Sleep, Awake (during sleeep) Data

### ISSUE THREAD

**Issue by AfriwanAhda** [cph-cachet/flutter-plugins#603]
**Health - Sleep**

Device / Emulator and OS
    OS: Android

### Description
REM Sleep, Light Sleep, Deep Sleep, Awake (during sleeep) data is not available.

### Additional information
Google Fit provide REM Sleep, Light Sleep, Deep Sleep, and Awake (during sleeep) data for Android device, but it doesn't exist in this plugin.

**Comment by tijanirf** [comment]
Oh yes, we do need this! I hope the PR will be reviewed soon.
