### ISSUE TITLE
[health 4.1.1]

### ISSUE THREAD

**Issue by bhagat-techind** [cph-cachet/flutter-plugins#605]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [Vivo]
 - OS: [12]

### Describe the bug
Crash when trying to access permission for EXERCISE_TIME.

### To Reproduce
types = [ HealthDataType.EXERCISE_TIME ];
permissions = [ HealthDataAccess.READ_WRITE ];

health.requestAuthorization(dataType: dataType,permissions: permissions);

### Expected behavior
Asks user to grant permissions

### Actual behavior
PlatformException(error, Unsupported dataType: EXERCISE_TIME, null, java.lang.IllegalArgumentException: Unsupported dataType: EXERCISE_TIME

**Comment by MadsVSChristensen** [comment]
This health data type only works on iOS
