### ISSUE TITLE
revokePermissions does not work

### ISSUE THREAD

**Issue by alireza-dhp** [cph-cachet/flutter-plugins#618]
By calling the revoke Permissions method in the HealthFactory class, I was unable to disconnect the Google Fit account.
THe exception message:
MissingPluginException(No implementation found for method revokePermissions on channel flutter_health)

**Comment by shilangyu** [comment]
Looking at the native code, this method is not implemented at all on any platform by this plugin.

**Comment by agilst** [comment]
Getting this on version 6.0.0
`MissingPluginException(No implementation found for method revokePermissions on channel flutter_health)`
