### ISSUE TITLE
noise_meter plugin doesn't request for microphone and storage permission

### ISSUE THREAD

**Issue by xiaozhi239** [cph-cachet/flutter-plugins#62]
**Plugin name & version**
noise_meter
1.0.1

**Describe the bug**
I installed noise_meter, start recording and didn't find the callback (onData) being triggered on the flutter side. I checked logcat and found that permission is not granted. So I manually granted the storage and microphone permissions, and it works perfectly. 

Digging into NoiseMeterPlugin, I didn't find it explicitly requesting permissions, should it be done somewhere, say registerWith?

Sorry that I removed the following template, as this seems not a tricky case, and could quickly browse the code to check. But let me know if I am wrong. :)

**Comment by thomasnilsson** [comment]
Hi! This, among other things, is now fixed in the latest version of `noise_meter` :)

Sorry for the late response

**Comment by xiaozhi239** [comment]
Thanks for the fix!
