### ISSUE TITLE
Flutter Health Package (4.3.0)D/FLUTTER HEALTH(21559): Access Denied!

### ISSUE THREAD

**Issue by IbrahimTalha0** [cph-cachet/flutter-plugins#626]
User encounters "D/FLUTTER HEALTH(21559): Access Denied!" error after selecting the mail to connect to "Google Fit"
Package for me it's only working in test mode. when I set the project to production mode, it stops working.
do you have a solution for this? 
I set the oauth id. I have given the necessary permissions.
OAuth ID Verf: 
![Ekran Resmi 2022-11-23 23 46 16](https://user-images.githubusercontent.com/75858218/203643090-59fb78bf-3c77-472b-97d0-38245f4fd2b6.png)
OAuth Scope:
![Ekran Resmi 2022-11-23 23 43 19](https://user-images.githubusercontent.com/75858218/203642769-74949cbe-b3a7-4a34-9d9e-2a4fa119ab4b.png)
Maniesft Permissions:
![Ekran Resmi 2022-11-23 23 44 22](https://user-images.githubusercontent.com/75858218/203642848-ff472402-71d9-4490-8a11-5d38dc969902.png)
Flutter Permissions:
![Ekran Resmi 2022-11-23 23 44 59](https://user-images.githubusercontent.com/75858218/203642925-249e828e-91f6-42af-913c-f0e22339b0cf.png)
![Ekran Resmi 2022-11-23 23 48 14](https://user-images.githubusercontent.com/75858218/203643377-d48217b3-ecc4-44b6-88b7-23e6ae2a72cc.png)

**Comment by VUNO-wonwoohan** [comment]
I have same problem.
This issue appears in the release mode build.

**Comment by IbrahimTalha0** [comment]
@VUNO-wonwoohan I solved the problem. The application was using a different sha1 code in release mode. I found the sha1 code that the application uses in release mode and added it to the necessary places. Problem solved.
