### ISSUE TITLE
Flutter health 4.4.0 plugin > Add nutrient data

### ISSUE THREAD

**Issue by JuanFcoRomero** [cph-cachet/flutter-plugins#638]
Hello!!

I need to access nutrients data on an app like proteins, carbs, vitamins...

This is the documentation of Apple:

https://developer.apple.com/documentation/healthkit/data_types/nutrition_type_identifiers

Is this data integration on your roadmap?

Thank you.

**Comment by hoffmatteo** [comment]
Nutrition data was added to health in a recent release!
