### ISSUE TITLE
[Movisens] How do I get the HRV value?

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#646]
### Description

The [HrvService](https://pub.dev/documentation/movisens_flutter/latest/movisens_flutter/HrvService-class.html) does not seem to have a way to get the HRV value? Only information about if it is valid? How do I get the HRV value?

**Comment by bardram** [comment]
Is this the [HrvRmssd](https://docs.movisens.com/Algorithms/ecg_hr_hrv/#hrv-parameter-rmssd-hrvrmssd) value?

**Comment by MadsVSChristensen** [comment]
Yes it is
