### ISSUE TITLE
[Health 4.4.0] - CocoaPods could not find compatible versions for pod "health"

### ISSUE THREAD

**Issue by tajjacob** [cph-cachet/flutter-plugins#654]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: iPhone
 - OS: 16.2

```
[!] CocoaPods could not find compatible versions for pod "health":
  In Podfile:
    health (from `.symlinks/plugins/health/ios`)

Specs satisfying the `health (from `.symlinks/plugins/health/ios`)` dependency were found, but they required a higher minimum deployment target.
```

### Describe the bug
I try to run health plugin on ios simulator and this error has occured. I already add healthkit capabilities in xcode and add 2 entries in info.plist. I also run pod install and the same error has occured. 
*I have no issue running on android emulator.

### To Reproduce
Steps to reproduce the behavior.

### Expected behavior
What did you expect to happen?

### Actual behavior
What did happen? Include stack traces and exception print-outs.

### Screenshots
<img width="639" alt="image" src="https://user-images.githubusercontent.com/63710008/211960711-c816b999-b756-479c-9016-059ea1d759d0.png">

### Flutter doctor 
Please run `flutter doctor` and add the output here.

### Additional information
Add any other info about the problem here.

**Comment by tajjacob** [comment]
I just found the solution. Need to update minimum deployments to ios 13.0

<img width="462" alt="image" src="https://user-images.githubusercontent.com/63710008/211968136-2b559614-e224-4510-88c0-883df58b5baf.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/63710008/211968244-af563416-2d49-4c7a-bce0-9a0a4f095251.png">

**Comment by franco820711** [comment]
> 


> I just found the solution. Need to update minimum deployments to ios 13.0
> 
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/63710008/211968136-2b559614-e224-4510-88c0-883df58b5baf.png">
> 
> <img alt="image" width="342" src="https://user-images.githubusercontent.com/63710008/211968244-af563416-2d49-4c7a-bce0-9a0a4f095251.png">


thanks, I just fixed

**Comment by shilangyu** [comment]
But that drops support for iOS 12, not really a fix.

**Comment by jhonsabowsla** [comment]
not be cocky but, what devices as of 2023 run on ios 12 ?
