### ISSUE TITLE
[Health 4.4.0] Revoking permissions iOS

### ISSUE THREAD

**Issue by thomasmol** [cph-cachet/flutter-plugins#659]
How do I revoke permissions on iOS? Is this even possible at all?

**Comment by arioul89** [comment]
Hi, you have to go to your Health App, then click on "Share" (second button on bottom bar), then select the App you want to revoke permission.

**Comment by MadsVSChristensen** [comment]
It is not _programmatically_ possible to revoke permissions on iOS to my knowledge. 
Users can do it on the phone as @arioul89 describes.
