### ISSUE TITLE
carp_background_location: ^1.0.2+1

### ISSUE THREAD

**Issue by gordett** [cph-cachet/flutter-plugins#669]
I can't start my app when I import this package. Anyone with this error?

carp_background_location: ^1.0.2+1

e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (25, 1): Class 'BackgroundLocatorPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in io.flutter.plugin.common.PluginRegistry.NewIntentListener
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (215, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (215, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (224, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (224, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (243, 43): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (243, 48): Type mismatch: inferred type is Map<Any, Any>? but Map<Any, Any> was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (266, 5): 'onNewIntent' overrides nothing
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/BackgroundLocatorPlugin.kt: (275, 35): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/IsolateHolderExtension.kt: (42, 27): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/IsolateHolderService.kt: (269, 35): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/pluggables/DisposePluggable.kt: (17, 51): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected
e: /Users/gordett/.pub-cache/hosted/pub.dev/background_locator-1.6.12/android/src/main/kotlin/rekab/app/background_locator/pluggables/InitPluggable.kt: (22, 55): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

**Comment by KlGleb** [comment]
Same issue, carp_background_location: ^3.0.1

**Comment by gordett** [comment]
someone could help about this error?

**Comment by bardram** [comment]
carp_background_location 4.0.0 has been published and I'm closing this old issues.
