### ISSUE TITLE
health - 4.5.0 

### ISSUE THREAD

**Issue by bhagat-techind** [cph-cachet/flutter-plugins#678]
**health required relogin even if i login the app with google_login**

### Description
Please create a call back to pass client token to auto login in health plugin.

**Comment by tagdev27** [comment]
Change this line of code in the requestAuthorization method inside HealthPlugin.kt
`val isGranted = false` to 

`val isGranted = GoogleSignIn.hasPermissions(GoogleSignIn.getLastSignedInAccount(context!!), optionsToRegister)`

**Comment by hoffmatteo** [comment]
This issue is fixed in the latest version.
