### ISSUE TITLE
[Health v4.6.0] Authorization not granted

### ISSUE THREAD

**Issue by maxiaodegithub** [cph-cachet/flutter-plugins#686]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. OPPO Find X5 Pro]
 - OS: [e.g. Android 13]
![image](https://user-images.githubusercontent.com/19525713/226853511-57941282-3242-45e5-93d6-656b26b35bba.png)

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug

![image](https://user-images.githubusercontent.com/19525713/226852248-299cf566-ac76-42ca-b28c-88317092554d.png)
Requested returns false

Then the log displays
 There was an error getting the total steps in the interval!
 4: The user must be signed in to make this API call.
 [Ljava.lang.StackTraceElement;@c73b88

Then I use the health demo from github and run release, which also shows Authorization not granted and Authorization not granted

**Comment by MadsVSChristensen** [comment]
Did you create an API key and followed the guide at https://developers.google.com/fit/android/get-api-key ?

**Comment by maxiaodegithub** [comment]
The issue has been resolved because the consent screen is not configured
