### ISSUE TITLE
[noise_meter] sampling rate not available

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#693]
The `noise_meter` plugin has stopped compiling after the update of `audio_streamer`.

![image](https://user-images.githubusercontent.com/1196642/228856418-6480031b-f7ae-4941-b086-32d470e83cf6.png)

**Comment by hoffmatteo** [comment]
Updated noise streamer with new correct audio streamer version: https://github.com/cph-cachet/flutter-plugins/pull/691
