### ISSUE TITLE
[Health 5.0.0] supplemental_oxygen_flow_rate not set (Google Fit)

### ISSUE THREAD

**Issue by maxiaodegithub** [cph-cachet/flutter-plugins#694]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. oppo find x5 pro]
 - OS: [e.g. Android 12]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
health: ^5.0.0 and health: ^4.4.0
Error reported when writing blood oxygen

PlatformException(error, supplemental_oxygen_flow_rate not set, null, java.lang.IllegalArgumentException: supplemental_oxygen_flow_rate not set

 bool success = await health.writeHealthData(
        value / 100, HealthDataType.BLOOD_OXYGEN, time, time,);

**Comment by hoffmatteo** [comment]
This bug will be fixed in the upcoming release.
For now, a temporary fix can be applied by setting the supplemental oxygen flow rate to the default of zero:
https://github.com/cph-cachet/flutter-plugins/blob/d6c5941ef9425b0c4cb03bcf6c4aa5d8f7432ab4/packages/health/android/src/main/kotlin/cachet/plugins/health/HealthPlugin.kt#L618-L622

```kotlin
    // ...
    // temporary fix
    val isOxygen = field == HealthFields.FIELD_OXYGEN_SATURATION
    if (isOxygen) {
      builder.setField(HealthFields.FIELD_SUPPLEMENTAL_OXYGEN_FLOW_RATE, 0.0f)
    }
    // existing code
    val dataPoint = if (!isIntField(dataSource, field))
      builder.setField(field, (if (!isGlucose) value else (value / MMOLL_2_MGDL).toFloat()))
        .build() else 
      builder.setField(field, value.toInt()).build()
    // ...
```

**Comment by wonunicorn** [comment]
Health [8.1.0] supplemental_oxygen_flow_rate not set (Google Fit) - bug still exists, when try write health data to HealthDataType.BLOOD_OXYGEN on Android
