### ISSUE TITLE
[Health 5.0.0] Terminating app due to uncaught exception '_HKObjectValidationFailureException'

### ISSUE THREAD

**Issue by appsowner** [cph-cachet/flutter-plugins#697]
**Remember to specify the plugin name in the title!**

*** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'HKDiscreteQuantitySample 8C5DD62A-76BD-46FA-B1D0-2158840B18A1 1100 m  (2023-04-05 12:54:30 -0400 - 2023-04-05 13:14:30 -0400) requires unit of type Mass. Incompatible unit: m'

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. iPhone 13]
 - OS: [e.g. iOS 16.2]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
run app with iphone physics

### To Reproduce
Steps to reproduce the behavior.

### Expected behavior
What did you expect to happen?

### Actual behavior
What did happen? Include stack traces and exception print-outs.

### Flutter doctor 
Please run `flutter doctor` and add the output here.

### Additional information
Add any other info about the problem here.

**Comment by hoffmatteo** [comment]
The example app includes the distance_delta type by default, even though it is only supported on Android and not iOS. I will remove it in the upcoming release to avoid any confusion.

For now, commenting out these two lines will fix the issue:
https://github.com/cph-cachet/flutter-plugins/blob/d6c5941ef9425b0c4cb03bcf6c4aa5d8f7432ab4/packages/health/example/lib/main.dart#L153-L154

**Comment by appsowner** [comment]
Hi, 

I test new version with getSteps! and very good !! here demo results 👍 


I/flutter (17714): pasos :60
I/flutter (17714): total pasos: 60


![Screenshot_20230424_223649](https://user-images.githubusercontent.com/110705397/234162001-da919906-3d39-43b2-a8ee-c2254a39404b.jpg)

thank you
