### ISSUE TITLE
[Health 5.0.0, HealthConnect] getTotalSteps not working

### ISSUE THREAD

**Issue by appsowner** [cph-cachet/flutter-plugins#698]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [Samsung A13]
 - OS: [e.g. Android 13]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
run 
 steps = await health.getTotalStepsInInterval(midnight, now);

error :
 MissingPluginException(No implementation found for method getTotalStepsInInterval on channel flutter_health)

### To Reproduce
example the repository

### Expected behavior
What did you expect to happen?
view data of the steps

### Actual behavior
What did happen? Include stack traces and exception print-outs.

ormTraversals:4108 android.view.ViewRootImpl.doTraversal:2991 android.view.ViewRootImpl$TraversalRunnable.run:10665 android.view.Choreographer$CallbackRecord.run:1301 
I/flutter (31704): error al obtener pasos : MissingPluginException(No implementation found for method getTotalStepsInInterval on channel flutter_health)
I/flutter (31704): total pasos: null

### Flutter doctor 
Please run `flutter doctor` and add the output here.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.3 22E252 darwin-x64, locale es-419)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.70.0)
[✓] Connected device (4 available)
 [✓] HTTP Host Availability

• No issues found!

### Additional information
Add any other info about the problem here.

D/AndroidRuntime(31704): Shutting down VM
E/AndroidRuntime(31704): FATAL EXCEPTION: main
E/AndroidRuntime(31704): Process: com.example.salutable, PID: 31704
E/AndroidRuntime(31704): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31704):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(31704):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime(31704):        at cachet.plugins.health.HealthPlugin.errHandler$lambda$11(HealthPlugin.kt:884)
E/AndroidRuntime(31704):        at cachet.plugins.health.HealthPlugin.$r8$lambda$9g6-Lc0WUTrBxFRdWITfq8TaLP0(Unknown Source:0)
E/AndroidRuntime(31704):        at cachet.plugins.health.HealthPlugin$$ExternalSyntheticLambda8.onFailure(Unknown Source:6)
E/AndroidRuntime(31704):        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(31704):        at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(31704):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31704):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(31704):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(31704):        at android.app.ActivityThread.main(ActivityThread.java:8741)
E/AndroidRuntime(31704):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31704):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(31704):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process (31704): Sending signal. PID: 31704 SIG: 9

**Comment by hoffmatteo** [comment]
I am having trouble reproducing the error, which are the exact steps you undertook?
E.g. you just started the example application and pressed the fetch step data button, or are you using your own implementation?

**Comment by hoffmatteo** [comment]
Ah I understand now, it is an error with HealthConnect. Looking into it.

**Comment by hoffmatteo** [comment]
Issue is caused by a missing return statement, as the total steps are not currently implemented for HealthConnect
https://github.com/cph-cachet/flutter-plugins/blob/d6c5941ef9425b0c4cb03bcf6c4aa5d8f7432ab4/packages/health/android/src/main/kotlin/cachet/plugins/health/HealthPlugin.kt#L1151-L1153
It can be temporarily fixed by adding a return statement at the end of the if clause and will be fixed in the upcoming release.

**Comment by CemTitor** [comment]
So I didn't understand exactly, can I use both Health Connect and gettingTotalSteps?

Because when I changed the useHealthConnectIfAvailable parameter to false, it worked but I can't use Health Connect this way.

`final HealthFactory _health = HealthFactory(useHealthConnectIfAvailable: false);`

And also I try this like you said but it doesn't work
`if (useHealthConnectIfAvailable && healthConnectAvailable) {
      result.notImplemented()
      return
    }`

**Comment by hoffmatteo** [comment]
Currently getTotalSteps is not implemented for HealthConnect, but I added it in the linked pull request.

I will probably release it tomorrow, if you want to take a look at it before please feel free to check out the pull request!

**Comment by CemTitor** [comment]
Oh I saw now, thank you so much
