### ISSUE TITLE
Air Quality Plugin is not returning data

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#70]
**Plugin name & version**
Air Quality - using master branch from github.

**Describe the bug**
The plugin seems not to return any data.

**To Reproduce**
Just run the test in the plugin -- nothing happens.

**Smartphone(s) / Emulator**
Running the test i IntelliJ

**Comment by bardram** [comment]
This might be the same problem as #69 -- but since there is no example app in the Air Quality plugin, I can't test it on a physical phone....

**Comment by thomasnilsson** [comment]
There is now an example app included in the Air Quality package.
