### ISSUE TITLE
[Health 5.0]

### ISSUE THREAD

**Issue by appsowner** [cph-cachet/flutter-plugins#700]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. Samsung a13]
 - OS: [e.g. iOS 13.1]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
not found  data for android 13 with health connect, i testing all datatypes and every nothing retrieve data

### To Reproduce
i use example the plugins

### Expected behavior
What did you expect to happen?
view data the galaxy watch 4 

### Actual behavior
What did happen? Include stack traces and exception print-outs.

### Flutter doctor 
Please run `flutter doctor` and add the output here.

[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3.1 22E261 darwin-x64, locale es-419)
    • Flutter version 3.7.10 on channel stable at /Users/csanchezb/Documents/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (8 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/csanchezb/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.70.0)
    • VS Code at /Users/csanchezb/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM A135M (mobile)     • R58T51ER11F               • android-arm    • Android 13 (API 33)
    • Iphone Chris (mobile) • 00008110-00066D021433801E • ios            • iOS 16.4 20E247
    • macOS (desktop)       • macos                     • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 112.0.5615.49
    ! Error: Apple Watch de Carlos needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Additional information

for ios there is no problem to recover data with the same method

**Comment by hoffmatteo** [comment]
I am not able to reproduce this behaviour, what steps are you undertaking exactly?
If you first add data using the example app, and then fetch data, nothing appears?

**Comment by appsowner** [comment]
Hi, here example with images y logs

/FLUTTER_HEALTH( 8619): Access Granted (to Health Connect)!
I/ViewRootImpl@425c6b7[MainActivity]( 8619): stopped(false) old = true
D/ViewRootImpl@425c6b7[MainActivity]( 8619): WindowStopped on com.example.salutable/com.example.salutable.MainActivity set to false
I/flutter ( 8619): authorized:
I/flutter ( 8619): true

I/flutter ( 8619): requested
I/flutter ( 8619): true
I/flutter ( 8619): 2023-04-17 00:00:00.000
I/flutter ( 8619): 2023-04-17 14:46:32.601358
I/flutter ( 8619): isDataTypeAvailable HealthDataType.HEART_RATE
I/flutter ( 8619): true
I/flutter ( 8619): Datos  :0
![Screenshot_20230417_145719_Permission controller](https://user-images.githubusercontent.com/110705397/232585501-26054a02-7ed4-4aeb-a723-dbd51016c7bd.jpg)
![Screenshot_20230417_145806_Permission controller](https://user-images.githubusercontent.com/110705397/232585509-4c6db24c-17e7-4d99-8d30-2efdad58fd4b.jpg)
![Screenshot_20230417_145833_Health Connect](https://user-images.githubusercontent.com/110705397/232585512-a2aca43f-0c04-473c-96c1-c694c0b020e1.jpg)









Thank you.

**Comment by appsowner** [comment]
also see you data available the heart rate in my phone. see image

![Screenshot_20230417_150437_Samsung Health](https://user-images.githubusercontent.com/110705397/232586470-39ce383c-541a-4ebe-b528-d7f8ff5d7325.jpg)



thank you

**Comment by hoffmatteo** [comment]
If you go into HealthConnect > Data and access > Vitals > Heart rate, is the health app listed as can read and write? 
And if you go then further into See all entries, is your data shown there?

**Comment by appsowner** [comment]
Hi ,

message : you don't have any data in HealtConnect, i have all permission otorged.  Whats up?. Thank you...

**Comment by appsowner** [comment]
Hi, 

install app health async and synchronize data between health connect and Samsung connect, view results: 


I/flutter (23505): requested
I/flutter (23505): true
I/flutter (23505): 2023-04-21 00:00:00.000
I/flutter (23505): 2023-04-21 13:17:03.026382
I/flutter (23505): isDataTypeAvailable HealthDataType.HEART_RATE
I/flutter (23505): true
I/flutter (23505): Datos  :3

view image
![Screenshot_20230421_133113](https://user-images.githubusercontent.com/110705397/233699174-0bc12c23-27de-4fcc-9f34-9763439a16ff.jpg)





![Screenshot_20230421_133304_Samsung Health](https://user-images.githubusercontent.com/110705397/233699482-8850ef87-9229-441f-8282-01ff82a5c6a0.jpg)

**Comment by appsowner** [comment]
Health Connect not save data for workout.......only step.....
do you have the same problem?.

Thank you

**Comment by hoffmatteo** [comment]
> Hi,
> 
> install app health async and synchronize data between health connect and Samsung connect, view results:
> 
> I/flutter (23505): requested I/flutter (23505): true I/flutter (23505): 2023-04-21 00:00:00.000 I/flutter (23505): 2023-04-21 13:17:03.026382 I/flutter (23505): isDataTypeAvailable HealthDataType.HEART_RATE I/flutter (23505): true I/flutter (23505): Datos :3
> 
> view image ![Screenshot_20230421_133113](https://user-images.githubusercontent.com/110705397/233699174-0bc12c23-27de-4fcc-9f34-9763439a16ff.jpg)
> 
> ![Screenshot_20230421_133304_Samsung Health](https://user-images.githubusercontent.com/110705397/233699482-8850ef87-9229-441f-8282-01ff82a5c6a0.jpg)



> Hi,
> 
> install app health async and synchronize data between health connect and Samsung connect, view results:
> 
> I/flutter (23505): requested I/flutter (23505): true I/flutter (23505): 2023-04-21 00:00:00.000 I/flutter (23505): 2023-04-21 13:17:03.026382 I/flutter (23505): isDataTypeAvailable HealthDataType.HEART_RATE I/flutter (23505): true I/flutter (23505): Datos :3
> 
> view image ![Screenshot_20230421_133113](https://user-images.githubusercontent.com/110705397/233699174-0bc12c23-27de-4fcc-9f34-9763439a16ff.jpg)
> 
> ![Screenshot_20230421_133304_Samsung Health](https://user-images.githubusercontent.com/110705397/233699482-8850ef87-9229-441f-8282-01ff82a5c6a0.jpg)

As I understand this means that it is working correctly now, so I will close this issue.

For your problem with workouts, please open a new issue!
