### ISSUE TITLE
There was an error getting the workout data!

### ISSUE THREAD

**Issue by fitterfly-parth** [cph-cachet/flutter-plugins#705]
Health SDK version 6.0.0

There was an error getting the workout data!

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Samsung M01
 - OS: Android 10

There was an error getting the workout data!
W/FLUTTER_HEALTH::ERROR( 6306): 4: The user must be signed in to make this API call.
W/FLUTTER_HEALTH::ERROR( 6306): [Ljava.lang.StackTraceElement;@541b2de
W/FLUTTER_HEALTH::ERROR( 6306): There was an error getting the total steps in the interval!
W/FLUTTER_HEALTH::ERROR( 6306): 4: The user must be signed in to make this API call.
W/FLUTTER_HEALTH::ERROR( 6306): [Ljava.lang.StackTraceElement;@438a6d5
W/FLUTTER_HEALTH::ERROR( 6306): There was an error getting the data!
W/FLUTTER_HEALTH::ERROR( 6306): 4: The user must be signed in to make this API call.
W/FLUTTER_HEALTH::ERROR( 6306): [Ljava.lang.StackTraceElement;@cb21eea

Not able to read Workout Data and also total steps in interval.

/Users/user/Desktop/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, 3.8.0-13.0.pre.74, on macOS 13.3.1 22E261 darwin-arm64, locale en-IN)
    • Flutter version 3.8.0-13.0.pre.74 on channel master at /Users/user/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 298d8c76ba (9 weeks ago), 2023-02-16 21:28:30 -0800
    • Engine revision 6e92c0c284
    • Dart version 3.0.0 (build 3.0.0-245.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM M015G (mobile)          • R9ZN605B0KF                          • android-arm    • Android 12 (API 31)
    • iPhone 14 Pro Max (mobile) • 5D7B7F44-1D37-42E6-8CDE-88A03DB75515 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0

**Comment by malik19995** [comment]
I am getting this same issue. The only data available is the active calories burnt data. 

Getting this same issue for Workout data and Steps data. Both with health.getStepsInInterval method and HealthDataType.STEPS method. 

Logs attached.. 

<img width="824" alt="Screenshot 2023-04-25 at 5 32 04 AM" src="https://user-images.githubusercontent.com/46687299/234146147-9bc1dcb0-0e30-453a-90ad-315a852fb664.png">

**Comment by malik19995** [comment]
Is the Google Auth Sign-In a requirement for getting the workout and steps data? I see googleSignInAccount linked in kotlin code for the data. 

I'm currently using email/password authentication within my application and the google auth is not enabled for users. Can this be an issue? 

@oakmad @fitterfly-parth @ristiisa @Whathecode

**Comment by hoffmatteo** [comment]
Are you using Google Fit or HealthConnect?

**Comment by malik19995** [comment]
It fetches the Steps data and a single call for the Calories Burned data, but won't return any data for the second call with a separate startTime and endTime declaration. 

The error starts coming with 'The user must be signed in to make this API call'.

**Comment by malik19995** [comment]
Ok so I narrowed it down a little, the issue comes from the AndroidManifest permissions, 

In my use-case, I only need Active Calories Burned, Exercise, and Steps from the API. 

But the Health API call crashes without the following permission. 

 ```
<!-- Used by Active Calories Calculation. Health API crashes without these.  -->
    <uses-permission android:name="android.permission.health.READ_DISTANCE"/>

```

The following error is given out (which can be misleading) 😅 

<img width="1050" alt="Screenshot 2023-05-01 at 6 57 43 PM" src="https://user-images.githubusercontent.com/46687299/235463356-c3696e41-2d7d-408f-a3f4-4cfba9173dc8.png">

**Comment by Tejas-gaikwad** [comment]
@malik19995 have you got any solution for it, I am also trying to fetch workout data but it's not giving me any data and showing this errors: W/FLUTTER_HEALTH::ERROR( 5564): There was an error getting the workout data!
W/FLUTTER_HEALTH::ERROR( 5564): 4: The user must be signed in to make this API call .

I am able to get other data properly
Have you got any solution for it.

**Comment by hoffmatteo** [comment]
I tried to reproduce this error, but on my end using the example app, everything works. Is there any other information you can give me, are you ensuring that you use the right permissions, do you have an example app I can run to see the error?

Also, when requesting the permissions in requestAuthorization, are they all granted? 

Also, this issue seems somewhat related: https://github.com/cph-cachet/flutter-plugins/issues/714

**Comment by malik19995** [comment]
The example App ran fine for me as well. 

This problem came when adding the heatlh sdk for only the use-cases mentioned above. If you are using ACTIVE ENERGY BURNED, Steps and Workouts, you'll need to add additional permissions to the AndroidManifest.xml. 

In my case, it was the READ_DISTANCE permission.

**Comment by malik19995** [comment]
@Tejas-gaikwad  Please check your AndroidManifest.xml and add the relevant permissions. 

Debugging the issue, I found that aligning app-level build.gradle with the example app (adding necessary implementations) and updating AndroidManifest with permissions worked well.

I used the elimination technique on the permissions, started with all of them, and eliminated the ones that were irrelevant to my project and did not produce any bug.  

Try adding the READ_DISTANCE permission, I think Workouts uses this under the hood.
