### ISSUE TITLE
 health: 6.0.0 - Authorization Access not granted

### ISSUE THREAD

**Issue by ShizaSiddique** [cph-cachet/flutter-plugins#714]
### Device / Emulator and OS
 - Device: OnePlus7Tpro
 - OS: Android 12

I have tried a lot but still, authorization to access the step data is not granted. Permission.activityRecognition.request() returns permission granted. But request authorization always returns false. 

### Expected behavior
After granted permissions successfully, authorization access should also be granted and Steps data should have been received

### Actual behavior
Request to access activity is granted but doesn't authorize the types i.e STEPS

### Screenshots
<img width="1022" alt="Screenshot 2023-05-02 at 8 32 55 PM" src="https://user-images.githubusercontent.com/40723244/235770662-4f8397cd-9c1f-4754-8644-d747d510b78e.png">

***EDIT
This package is setup correctly because it runs fine on other developers' device and the feature is already in production. But its not running on my device. Any pointers would be appreciated

**Comment by ludovicjamet** [comment]
Same here:
Device Samsung A10
OS: Android 11
Error:  The user must be signed in to make this API call.

Checks:
- Oauth is set with debug SHA1
- Google Fit is installed on the device
- Consent screen setup with test users

**Comment by ShizaSiddique** [comment]
@hoffmatteo im only trying to get the Steps so heres my manifest.xml
<img width="972" alt="Screenshot 2023-05-09 at 2 58 10 PM" src="https://user-images.githubusercontent.com/40723244/237062516-dfb1bb4c-9343-494e-bfe0-986ebad2090b.png">
The point is - its working on few other phones but not working on mine

**Comment by hoffmatteo** [comment]
Did you try adding this permission:
`<uses-permission android:name="android.permission.health.READ_DISTANCE"/>
`

Does this fix the issue?

**Comment by hoffmatteo** [comment]
Closed as stale.
