### ISSUE TITLE
version solving failed incompatiable with intl plugin

### ISSUE THREAD

**Issue by ketanphpdots** [cph-cachet/flutter-plugins#715]
[appname] flutter pub get
Running "flutter pub get" in appname...
Resolving dependencies...
Because health >=5.0.0 depends on intl ^0.17.0 and appname depends on intl ^0.18.1, health >=5.0.0 is forbidden.
So, because appname depends on health ^6.0.0, version solving failed.
pub get failed

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2 22D49 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

pubspec.yaml

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  health: ^6.0.0

**Comment by cachapa** [comment]
As a temporary solution you can add my PR #704 in your pubspec.yaml.
The only change is matching the `intl` package version to the Flutter SDK's.

``` yaml
  health:
    git:
      url: https://github.com/cachapa/flutter-plugins.git
      path: packages/health
```
