### ISSUE TITLE
Does activity_recognition_flutter no longer support the pre-Flutter-1.12 Android projects?

### ISSUE THREAD

**Issue by tc14077** [cph-cachet/flutter-plugins#72]
**Plugin name & version**
 activity_recognition_flutter: ^1.0.3

**Describe the bug**
The static function registerWith(registrar: Registrar) had been removed in this plugin which makes the pre-Flutter-1.12 Android projects fail to register with it. It leads following error: 

> error: cannot find symbol method registerWith(Registrar)

**To Reproduce**
1. Downgrade to Flutter: 1.9.1+hotfix.6
2. import the plugin to the project
3. Build the project

**Actual behavior**

> ActivityRecognitionFlutterPlugin.registerWith(registry.registrarFor("com.example.activity_recognition_flutter.ActivityRecognitionFlutterPlugin"));
>                                     ^
>   symbol:   method registerWith(Registrar)
>   location: class ActivityRecognitionFlutterPlugin
> 1 error
> FAILURE: Build failed with an exception.

**Flutter doctor**
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.37.1)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!

**Comment by thomasnilsson** [comment]
When writing the package it seemed the choice was between supported 1.12 or newer, or older than 1.12, and we chose supporting newer packages. If you know of a way to support both, let us know!

**Comment by tc14077** [comment]
According to the commit c6e5f423571577783d147ff0aad9ec5bc33d2c26, I think the function registerWith(registrar: Registrar) should be kept in order to support the pre-Flutter-1.12 Android projects.
```
  // This static function is optional and equivalent to onAttachedToEngine. It supports the old
  // pre-Flutter-1.12 Android projects. You are encouraged to continue supporting
  // plugin registration via this function while apps migrate to use the new Android APIs
  // post-flutter-1.12 via https://flutter.dev/go/android-project-migration.
  //
  // It is encouraged to share logic between onAttachedToEngine and registerWith to keep
  // them functionally equivalent. Only one of onAttachedToEngine or registerWith will be called
  // depending on the user's project. onAttachedToEngine or registerWith must both be defined
  // in the same class.
  companion object {
    @JvmStatic
    fun registerWith(registrar: Registrar) {
      val channel = MethodChannel(registrar.messenger(), "activity_recognition_flutter")
      channel.setMethodCallHandler(ActivityRecognitionFlutterPlugin())
    }
  }
```
I am sorry that I could not give a better suggestion because I am new to flutter.

**Comment by thomasnilsson** [comment]
Today I had to deal with, what I believe to be the same problem. 
The solution is the following: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
