### ISSUE TITLE
6.0.0  Health - Incompatibility with version   intl: ^0.18.0

### ISSUE THREAD

**Issue by JuanFcoRomero** [cph-cachet/flutter-plugins#726]
Health package for iOs

### Device
 - Device: iPhone 12 Plus
 - OS: iOs 16

### Describe the bug
I integrated the dependency in my project and get this error: 

Resolving dependencies...
Because health >=5.0.0 depends on intl ^0.17.0 and myproject depends on intl ^0.18.0, health >=5.0.0 is forbidden.
So, because myproject depends on health ^6.0.0, version solving failed.
exit code 1

I downgraded the intl to the 0.17.0 version but I have other dependencies depending from that version 0.18.0.

### To Reproduce
Integrate the plugin having intl ^0.18.0 integrated

**Comment by Jason-Sleigh** [comment]
I have the same issue but using health ^6.0.0 depending on intl ^0.17.0 and I need to use intl ^0.18.1 as I have another dependency that needs this. Please update

**Comment by hoffmatteo** [comment]
Fixed in version 7.0.0.
