### ISSUE TITLE
[6.0.0 Health] CocoaPods could not find compatible version

### ISSUE THREAD

**Issue by JuanFcoRomero** [cph-cachet/flutter-plugins#727]
We had this issue when we tried to build the app: 

[!] CocoaPods could not find compatible version for pod "health": 
    In Podfile: 
        health (from '.symlinks/plugins/health/ios')

Specs satisfying the 'health (from '.symlinks/plugins/health/ios') dependency were found, but they required a higher minimum deployment target. 

I'm using Flutter 3.10.1

**Comment by hoffmatteo** [comment]
Does your podfile contains the correct minimum deployment target, which should be platform :ios, '11.0'?

**Comment by JuanFcoRomero** [comment]
> Does your podfile contains the correct minimum deployment target, which should be platform :ios, '11.0'?

Hello, 

I have that commented as a d
<img width="756" alt="jhon" src="https://github.com/cph-cachet/flutter-plugins/assets/30311669/010b7559-37d6-4967-82e0-75d8e3333fdd">
efault on the project.

**Comment by hoffmatteo** [comment]
> > Does your podfile contains the correct minimum deployment target, which should be platform :ios, '11.0'?
> 
> Hello,
> 
> I have that commented as a default on the project.
> 
> <img alt="jhon" width="756" src="https://user-images.githubusercontent.com/30311669/242313066-010b7559-37d6-4967-82e0-75d8e3333fdd.png">

What happens if you comment this in? What is the version of your test device?

**Comment by JuanFcoRomero** [comment]
I did a few test and worked with:

platform :ios, '13.0'

**Comment by JuanFcoRomero** [comment]
Thank you
