### ISSUE TITLE
requestAuthorization() always returns true.

### ISSUE THREAD

**Issue by VinitEncodework** [cph-cachet/flutter-plugins#736]
requestAuthorization() always returns true.

In my code, I have a function called requestAuthorization() which is responsible for requesting authorization from a user. However, I'm experiencing a consistent issue where, regardless of the actual authorization outcome, the function always returns true as the result.

The expected behavior of the requestAuthorization() function is to return true if the authorization is granted and false if it is denied. However, in this case, the function consistently returns true, even when the authorization should be denied.

This issue is causing a problem in my application because I need to accurately determine the authorization status to proceed with the appropriate actions based on user authorization.

I have already tried different scenarios and confirmed that the authorization process itself is working correctly. The issue seems to be specific to the requestAuthorization() function implementation.

I'm seeking assistance in understanding why the requestAuthorization() function always returns true and how I can fix this issue to ensure it returns the correct authorization status based on user input.

Please let me know if you require any additional information or code snippets to help diagnose and resolve the problem.

ISSUE IN IOS DEVICE

this is my code :
`import 'package:flutter/material.dart';
import 'package:health/health.dart';

void main() => runApp(const HealthApp());

class HealthApp extends StatelessWidget {
  const HealthApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "My Health Data",
      home: const HealthDataScreen(),
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData(
          brightness: Brightness.dark,
          scaffoldBackgroundColor: const Color(0xFF101820),
          appBarTheme: const AppBarTheme(color: Color(0xFF101820))),
    );
  }
}

class HealthDataScreen extends StatefulWidget {
  const HealthDataScreen({Key? key}) : super(key: key);

  @override
  _HealthDataScreenState createState() => _HealthDataScreenState();
}

class _HealthDataScreenState extends State<HealthDataScreen> {
  String? heartRate;
  String? bp;
  String? steps;
  String? activeEnergy;

  String? bloodPreSys;
  String? bloodPreDia;

  List<HealthDataPoint> healthData = [];

  HealthFactory health = HealthFactory();

  @override
  void initState() {
    super.initState();
    fetchData();
  }

  /// Fetch data points from the health plugin and show them in the app.
  Future fetchData() async {
    // define the types to get
    final types = [
      HealthDataType.HEART_RATE,
      HealthDataType.BLOOD_PRESSURE_SYSTOLIC,
      HealthDataType.BLOOD_PRESSURE_DIASTOLIC,
      HealthDataType.STEPS,
      HealthDataType.ACTIVE_ENERGY_BURNED,
    ];

    // get data within the last 24 hours
    final now = DateTime.now();
    final yesterday = now.subtract(const Duration(days: 1));

    // requesting access to the data types before reading them
    bool requested = await health.requestAuthorization(types);

    if (requested) {
      try {
        // fetch health data
        healthData = await health.getHealthDataFromTypes(yesterday, now, types);

        if (healthData.isNotEmpty) {
          for (HealthDataPoint h in healthData) {
            if (h.type == HealthDataType.HEART_RATE) {
              heartRate = "${h.value}";
            } else if (h.type == HealthDataType.BLOOD_PRESSURE_SYSTOLIC) {
              bloodPreSys = "${h.value}";
            } else if (h.type == HealthDataType.BLOOD_PRESSURE_DIASTOLIC) {
              bloodPreDia = "${h.value}";
            } else if (h.type == HealthDataType.STEPS) {
              steps = "${h.value}";
            } else if (h.type == HealthDataType.ACTIVE_ENERGY_BURNED) {
              activeEnergy = "${h.value}";
            }
          }
          if (bloodPreSys != "null" && bloodPreDia != "null") {
            bp = "$bloodPreSys / $bloodPreDia mmHg";
          }

          setState(() {});
        }
      } catch (error) {
        print("Exception in getHealthDataFromTypes: $error");
      }

      // filter out duplicates
      healthData = HealthFactory.removeDuplicates(healthData);
    } else {
      print("Authorization not granted");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("My Health Data"),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            Row(
              children: [
                Expanded(
                    child: healthCard(
                        title: "Heart rate",
                        image: "assets/health.png",
                        data: heartRate != "null" ? "$heartRate bpm" : "",
                        color: const Color(0xFF8d7ffa))),
                const SizedBox(
                  width: 10,
                ),
                Expanded(
                    child: healthCard(
                        title: "Blood pressure",
                        data: bp ?? "",
                        image: "assets/blood-pressure.png",
                        color: const Color(0xFF4fd164))),
              ],
            ),
            Row(
              children: [
                Expanded(
                    child: healthCard(
                        title: "Step count",
                        image: "assets/step.png",
                        data: steps ?? "",
                        color: const Color(0xFF2086fd))),
                const SizedBox(
                  width: 10,
                ),
                Expanded(
                    child: healthCard(
                        title: "Energy burned",
                        image: "assets/calories.png",
                        data: activeEnergy != "null" ? "$activeEnergy cal" : "",
                        color: const Color(0xFFf77e7e))),
              ],
            )
          ],
        ),
      ),
    );
  }
}

Widget healthCard(
    {String title = "",
    String data = "",
    Color color = Colors.blue,
    required String image}) {
  return Container(
    height: 240,
    margin: const EdgeInsets.symmetric(vertical: 10),
    padding: const EdgeInsets.symmetric(vertical: 10),
    decoration: BoxDecoration(
        color: color,
        borderRadius: const BorderRadius.all(Radius.circular(20))),
    child: Column(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: [
        Text(title,
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
        Image.asset(image, width: 70),
        Text(data),
      ],
    ),
  );
}`

**Comment by subincdevFiet** [comment]
I had the same problem.

**Comment by hoffmatteo** [comment]
Please note the following: 
As Apple HealthKit will not disclose if READ access has been granted for a data type due to privacy concern, requestAuthorization will return true if the window asking for permission was showed to the user without errors if it is called on iOS with a READ or READ_WRITE access.

**Comment by mobinshaik999** [comment]
This window is opening only once ,
if user don't allow, stills it sends true,  ( I understood that apple doesn't disclose this status )
but is any possibility to open this window whenever we call requestAuthorization

**Comment by hoffmatteo** [comment]
> This window is opening only once , if user don't allow, stills it sends true, ( I understood that apple doesn't disclose this status ) but is any possibility to open this window whenever we call requestAuthorization

No this is not possible, see here: https://developer.apple.com/documentation/healthkit/hkhealthstore/1614152-requestauthorization
"If the user has already chosen to grant or prohibit access to all of the types specified, HealthKit calls the completion without prompting the user."
The user has to change the permissions himself.
