### ISSUE TITLE
[pedometer]: pedometer device no counting 

### ISSUE THREAD

**Issue by AHNHAEMOON** [cph-cachet/flutter-plugins#74]
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.778], locale ko-KR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

device -model:  SM-J530K
android version: 9 
package version : 1.0.0

I applied a sample source
The step count number does not go up.

**Comment by omarsherifs** [comment]
i have the same issue

**Comment by codeledger** [comment]
Be aware that in Android 9 and 10 have additional permissions as documented:

https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition

**Comment by balajiks-dev** [comment]
The step count number does not go up in an iOS device.
Device: iPhone 5
iOS version: 10.3

Is there any solution for this?

**Comment by thomasnilsson** [comment]
> The step count number does not go up in an iOS device.
> Device: iPhone 5
> iOS version: 10.3
> 
> Is there any solution for this?

I don't have access to an iPhone 5 unfortunately - it works on newer iPhones (6s and above). Did you give the application the necessary permissions to track the user's motion?

**Comment by thomasnilsson** [comment]
> Be aware that in Android 9 and 10 have additional permissions for step counting as documented:
> 
> https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition
> 
> Related: #99

This has been fixed (Android only) in version 1.2.5 of the plugin

**Comment by balajiks-dev** [comment]
> > The step count number does not go up in an iOS device.
> > Device: iPhone 5
> > iOS version: 10.3
> > Is there any solution for this?
> 
> I don't have access to an iPhone 5 unfortunately - it works on newer iPhones (6s and above).
> 
> I would need more information to troubleshoot the issue.
> 
> * Did you give the application the necessary permissions and capabilities to track the user's motion?
> * Are you using the newest version of the package?

Yes, I have given all the permission for that (Motion Usage Description)

I' m using the latest version of Pedometer (  pedometer: ^1.2.5)

**Comment by thomasnilsson** [comment]
Ok thanks for clarifying. I will try and replicate the issue on an iOS 10 device.

**Comment by thomasnilsson** [comment]
A new version (2.0.1+1) is out.

I tried it on an iOS 12.4 device: The step count is working fine, but the newly introduced Pedestrian Status does not seem to work. 

Error handling has been introduced now such that you will be informed if the sensor is not available.

**Comment by balajiks-dev** [comment]
Okay and Thanks @thomasnilsson
