### ISSUE TITLE
[Weather 3.0.0] Upgrade http dependency to >=1.0.0

### ISSUE THREAD

**Issue by xRidney** [cph-cachet/flutter-plugins#754]
I have other newest packages using http >=1.0.0 and I can't install them along with the weather package. 
Is possible to upgrade http dependency from 0.13.1 to >=1.0.0?

**Comment by hoffmatteo** [comment]
Fixed in version 4.0.0 of weather

**Comment by xRidney** [comment]
@hoffmatteo Thanks for the feedback. When is the planned release of version 4.0.0 of Weather?

**Comment by hoffmatteo** [comment]
> @hoffmatteo Thanks for the feedback. When is the planned release of version 4.0.0 of Weather?

@xRidney I am sorry I mistyped, this was included in version 3.1.0 of weather, and is thus already released.
