### ISSUE TITLE
Crash in Android - Release Mode

### ISSUE THREAD

**Issue by alihassan711** [cph-cachet/flutter-plugins#760]
Flutter Plugin
health: ^4.1.1

Device:
SM A127F (Android 13 & API 33)

Issue:
I have an app that tracks users' health via Goggle FIT. I have correctly set up all the OAuth and I am able to see the Google mail selector pop-ups while connecting it shows popups again and again for connection.

The app crashes with the following error

Video leading to the crash - [Android Crash Video](https://drive.google.com/file/d/1i4CRacHyC9_Cj-eLeg2IXz7bPZmSBJF5/view?usp=sharing)

Logs:
D/FLUTTER_HEALTH(27823): Access Denied!
D/FLUTTER_HEALTH(27823): Access Denied!
E/AndroidRuntime(27823): FATAL EXCEPTION: main
E/AndroidRuntime(27823): Process: com.idzyns.nf1app, PID: 27823
E/AndroidRuntime(27823): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=0, data=Intent { (has extras) }} to activity {com.idzyns.nf1app/com.idzyns.nf1app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(27823):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5994)
E/AndroidRuntime(27823):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
E/AndroidRuntime(27823):        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(27823):        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(27823):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27823):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27823):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(27823):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27823):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(27823):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(27823):        at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(27823):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27823):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(27823):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(27823): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(27823):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(Unknown Source:35)
E/AndroidRuntime(27823):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(Unknown Source:14)
E/AndroidRuntime(27823):        at cachet.plugins.health.HealthPlugin.onActivityResult(Unknown Source:37)
E/AndroidRuntime(27823):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(Unknown Source:25)
E/AndroidRuntime(27823):        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(Unknown Source:13)
E/AndroidRuntime(27823):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(Unknown Source:51)
E/AndroidRuntime(27823):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(Unknown Source:10)
E/AndroidRuntime(27823):        at android.app.Activity.dispatchActivityResult(Activity.java:8951)
E/AndroidRuntime(27823):        at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
E/AndroidRuntime(27823):        ... 13 more

Also Attaching flutter doctor -v info:
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6.7 21G651 darwin-x64, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/alburraqtech/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (10 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/alburraqtech/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • SM A127F (mobile) • R58RC2E4DKA • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 12.6.7 21G651 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by hoffmatteo** [comment]
Please try if this issue persists with the newest version of health, 7.0.1.
