### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

### ISSUE THREAD

**Issue by ptmcode** [cph-cachet/flutter-plugins#773]
D/AndroidRuntime( 7198): Shutting down VM
E/AndroidRuntime( 7198): FATAL EXCEPTION: main
E/AndroidRuntime( 7198): Process: com.example.test_get_app_notification, PID: 7198
E/AndroidRuntime( 7198): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
E/AndroidRuntime( 7198): 	at dk.cachet.notifications.NotificationListener.onNotificationPosted(NotificationListener.java:41)
E/AndroidRuntime( 7198): 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:456)
E/AndroidRuntime( 7198): 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2352)
E/AndroidRuntime( 7198): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7198): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 7198): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 7198): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime( 7198): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7198): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 7198): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process ( 7198): Sending signal. PID: 7198 SIG: 9****

**Comment by hoffmatteo** [comment]
Please provide more information on what steps you took to receive this error.

**Comment by candraprasetya** [comment]
i have same problem, my apps works properly, but after get some notification, my app crashed and debug console tell "java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference"

**Comment by hoffmatteo** [comment]
Hi @candraprasetya , please open your own issue with more information on the circumstances, otherwise I am unable to replicate it.
