### ISSUE TITLE
[Health 7.0.1] Load Workout Data / User must be signed in to make API Call

### ISSUE THREAD

**Issue by Felix-Fab** [cph-cachet/flutter-plugins#775]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Android Pixel 4, 6, 3a
 - OS: Api 34 & 31

### Describe the bug
I am authorized and the permissions are queried. However, the error "User must be signed in to make API Call" comes up every time

When loading the steps, everything works normally

### To Reproduce
Load Activity/Workout Data

### Expected behavior
Activity/Workout Data returns

### Actual behavior
What did happen? Include stack traces and exception print-outs.

### Screenshots
![image](https://github.com/cph-cachet/flutter-plugins/assets/69577380/44ad47d6-f82a-403a-83ed-746bb4a023c7)
![image](https://github.com/cph-cachet/flutter-plugins/assets/69577380/701a638e-a03f-4d77-8b6c-1c9b8191ef92)

### Flutter doctor 
![image](https://github.com/cph-cachet/flutter-plugins/assets/69577380/692f3707-4cce-4526-b2c3-f11bff2769dc)

**Comment by hoffmatteo** [comment]
Please validate your AndroidManifest.xml to ensure that it contains all the correct permissions - feel free to test it out using the list of permissions from the example app, if the issue still persists please let me know.

**Comment by hoffmatteo** [comment]
Closed as stale.
