### ISSUE TITLE
audio_streamer how to produce audio from the stream

### ISSUE THREAD

**Issue by RizanPSTU** [cph-cachet/flutter-plugins#78]
How to produce audio from list<double>

**Comment by thomasnilsson** [comment]
If you want to produce an audio file check out other plugins such as https://pub.dev/packages/audio_recorder

**Comment by RizanPSTU** [comment]
Can you share an example code? audio_recorder with audio_streamer?

**Comment by thomasnilsson** [comment]
You should not use this plugin (`audio_streamer`) if you want to save the audio as a file :)

**Comment by RizanPSTU** [comment]
And can this be used like sending the audio stream data to socket IO nodejs backend end user can play the audio?

**Comment by RizanPSTU** [comment]
No I don't want to save the file. I want to play audio from list<double> stream.

**Comment by RizanPSTU** [comment]
Can I convert this list double to Uint8List is this possible?

**Comment by RizanPSTU** [comment]
audio data to sound stream. Like I can hear.

**Comment by thomasnilsson** [comment]
Some of the audio data has negative values, so you probably cannot do this with an unsigned integer, instead, I would use int16. 

You would have to convert it yourself, for example by multiplying a given double by the maximum value allowed by your format (i.e 2^15 for int16).

**Comment by RizanPSTU** [comment]
Is there a way to get sound from list double?

**Comment by thomasnilsson** [comment]
Probably, but this is beyond this plugin.

**Comment by tang158152** [comment]
@thomasnilsson We want to develop a spectrogram through the audio data returned by the microphone, but only return data 2-3 times a second, which seems to be not very friendly to the development of spectrogram, how can we return data once in 0.1 seconds,
