### ISSUE TITLE
HEALTH 7.01

### ISSUE THREAD

**Issue by AvinashKasukurthi** [cph-cachet/flutter-plugins#785]
**Cannot able to get data from getHealthDataFromTypes**

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: [e.g. Redmi - M2101k7BI]
 - OS: [e.g. Android 12]

**NB: Bugs pertaining to old devices/OS versions will likely not be fixed.**
* For iOS only the latest OS is supported. 
* For Android, see [the OS versions for which Google support security fixes](https://en.wikipedia.org/wiki/Android_version_history)**

### Describe the bug
Cannot able to get the heart rate

    types = [
      HealthDataType.STEPS,
      HealthDataType.BLOOD_GLUCOSE,
      HealthDataType.HEART_RATE,
    ];
    var permissions = [
      HealthDataAccess.READ,
      HealthDataAccess.READ_WRITE,
      HealthDataAccess.READ_WRITE,
    ];
    final res =
        await health.requestAuthorization(types, permissions: permissions);
    print("Requested: $res");

    var midnight = DateTime(now.year, now.month, now.day);
    int? steps = await health.getTotalStepsInInterval(midnight, now);
    var heartPts = await health.getHealthDataFromTypes(
      now.subtract(const Duration(days: 1)),
      now,
      [HealthDataType.HEART_RATE, HealthDataType.BLOOD_GLUCOSE],
    );

    print("Steps: $steps");
    print("HeartPts: $heartPts");

**Comment by hoffmatteo** [comment]
I tested your code in the example app and everything works as expected. Please verify that you have all the necessary permissions in your AndroidManifest.xml, otherwise please let me know what error appears.

**Comment by AvinashKasukurthi** [comment]
There was no error I am getting empty list.

**Comment by hoffmatteo** [comment]
Closed as issue seems fixed.
