### ISSUE TITLE
Access Denied for Health Connect

### ISSUE THREAD

**Issue by endmr11** [cph-cachet/flutter-plugins#788]
Everything that needs to be defined in AndroidManifest is defined. There is no problem in the iOS application, but I get such an error on android.
->>> Access Denied (to Health Connect) due to too many requests!
I'm also trying a real android device. The Health Connect app is installed.
sample codes:

final health = HealthFactory(useHealthConnectIfAvailable: true);
    final now = DateTime.now();
    final midnight = DateTime(now.year, now.month, now.day);
    try {
      final types = [HealthDataType.STEPS];
      final permissions = [HealthDataAccess.READ];
      final isGranted = await Permission.activityRecognition.isGranted;
      print("RESULT >>1 $isGranted");
      if (!isGranted) {
        await Permission.activityRecognition.request();
      }
      final requested = await health.requestAuthorization(types, permissions: permissions);
      final hasPermission = await health.hasPermissions(types);
      print("RESULT >>2 $requested,$hasPermission,${health.useHealthConnectIfAvailable}");
      if (requested) {
        final result = await health.getTotalStepsInInterval(midnight, now);
        print("RESULT >>3 $result");
      }
    } catch (e) {
      print("RESULT >> error $e");
    }

**Comment by hoffmatteo** [comment]
Hi!
The error "->>> Access Denied (to Health Connect) due to too many requests!" appears when HealthConnect received too many requests to authorize and thus blocks the following requests. Please delete and reinstall both HealthConnect and the application to reset this. Since the issue is a feature of Android, the plugin can only reflect the behaviour.

Please let me know if this solves the issue.

**Comment by Malte2036** [comment]
I had the same error, but with 
```
types = [
  HealthDataType.STEPS,
  HealthDataType.WORKOUT
];
```

I fixed it by adding  

```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />

    <!-- Permissions for new android API (Health Connect) -->
    <uses-permission android:name="android.permission.health.READ_STEPS" />
    <uses-permission android:name="android.permission.health.READ_EXERCISE" />
    <uses-permission android:name="android.permission.health.READ_SPEED" />
    <uses-permission android:name="android.permission.health.READ_DISTANCE" />
    <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED" />
    <uses-permission android:name="android.permission.health.READ_ACTIVE_CALORIES_BURNED" />
```

to the `AndroidManifest.xml`. 

And I was missing `await Permission.location.request();`. 
I only had `await Permission.activityRecognition.request();`

**Comment by hagen00** [comment]
Having the same problem. I've uninstalled the app, uninstalled Health Connect and have the above code. 

Still getting `Access Denied (to Health Connect) due to too many requests!`

Trying with
```
HealthDataType.STEPS,
HealthDataType.WORKOUT
```
and pretty sure my AndroidManifest in main is correct...

**Comment by mobinshaik999** [comment]
Same here,  
Error : Access Denied , too many requests

**Comment by Abdullah123op** [comment]
Same issue i getting is there any solution for it
Access Denied (to Health Connect) due to too many requests!

**Comment by hoffmatteo** [comment]
> So for me at least, this fixes the problem. There is no mention of this in the README here: https://pub.dev/packages/health. Should these instructions be added to the documentation?

This is in fact mentioned in the README, under Health Connect (Android option 2):

Health Connect requires the following lines in the AndroidManifest.xml file (also seen in the example app):

<queries>
    <package android:name="com.google.android.apps.healthdata" />
        <intent>
            <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
        </intent>
</queries>

**Comment by hoffmatteo** [comment]
Seems like this is an issue of an incomplete AndroidManifest.xml, please verify if this is the case, otherwise please create a new issue when you are sure it is not.
