### ISSUE TITLE
[noise_meter]: Low pass filter to detect human voice in noise_meter

### ISSUE THREAD

**Issue by JPiris88** [cph-cachet/flutter-plugins#80]
**Plugin name & version**
noise_meter

**Enhancement request**
Apply low pass filter to leave the lower tones well alone, such as the human voice. Maybe a new public property in NoiseReading? This article can help:

"Detecting When A User Blows Into The Mic" https://www.cnblogs.com/pengyingh/articles/2536537.html

**Expected behavior**
I would like to detect when someone speaks into the microphone

**Comment by thomasnilsson** [comment]
This is a good idea for a new plugin, but doesn't fit the idea of the`noise_meter` plugin. We will have a look in July.
