### ISSUE TITLE
 Failed to handle method call

### ISSUE THREAD

**Issue by iresolveservices** [cph-cachet/flutter-plugins#802]
E/MethodChannel#flutter_health( 3665): Failed to handle method call
E/MethodChannel#flutter_health( 3665): java.lang.NullPointerException
E/MethodChannel#flutter_health( 3665): 	at cachet.plugins.health.HealthPlugin.hasPermissionsHC(HealthPlugin.kt:1456)
E/MethodChannel#flutter_health( 3665): 	at cachet.plugins.health.HealthPlugin.hasPermissions(HealthPlugin.kt:1203)
E/MethodChannel#flutter_health( 3665): 	at cachet.plugins.health.HealthPlugin.onMethodCall(HealthPlugin.kt:1395)
E/MethodChannel#flutter_health( 3665): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_health( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_health( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_health( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter_health( 3665): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter_health( 3665): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_health( 3665): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter_health( 3665): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter_health( 3665): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/MethodChannel#flutter_health( 3665): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_health( 3665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#flutter_health( 3665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 3665): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
E/flutter ( 3665): 	at cachet.plugins.health.HealthPlugin.hasPermissionsHC(HealthPlugin.kt:1456)
E/flutter ( 3665): 	at cachet.plugins.health.HealthPlugin.hasPermissions(HealthPlugin.kt:1203)
E/flutter ( 3665): 	at cachet.plugins.health.HealthPlugin.onMethodCall(HealthPlugin.kt:1395)
E/flutter ( 3665): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 3665): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 3665): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 3665): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 3665): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 3665): 	at android.os.Looper.loop(Looper.java:313)
E/flutter ( 3665): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/flutter ( 3665): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter ( 3665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 3665): )
E/flutter ( 3665): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 3665): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 3665): <asynchronous suspension>
E/flutter ( 3665): #2      HealthFactory.hasPermissions (package:health/src/health_factory.dart:75:12)
E/flutter ( 3665): <asynchronous suspension>

**Comment by hoffmatteo** [comment]
Can you explain your steps before the error appeared so I can replicate it?
