### ISSUE TITLE
Getters for min, max and avg in noise_meter

### ISSUE THREAD

**Issue by JPiris88** [cph-cachet/flutter-plugins#81]
**Plugin name & version**
noise_meter

**Enhancement request**
Add public properties for "min", "max" and "avg" in "NoiseReading" class.

**Expected behavior**
Need to get the requested properties

**Actual behavior**
Actually is only possible to get the decibels

**Comment by thomasnilsson** [comment]
This has been fixed in the latest version. https://pub.dev/documentation/noise_meter/latest/noise_meter/NoiseReading-class.html

However getting the minimum value is not very useful information, since with a high sample rate it will almost always be 0 (in terms of absolute value)

**Comment by JPiris88** [comment]
Thank you!
