### ISSUE TITLE
Health Data Fetching Returns Limited Results health: ^8.0.0 (with health connect enabled)

### ISSUE THREAD

**Issue by simplayy** [cph-cachet/flutter-plugins#833]
In the current implementation of the health data fetching function, the returned results are limited to a maximum of 1000 data points, even when the actual number of data points is much higher. 
This issue occurs when fetching health data from the last 7 days using the getHealthDataFromTypes function. 
The expected behavior is that the function should return all available data points within the specified date range. 
```
// fetch health data from the last 7 days
List<HealthDataPoint> healthData = await health.getHealthDataFromTypes(now.subtract(Duration(days: 7)), now, types);
print("Health data length: ${healthData.length}");
```

In the above code snippet, healthData.length returns 1000, even when the actual number of data points is higher.

### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: POCO F3
 - OS: Android 13

**Comment by armanso** [comment]
Hey @simplayy, we faced the same issue and figured out that there was a missing implementation at the Health Connect level. This has been addressed in the following pull request: https://github.com/cph-cachet/flutter-plugins/pull/862.
