### ISSUE TITLE
[movisens]: Movisens does not work

### ISSUE THREAD

**Issue by attex** [cph-cachet/flutter-plugins#85]
Hi, 

i am trying to connect my app with a movisens sensor and was trying your sample project. 
There is no error. But there is also no data received from the sensor. 

My log:

`
D/FlutterActivityAndFragmentDelegate(31169): Executing Dart entrypoint: main, and sending initial route: /
D/PermissionActivity(31169): {age=25, sensor_address=00:07:80:78xxxx, height=190, gender=Gender.male, sensor_location=SensorLocation.chest, sensor_name=Sensor 02655, weight=90}
D/HandlerBluetoothStart(31169): {age=25, sensor_address=00:07:80:78xxxx, height=190, gender=Gender.male, sensor_location=SensorLocation.chest, sensor_name=Sensor 02655, weight=90}`

I got the adress with an app called ble scanner. 

Any help?

**Comment by devhci** [comment]
Hi @attex,

There is not much log here so its lil difficult to see what's going on.  The sensor address  you posted "00:07:80:78xxxx" does not seems to be right.   Are you passing `00:07:80:78xxxx` or is it that  you just xxxx it in the message ?

Regards
Devender

**Comment by attex** [comment]
It is just xxx in the message, i get the IP with a BLE Scanner. 

Thats the log i get: 

` Built build\app\outputs\apk\debug\app-debug.apk.
D/PermissionActivity( 9424): {age=25, sensor_address=00:07:80:78:63:A5, height=180, gender=Gender.male, sensor_location=SensorLocation.chest, sensor_name=Sensor 02655, weight=100}
I/Timeline( 9424): Timeline: Activity_launch_request time:34698386 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
D/HandlerBluetoothStart( 9424): {age=25, sensor_address=00:07:80:78:63:A5, height=180, gender=Gender.male, sensor_location=SensorLocation.chest, sensor_name=Sensor 02655, weight=100}`

Nothing else is happening

**Comment by devhci** [comment]
BTW It currently  works ONLY for Android. 
Are u testing it on Android or iOS? Without log it would be difficult to know whats going on. If you want me to look into it pls share the git repo so that I can replicate and see whats going on.

**Comment by attex** [comment]
@devhci thanks. Yes I know that its only available for Android. 

https://github.com/attex/movisens 

Here is the repository.

**Comment by attex** [comment]
Hi @devhci did you have time to take a look at this?
