### ISSUE TITLE
[noise_meter]: Mic recoder closed when other player app opened, with noise_meter

### ISSUE THREAD

**Issue by zxl777** [cph-cachet/flutter-plugins#86]
Turn on the mic, then the Up-Left mic icon show red.

Open other player app, The mic icon gone.

**Comment by zxl777** [comment]
Maybe using AVAudioSession?

**Comment by thomasnilsson** [comment]
Will look into this issue soon

**Comment by thomasnilsson** [comment]
I have almost managed to solve the issue:

The AVAudioSession gets interrupted if another media player needs to use it while it is recording. If this happens then the interruption should be handled correctly.

**Comment by thomasnilsson** [comment]
Fixed in NoiseMeter version 2.0.0 and AudioStreamer 1.3.0

Thanks for the issue, it was a tough one to crack!
