### ISSUE TITLE
notifications v 0.0.2

### ISSUE THREAD

**Issue by markflarup** [cph-cachet/flutter-plugins#9]
I tried to implement the [notifications](https://pub.dartlang.org/packages/notifications) package as a dependency in a Flutter project and followed the sparse documentation provided in the ReadMe. I might have the wrong expectation for this dependency, but to my surprise I am no longer presented with the notification when the application is in the background or terminated.
I am receiving the notifications as the content is printed in my terminal. Furthermore, I can see my app is highlighting the desired card (the payload of the notification contains a id to act upon).

Depending on whether this is the intended behaviour or a feature that needs to be implemented I would ask you to update the ReadMe and clarify your intension with this plugin 😊

**Comment by KingDarBoja** [comment]
I have implemented the notifications package in my own Flutter project and so far the notifications are displayed at the terminal when the app is running (Foreground and Background) but not while it is terminated. If there is something I am missing to make it work while the app is closed, I would be pleased unless the intended behaviour is only while the app is open. 

Looking forward for this topic.
Cheers! 👍

**Comment by thomasnilsson** [comment]
> I have implemented the notifications package in my own Flutter project and so far the notifications are displayed at the terminal when the app is running (Foreground and Background) but not while it is terminated. If there is something I am missing to make it work while the app is closed, I would be pleased unless the intended behaviour is only while the app is open.
> 
> Looking forward for this topic.
> Cheers! 👍

If I understand you correctly, you are asking if an app which uses the plugin can track notifications, even though it is not running, i.e. has been terminated? I don't think that is possible, but if you have an example where this works, ex another plugin, feel free to post it here

**Comment by KingDarBoja** [comment]
You are right, it is not possible, maybe I wrote it wrong and wanted to capture all notifications while the app was running on background but I think it does work already so no problem.

**Comment by thomasnilsson** [comment]
See notifications 1.0.0
