### ISSUE TITLE
Plugin Behaves very odd in ios sometimes

### ISSUE THREAD

**Issue by krupeshxebia** [cph-cachet/flutter-plugins#90]
Your last update broke our release code, we were using old version 1.0.0 and it was no more working. Latest version (1.2.0) claims in change logs that plugin returns steps since last boot in ios. This is not always the case, very rarely it starts bringing value from zero all of sudden. This is crashing our app store release app sometimes.

**Comment by thomasnilsson** [comment]
Interesting, do you have more info on when it behaves weird on iOS? We haven't had that experience yet.

The old version of the plugin did not have the same behavior on iOS and Android, and it was therefore changed.

**Comment by krupeshxebia** [comment]
Hi @thomasnilsson, I would suggest you to just revisit package code and help make sure that iOS and Android behaviour is same always. sometimes steps are getting reset to 0 and sent out via package. If you do revisit the code and fix, please reply back here. For time being if required, mark this issue closed.

**Comment by thomasnilsson** [comment]
Version 2.0.0 of pedometer has been released. Please make a new issue if this issue persists :)
