### ISSUE TITLE
Health - id of data points?

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#93]
**Plugin name & version**
`health`

**Describe the issue**

Does Apple Health / Google Fit provide a unique ID for their health data points?

I would be useful to know when collecting data if you have already collected this data -- i.e. that you keep track on the uniqeness of a health data point. Otherwise you might end up collecting e.g. the same 10 steps twice, resulting in 20 rather than 10 steps...

Can you extend the `HealthDataPoint` class with this?

**Comment by thomasnilsson** [comment]
Implemented in Health version 1.1.0
