### ISSUE TITLE
[Health] crash in SwiftHealthPlugin.getData

### ISSUE THREAD

**Issue by ristiisa** [cph-cachet/flutter-plugins#94]
**Plugin name & version**
health: 1.0.2

**Describe the bug**
Frequent crashes. 

**To Reproduce**
Use plugin while the screen is locked.

**Screenshots**
![image](https://user-images.githubusercontent.com/514571/82820007-0bee0a80-9eaa-11ea-8bad-7c5911cad921.png)
![image](https://user-images.githubusercontent.com/514571/82820041-20ca9e00-9eaa-11ea-9d0e-c44422b61dbb.png)

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.17.1 at /Users/silver/flutter
    • Framework revision f7a6a7906b (13 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
```

**Smartphone(s) / Emulator**
iPhone 11 iOS 13.4.1

**Additional context**
&#35;&#8203;8	0x1042cee0c in partial apply for closure &#35;&#8203;1 in SwiftHealthPlugin.getData(call:result:) at ~/.pub-cache/hosted/pub.dartlang.org/health-1.0.2/ios/Classes/SwiftHealthPlugin.swift:103

**Comment by ristiisa** [comment]
I think this happens if health data is requested when the device is locked

**Comment by ristiisa** [comment]
A more detailed error message:

```
Unsupported value: Error Domain=com.apple.healthkit Code=6 "Protected health data is inaccessible" UserInfo={NSLocalizedDescription=Protected health data is inaccessible} of type NSError
*** Assertion failure in -[FlutterStandardWriter writeValue:], ../../flutter/shell/platform/darwin/common/framework/Source/FlutterStandardCodec.mm:330
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x1ae9d0164 0x1ae6e4c1c 0x1ae8ccf48 0x1aed12528 0x102d0dd8c 0x102d0e570 0x102d0b3a8 0x104e76314 0x104e78718 0x104e79944 0x1ae66eec4 0x1ae67033c 0x1ae67685c 0x1ae6772c4 0x1ae680928 0x1ae6d7714 0x1ae6dd9c8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ristiisa** [comment]
It seems that the cause of the crash is supplying Error object as a value to FlutterError.details

**Comment by thomasnilsson** [comment]
Will look into this

**Comment by thomasnilsson** [comment]
It would seem that while the phone is locked, Apple Health data is encrypted and can therefore not be read.

https://stackoverflow.com/questions/30361033/healthkit-data-inaccessible-in-background

**Comment by thomasnilsson** [comment]
I'd say this is intended behavior. Your app should not be crashing; we catch errors inside the plugin before they arrive on your end. Please use the newest version of the plugin (2.0.1 or newer) and make a new issue if this behavior persists; I have been unable to recreate a crash.
