### ISSUE TITLE
[audio_streamer]: How to change default sampleRate in plugin audio_streamer

### ISSUE THREAD

**Issue by hibernate2011** [cph-cachet/flutter-plugins#95]
The default sampleRate is 44,100 Hz  of the plugin, i need change it
I have changed it in Android plugin source code, but I don't know how on iOS, the swift code in [here](https://github.com/cph-cachet/flutter-plugins/blob/master/packages/audio_streamer/ios/Classes/SwiftAudioStreamerPlugin.swift)
Can anyone help me ? 
 Is it possible add the feature to the plugin ?  @thomasnilsson

**Comment by KingDarBoja** [comment]
Would be easy to implement, some getter/setter :)

**Comment by thomasnilsson** [comment]
Will look into this when we get the time :)

**Comment by aalex** [comment]
I would be interested in this feature too.

**Comment by aalex** [comment]
For audio detection, we typically need to increase the sample rate to 48000 Hz or more in order to detect lower frequencies.

**Comment by HIHIQY1** [comment]
Any update on this issue?
