### ISSUE TITLE
[activity_recognition]: Activity recognition in background

### ISSUE THREAD

**Issue by vasiachess** [cph-cachet/flutter-plugins#96]
**Plugin name & version**
activity_recognition_flutter 1.2.0

**Describe the bug**
I am trying to use Activity recognition in the background. I am using for it plugin workmanager: ^0.2.2. but get the error. Is there a way to use activity_recognition_flutter plugin in the background?

**To Reproduce**
My code from the background task:

        ActivityRecognition.activityUpdates().listen((event) {
          print("Your phone is to ${event.confidence}% ${event.type}!");
        });

**Expected behavior**
Get activity event in the background

**Actual behavior**
Get this error:
I/flutter (21074): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (21074): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter (21074): activity_recognition/activityUpdates:
I/flutter (21074): MissingPluginException(No implementation found for method listen on channel
I/flutter (21074): activity_recognition/activityUpdates)
I/flutter (21074): 
I/flutter (21074): When the exception was thrown, this was the stack:
I/flutter (21074): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (21074): <asynchronous suspension>
I/flutter (21074): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (21074): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
I/flutter (21074): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
I/flutter (21074): #8      _ActivityChannel.startActivityUpdates (package:activity_recognition_flutter/channel/activity_channel.dart:24:10)
I/flutter (21074): #9      new _ActivityChannel (package:activity_recognition_flutter/channel/activity_channel.dart:16:42)
I/flutter (21074): #10     ActivityRecognition._activityChannel (package:activity_recognition_flutter/activity_recognition_flutter.dart:17:35)
I/flutter (21074): #11     ActivityRecognition._activityChannel (package:activity_recognition_flutter/activity_recognition_flutter.dart:17:16)
I/flutter (21074): #12     ActivityRecognition.activityUpdates (package:activity_recognition_flutter/activity_recognition_flutter.dart:15:48)
I/flutter (21074): #13     callbackDispatcher.<anonymous closure> (package:bacon/ui/screens/feed_screen.dart:77:29)
I/flutter (21074): (elided 17 frames from dart:async)
I/flutter (21074): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (21074): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startActivityUpdates on channel activity_recognition/activities)
E/flutter (21074): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (21074): <asynchronous suspension>
E/flutter (21074): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (21074): #2      _ActivityChannel.startActivityUpdates (package:activity_recognition_flutter/channel/activity_channel.dart:26:14)
E/flutter (21074): #3      new _ActivityChannel (package:activity_recognition_flutter/channel/activity_channel.dart:16:42)
E/flutter (21074): #4      ActivityRecognition._activityChannel (package:activity_recognition_flutter/activity_recognition_flutter.dart:17:35)
E/flutter (21074): #5      ActivityRecognition._activityChannel (package:activity_recognition_flutter/activity_recognition_flutter.dart:17:16)
E/flutter (21074): #6      ActivityRecognition.activityUpdates (package:activity_recognition_flutter/activity_recognition_flutter.dart:15:48)
E/flutter (21074): #7      callbackDispatcher.<anonymous closure> (package:bacon/ui/screens/feed_screen.dart:77:29)
E/flutter (21074): #8      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (21074): #9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (21074): #10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (21074): #11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (21074): #12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (21074): #13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (21074): #14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (21074): #15     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (21074): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (21074): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (21074): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (21074): #19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (21074): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by georgeraveen** [comment]
I too have this problem, any solutions?

**Comment by karanm4797** [comment]
I also have an issues running it

**Comment by thomasnilsson** [comment]
I have been trying to manually implement this in a native app, and it does not seem like it is possible to perform activity recognition in the background. 

I am going to leave this issue open, in case someone finds a solution.

**Comment by georgeraveen** [comment]
Also I have been trying to use screen_state plugin in the background, but it's also the same. May I know whether there is any possibility to run screen_state plugin background? @thomasnilsson

**Comment by thomasnilsson** [comment]
> Also I have been trying to use screen_state plugin in the background, but it's also the same. May I know whether there is any possibility to run screen_state plugin background? @thomasnilsson

Screen State does work in the background. Do you mean while the app is closed? Also, please make a new issue

**Comment by georgeraveen** [comment]
> > Also I have been trying to use screen_state plugin in the background, but it's also the same. May I know whether there is any possibility to run screen_state plugin background? @thomasnilsson
> 
> Screen State does work in the background. Do you mean while the app is closed? Also, please make a new issue

while the app is open or in the recent apps section, works well. (Android)
But after the app is terminated, intents won't trigger when the screen on /off happens.
Also, I'll create a new issue
thanks.

**Comment by johanlantz** [comment]
IIRC the timer based ActivityRecognition does not work after Android 8. 

The activity transition API works well on vanilla Android builds, I am running it on Android 11 with my Pixel device. You do need to register the listener when the app is in foreground but after that it generally works ok (until you reboot the device).

**Comment by mvolpato** [comment]
> I have been trying to manually implement this in a native app, and it does not seem like it is possible to perform activity recognition in the background on Android. For iOS it works without issues.
> 
> I am going to leave this issue open, in case someone finds a solution.

Hi, I do not know much about Android development. Is [this video](https://www.youtube.com/watch?v=11_FCqJDAEA) showing Activity recognition working in the background?

**Comment by thomasnilsson** [comment]
I made some progress on this issue; running a foreground service with notifications can keep the activity recognition active. Will push something soon, hopefully.

**Comment by thomasnilsson** [comment]
Solved in version 2.0.0
