### ISSUE TITLE
android.os.RemoteException: Request rejected. Rate limited request quota has been exceeded. Please wait until quota has replenished before making further requests.

### ISSUE THREAD

**Issue by Naeem-Qizill** [cph-cachet/flutter-plugins#973]
android.os.RemoteException: Request rejected. **Rate limited request quota has been exceeded**. Please wait until quota has replenished before making further requests.
E/AndroidRuntime(12254): 	at androidx.health.connect.client.impl.HealthConnectClientImpl.getGrantedPermissions(HealthConnectClientImpl.kt:308)
E/AndroidRuntime(12254): 	at androidx.health.connect.client.impl.HealthConnectClientImpl$getGrantedPermissions$1.invokeSuspend(Unknown Source:14)
E/AndroidRuntime(12254): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(12254): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(12254): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(12254): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12254): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(12254): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(12254): 	at android.app.ActivityThread.main(ActivityThread.java:8319)
E/AndroidRuntime(12254): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/AndroidRuntime(12254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
E/AndroidRuntime(12254): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4e65eb1, **Dispatchers.Main]**

**after this error app crashes**

**Comment by Vrushti24** [comment]
any updates on this issue ?

**Comment by WingCH** [comment]
any updates on this issue ?

**Comment by SlimShadyIAm** [comment]
Apologies for the late response.

Tracking this in #1028.
