### ISSUE TITLE
I can't run as release mode on Android

### ISSUE THREAD

**Issue by matheus7mm** [cph-cachet/flutter-plugins#98]
**Plugin name & version**
Which of the CACHET Flutter plugins is this issue related to and what is the version number.
pedometer 1.2.0
**Describe the bug**
When I use the command like: flutter run -d myDeviceId --release I've got the following error:
FAILURE: Build failed with an exception.

* Where:

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > AndroidX must be enabled when Jetifier is enabled. To resolve, set android.useAndroidX=true in your gradle.properties file.

**Comment by Anay121** [comment]
Hey i'm having the same issue. Have you found any solution or fix to this?

**Comment by cadaniel** [comment]
Did you guys follow the instructions on https://github.com/cph-cachet/flutter-plugins/tree/master/packages/health

**Comment by Anay121** [comment]
Do you mean creating an OAuth2 for Google API?
I am trying the pedometer 1.2.0 package, so is that still required?

**Comment by cadaniel** [comment]
I mean following the section that says enable androidX

**Comment by Anay121** [comment]
Ah, yeah
all three lines are there
androidX, jetifer and the first line

**Comment by abhishekngen** [comment]
I seem to be having the same error. This is the error given: 
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':pedometer:verifyReleaseResources'.          
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/abhishekmanikandan/.gradle/caches/transforms-2/files-2.1/3aaf6e5219b7f981ec263df919098c6f/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /Users/abhishekmanikandan/.gradle/caches/transforms-2/files-2.1/3aaf6e5219b7f981ec263df919098c6f/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by thomasnilsson** [comment]
Use version 1.2.5 and use Android X
