### ISSUE TITLE
Android 10 permissions for activity recognition

### ISSUE THREAD

**Issue by bejaeger** [cph-cachet/flutter-plugins#99]
**Plugin name & version**
activity_recognition_flutter

**Describe the bug**
This is not a big issue but for Android 10 and higher the permission setting is a bit different, see [developers.google.com](https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognitionClient#requestActivityTransitionUpdates(com.google.android.gms.location.ActivityTransitionRequest,%20android.app.PendingIntent)), where it says:

For Android 10 (API level 29) and later: android.permission.ACTIVITY_RECOGNITION permission
For Android 9 (API level 28) and earlier: com.google.android.gms.permission.ACTIVITY_RECOGNITION permission

Might be helpful for future users to add that.

**Comment by thomasnilsson** [comment]
Thanks, I will update the documentation :)
