### ISSUE TITLE
[HEALTH 10.2.0] support for more Android health platforms

### ISSUE THREAD

**Issue by guyluz11** [cph-cachet/flutter-plugins#992]
### Description
It would be awesome if this package could support even more health platforms, specifically in Android side.

* [samsung-health](https://www.samsung.com/us/apps/samsung-health/)
* [HUAWEI Health Kit](https://developer.huawei.com/consumer/en/doc/HMS-Plugin-Guides/service-introduction-0000001073951368?ha_source=hms1)

### Additional information
Found a [huawei_health](https://pub.dev/packages/huawei_health) package, maybe we can integrate it for a seamless developer experience.

**Comment by SlimShadyIAm** [comment]
Hi, thanks for the suggestion! 

I agree that it would be really great to have one package for interacting with all the health platforms, but unfortunately we don't have the resources to maintain interaction with all the different APIs.
