### ISSUE TITLE
NUTRITION data is crashing the app

### ISSUE THREAD

**Issue by navaidali** [cph-cachet/flutter-plugins#994]
**We are using health: ^10.2.0**

When we try to read NUTRITION data from health connect, the app crashes. We have tried on multiple testing devices but the app crashes on all of the devices. The flutter app is unable to get NUTRITION Data.

**Code Causing the crash**

protein =  await health.getHealthDataFromTypes(
types: [HealthDataType.NUTRITION],startTime:startTime, endTime: endTime,includeManualEntry:false, 
);

**Comment by thelexhibition** [comment]
+1 Also interested in this fix

**Comment by shubhamsinghmutualmobile** [comment]
> **We are using health: ^10.2.0**
> 
> When we try to read NUTRITION data from health connect, the app crashes. We have tried on multiple testing devices but the app crashes on all of the devices. The flutter app is unable to get NUTRITION Data.
> 
> **Code Causing the crash**
> 
> protein = await health.getHealthDataFromTypes( types: [HealthDataType.NUTRITION],startTime:startTime, endTime: endTime,includeManualEntry:false, );

I hope this helps you: https://github.com/cph-cachet/flutter-plugins/issues/950#issuecomment-2271673230

**Comment by SlimShadyIAm** [comment]
Hi, 

Thanks for raising this issue. Are you experiencing this on Android or iOS?

**Comment by SlimShadyIAm** [comment]
This should be resolved in the upcoming 11.0.0 release.
