### ISSUE TITLE
[Health] Atrial fibrillation support

### ISSUE THREAD

**Issue by JulienRim** [cph-cachet/flutter-plugins#995]
### Description
Describe what you will like to see improved/added/removed.
Can you please add support for reading atrial fibrillation for Apple Watches and Galaxy Watches. 

### Additional information
It appears that these sync with [Apple Health](https://support.apple.com/en-ca/HT212214), but not clear if it is synced with [Google Health Connect, as it is not in the list of supported variables](https://developer.android.com/health-and-fitness/guides/health-connect/plan/data-types).

**Comment by SlimShadyIAm** [comment]
Hi @JulienRim, I can implement this but I don't have any AFib data in my Health app to test that it works and it seems like you need to wear an Apple Watch continuously for a week for it to calculate the required data. It would be great if you already have some data in your Health app to test with to make sure that it works.

**Comment by JulienRim** [comment]
Hi @SlimShadyIAm, 

I am working with my team to obtain suitable data to test this. We were hoping to explore reading AFib data for a future research.

**Comment by SlimShadyIAm** [comment]
Great, thank you! I'll let you know when I have a PR ready for it.

**Comment by SlimShadyIAm** [comment]
Hi @JulienRim, I've just opened #1027 to implement afib support. Could you please test that it works when you get the chance to? In the mean time, I've turned on AFib tracking on my own watch as well.

**Comment by SlimShadyIAm** [comment]
I've merged this for now but please let me know if you experience issues with it!
